### ISSUE TITLE
通用 Mapper 4.0 计划

### ISSUE THREAD

**Issue by abel533** [abel533/Mapper#100]
在 4.0 之前会针对 github 和 gitosc 的部分问题发布几个 3.x 版本。

最近 1 年多的时间因为新书的原因，维护的次数少了，新书在 6 月底出版后会有更多时间。

## 时间安排

- 3.x 会在 6 月中发布。
- 4.0 会在 7~8 月发布，中间会有 beta 版本。

## 4.0 大概计划如下，大家可以留言补充：

1. 4.0 兼容 3.x 版本，对业务代码没有任何影响。
2. 目的是减少或消除实体类中的注解（仍然支持注解）。
3. 增加通用接口级别的注解配置，提供更多的配置（包含实体类的通用配置），继承接口即可使用相应的配置。
4. 增加配置，可以直接使用 XML 中配置的 `resultMap`，方便手动配置详细信息。
5. 增加配置，允许通过 `<sql>` 定义某个具体方法的 SQL，允许出现一对一和一对多，`<sql>`可能会重新定义规则，支持某种模板语言。
6. 项目改为多模块，增加 mapper-extend 项目，提供更多针对性的接口。
7. 增加如 mapper-mysql，mapper-oracle 等和数据库具体相关的项目，针对不同数据库提供最佳实践，目的是在前面的基础上定义数据库规范（规范可以简单修改），符合规范的可以直接使用。
8. 简化 `MapperHelper` 和 `MapperTemplate` 逻辑。

## 已实现
1. 增强的Example，可以使用 and or 任意组合。

**Comment by leaf2436** [comment]
最好可以实现复杂查询的控制

**Comment by yangdq1** [comment]
有没有增加版本控制的可能

**Comment by Dreamroute** [comment]
@yangdq1 乐观锁插件https://github.com/Dreamroute/locker

**Comment by yangdq1** [comment]
@Dreamroute 谢谢 有没有支持Spring Boot呀

**Comment by syncml** [comment]
期待，别忘记dubbo的consumer端的 Example查询的支持哦

**Comment by Dreamroute** [comment]
@yangdq1 支持

**Comment by TianShiHeiDe** [comment]
厉害了，老哥。

**Comment by evan-luke** [comment]
1、最好增加一个可选的版本控制(乐观锁)功能
2、在通用方法的基础上，允许特定的mapper.xml使用自定义sql语句。即：定义了一个通用方法selectWahaha()，所有的dao通过继承baseDao后可以使用这个通用方法，然后某一个dao在其对应的XML文件里已经写了<select id="selectWahaha()">...</select>之后，这个dao的selectWahaha就不再会使用通用方法中的SQL语句进行操作，而是使用具体的XML文件里的SQL语句来进行操作
3、在 建议1 的基础上,可以做一些注解实现基础功能：带有注解的属性在进行update不参与set，而是作为where查询，比如可以弄个@UpdateWhere.。
4、在 建议3 的基础上，甚至可以做类似于validator的功能，就是分组。不同地分组的情况下可以有不同的@UpdateWhere执行

**Comment by weishuwei** [comment]
刚开始用，是不是已经支持了还没摸清，我也是比较建议关注点在注解上，可以基于注解做些扩展，比如：
1，null情况下默认值@Default注解
2，数据库是date类型的，实体我用String类型，可以定义formatString；实体是枚举，对应数据库是varchar
3，@version 乐观锁
4，级联操作
5，一对一、一对多、多对一关系
6，xxxMapper.xml可以注入动态生成的sql，这样复杂的查询，我也不需要因为调整了字段去改一下xml文件

**Comment by cmp-cc** [comment]
不建议增加： 一对一、一对多、多对一关系 ， 连这些代码都不想写的话，那干脆使用Hibernate 算了

实体类Model 中使用JPA注解，给我一种怪怪的感觉 ， 因为Mybatis 并没有实现JPA规范。

**Comment by Kanvin** [comment]
public interface InsertMapper<T> {

    /**
     * 保存一个实体，null的属性也会保存，不会使用数据库默认值
     *
     * @param record
     * @return
     */
    @InsertProvider(type = BaseInsertProvider.class, method = "dynamicSQL")
    int insert(T record);

}

字段null 报错
应该更新为空

**Comment by abel533** [comment]
@Kanvin Oracle ? jdbcTypeForNull = NULL

**Comment by Be-Curious-Children** [comment]
可否对存储过程的调用封装为一个mapper呢？

**Comment by abel533** [comment]
@Be-Curious-Children 存储过程看这儿：http://blog.csdn.net/column/details/mybatis-sample.html

**Comment by yangdq1** [comment]
哥，4.0 有最新进展么

**Comment by abel533** [comment]
@yangdq1 4.0 等mybatis官方消息，如果官方会合并 https://github.com/mybatis/mybatis-3/pull/1111 这个 PR，就会有 4.0。。现阶段准备添加更多通用方法。

**Comment by Ngone51** [comment]
@abel533 英文异常&英文文档

**Comment by windhc** [comment]
Example查询可以实现这样的方式吗？
```
List<User> list1  = userDao.createQuery().lamdba().andEq(User::getName, "hi").orderBy(User::getCreateDate).select();
```
感觉现在直接把表的列名写在字符串中不是很灵活

**Comment by abel533** [comment]
@windhc 看最新版本中的 `Weekend` 支持 java8 方式。
