### ISSUE TITLE
insert domain with default value 

### ISSUE THREAD

**Issue by jiahut** [abel533/Mapper#103]
目前数据库表定义中字段有默认值，比如 `status `默认值为`"0000"` ，这个在`insert object`的时候 如果没有设置过这个值的前提下期望是数据库定义的默认值？
 ` mybatis:general` 的时候能获取到DDL中字段的默认值，然后生成` private String status = "0000" `吗？

**Comment by abel533** [comment]
Selective 方法可以保留数据库的默认值。
