### ISSUE TITLE
setting配置了BATCH导致通用mapper增删改无效

### ISSUE THREAD

**Issue by benjaminwhx** [abel533/Mapper#107]
1、如果我配置了<setting name="defaultExecutorType" value="BATCH"/>默认batch提交的话，sqlSession自动提交会导致插入、更新、删除通用mapper失效。，如果关闭自动提交，得手动控制sqlSession进行commit，但是如果我针对一条id进行删除，类似于int i = mapper.deleteByPrimaryKey(7L);数据库这条数据执行成功了，但是返回值不是1，是-2147482646，这是不是有问题？
2、不配置<setting name="defaultExecutorType" value="BATCH"/>一切正常。

**Comment by abel533** [comment]
通用Mapper没有问题，mybatis在batch情况下，update时总是返回`BATCH_UPDATE_RETURN_VALUE = Integer.MIN_VALUE + 1002`.
