### ISSUE TITLE
Mapper自带的查询方法不能调用

### ISSUE THREAD

**Issue by Ancore01** [abel533/Mapper#108]
我用的框架 是spring boot +shiro
在集成Mapper时，自己在接口里写的查询方法是可以使用的
但是调用自身带就会报错：There was an unexpected error (type=Internal Server Error, status=500).
nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.base.BaseSelectProvider.dynamicSQL). Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.base.BaseSelectProvider

**Comment by aiqiao** [comment]
在网上查的错误信息，有说和shiro有关的，但是没找着解决办法，大佬能说说要怎么解决吗

**Comment by abel533** [comment]
shiro 调用方法过早，由于通用方法还没有初始化完成，所以调用出错。

暂时只能通过调用非通用方法解决。

**Comment by aiqiao** [comment]
有什么方法可以控制他们的顺序吗

**Comment by Ancore01** [comment]
您好！邮件已收到。
