### ISSUE TITLE
批量插入时如何去除重复数据？

### ISSUE THREAD

**Issue by wangh09** [abel533/Mapper#109]
请问批量插入时如何避免重复数据？即 replace into 或者 insert ignore. 谢谢～

**Comment by abel533** [comment]
插入前去重。

**Comment by wangh09** [comment]
这样效率很低呀，要先把所有记录search一遍，去重再插入

**Comment by wangh09** [comment]
能否在SpecialProvider 拼字段的时候用replace？或者给一个配置可以配置成普通insert 或 replace。毕竟批量插入的时候经常容易因为一条的重复导致所有数据都没插进去

**Comment by wangh09** [comment]
好吧，最后还是靠自己解决了这个问题，方法如下：
定义一个ReplaceProvider:
`public class ReplaceProvider extends MapperTemplate {
    public ReplaceProvider(Class<?> mapperClass, MapperHelper mapperHelper) {
        super(mapperClass, mapperHelper);
    }
    public String insertListReplace(MappedStatement ms) {
        final Class<?> entityClass = getEntityClass(ms);
        //开始拼sql
        StringBuilder sql = new StringBuilder();
        sql.append("REPLACE INTO ");
        sql.append(SqlHelper.getDynamicTableName(entityClass,tableName(entityClass)));
        sql.append(" ");
   //     sql.append(SqlHelper.insertIntoTable(entityClass, tableName(entityClass)));
        sql.append(SqlHelper.insertColumns(entityClass, true, false, false));
        sql.append(" VALUES ");
        sql.append("<foreach collection=\"list\" item=\"record\" separator=\",\" >");
        sql.append("<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">");
        //获取全部列
        Set<EntityColumn> columnList = EntityHelper.getColumns(entityClass);
        //当某个列有主键策略时，不需要考虑他的属性是否为空，因为如果为空，一定会根据主键策略给他生成一个值
        for (EntityColumn column : columnList) {
            if (!column.isId() && column.isInsertable()) {
                sql.append(column.getColumnHolder("record") + ",");
            }
        }
        sql.append("</trim>");
        sql.append("</foreach>");
        return sql.toString();
    }
}`

然后在Mapper中定义方法：
`@Options(useGeneratedKeys = true, keyProperty = "id")
    @InsertProvider(type = ReplaceProvider.class, method = "dynamicSQL")
    int InsertListReplace(List<T> recordList);`
这样Service就可以调用这个insertListReplace进行去重的批量插入了。
