### ISSUE TITLE
通用mapper，字段名，表明没有添加autoDelimitKeywords"`"的选项

### ISSUE THREAD

**Issue by huanzhang** [abel533/Mapper#110]
我有个表名是order，调用通用的mapper时，报错：
SQL: SELECTfield1,field2,field3 FROM order
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException:

**Comment by abel533** [comment]
给实体类加注解`@Table(name="反单引号order反单引号")`

**Comment by huanzhang** [comment]
@abel533 这个也可以。。。

**Comment by abel533** [comment]
markdown 里面的反单引号没法直接写出来。\`

**Comment by goodcto** [comment]
oracle 咋整
