### ISSUE TITLE
【无法获取实体类对应的表名】

### ISSUE THREAD

**Issue by wlkfec** [abel533/Mapper#111]
我在开发 SpringBoot 应用，使用了通用 Mapper 的功能，当我引入了热部署插件 spring-boot-devtools 之后，便出现了无法获取实体类对应的表明异常，但是不是所有的实体都找不到，是部分，我看了半天源代码也没找到是哪里的问题，猜想大概是哪些东西冲突导致的，请检查指教。

**Comment by abel533** [comment]
看通用Mapper首页 devtools 配置。或者用最新版本。
