### ISSUE TITLE
@GeneratedValue(generator = "JDBC") 与mycat 共同使用 插入依然会发出 id 字段

### ISSUE THREAD

**Issue by Darkthas** [abel533/Mapper#115]
@GeneratedValue(generator = "JDBC") 与mycat 共同使用 插入依然会发出 id 字段 导致columnValue:NULL Please eliminate any quote and non number within it.

3.4.2

**Comment by abel533** [comment]
可以试试`insertable=false`

**Comment by qrqhuang** [comment]
postgres数据库也有这个问题，加上这个属性可以用， 但MBG不能完全自动化配置了。  不知能否完美解决，谢谢。

**Comment by abel533** [comment]
@qrqhuang 如果抽出一个基类，配置rootclass就能解决。
