### ISSUE TITLE
通用mapper如何使用逻辑删除？

### ISSUE THREAD

**Issue by 844189873** [abel533/Mapper#117]
数据库使用的是逻辑删除，使用通用mapper实现的单表的crud，应该怎么做？
由于逻辑删除，原来的delete就得用改用update来做，同时原来的select里面都得加上逻辑删除的标志那个条件。这样的话，通用mapper实现的单表的crud就用不了。

**Comment by abel533** [comment]
详细说明一下，你逻辑删除的时候是如何更新的。

**Comment by 844189873** [comment]
所有的业务表中都有一个delFlag字段，用来标识数据是否已逻辑删除，它取的取值为：0-正常、1-删除、2-审核。我想使用通用mapper删除时自动更新此字段的值为1，查询时自动加上delFlag=0条件。

如下代码，我是想封装个业务基类（BaseCrudExtService类），在里面实现增删改查，删的时候做逻辑删除，查的时候也加上逻辑删除这个标识这个段件，但是不知道用通用mapper该怎么处理。

实体基类：
`
public abstract class BaseDataExtEntity<T> extends BaseExtEntity<T> {

	private static final long serialVersionUID = 1L;

	protected String delFlag; // 删除标记（0：正常；1：删除；2：审核）

	public BaseDataExtEntity() {
		super();
		this.delFlag = DEL_FLAG_NORMAL;
	}

	public BaseDataExtEntity(String id) {
		super(id);
	}

	@JsonIgnore
	@Length(min = 1, max = 1)
	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * 删除标记（0：正常；1：删除；2：审核；）
	 */
	public static final String DEL_FLAG_FIELD_NAME = "delFlag";
}
`



业务基类：
`
public abstract class BaseCrudExtService<T extends BaseExtEntity<T>> {

	/**
	 * 持久层对象
	 */
	@Autowired
	protected Mapper<T> dao;

	/**
	 * 获取单条数据
	 * 
	 * @param id
	 * @return
	 */
	public T get(String id) {
		return dao.selectByPrimaryKey(id);
	}

	/**
	 * 获取单条数据
	 * 
	 * @param entity
	 * @return
	 */
	public T get(T entity) {
		return dao.selectOne(entity);
	}

	/**
	 * 查询列表数据
	 * 
	 * @param entity
	 * @return
	 */
	public List<T> findList(T entity) {
		return dao.select(entity);
	}

	/**
	 * 查询分页数据
	 * 
	 * @param page
	 *            分页对象
	 * @param entity
	 * @return
	 */

	public <S extends T> Page<T> findPage(Page<T> page, final S parameter) {
		page = PageHelper.startPage(page.getPageNum(), page.getPageSize()).doSelectPage(new ISelect() {
			@Override
			public void doSelect() {
				dao.select(parameter);
			}
		});

		return page;
	}

	/**
	 * 保存数据（插入或更新）
	 * 
	 * @param entity
	 */
	@Transactional(readOnly = false)
	public void save(T entity) {
		if (entity.getIsNewRecord()) {
			entity.preInsert();
			dao.insert(entity);
		} else {
			entity.preUpdate();
			dao.updateByPrimaryKey(entity);
		}
	}

	/**
	 * 插入数据
	 * 
	 * @param entity
	 */
	@Transactional(readOnly = false)
	public void insert(T entity) {
		entity.preInsert();
		dao.insert(entity);
	}

	/**
	 * 更新数据
	 * 
	 * @param entity
	 */
	@Transactional(readOnly = false)
	public void update(T entity) {
		entity.preUpdate();
		dao.updateByPrimaryKey(entity);
	}

	/**
	 * 删除数据
	 * 
	 * @param entity
	 */
	@Transactional(readOnly = false)
	public void delete(T entity) {
		dao.delete(entity);
	}

	/**
	 * 通过id删除数据
	 * 
	 * @param entity
	 */
	@Transactional(readOnly = false)
	public int delete(String id) {
		return dao.deleteByPrimaryKey(id);
	}

}
`
mapper类：
`
public interface CmsInfoMapper extends Mapper<CmsInfo> {

}
`

业务service：
`
@Service
@Transactional(readOnly = true)
public class CmsInfoService extends CrudExtService<CmsInfo> {

	@Autowired
	private CmsInfoMapper dao;

	public CmsInfo delete(CmsInfo cmsInfo) {
		return this.delete(cmsInfo);
	}

	public CmsInfo select(String id) {
		return this.select(id);
	}

	public List<BannerListResp> findBannerList(BannerListParam parameter) {
		return dao.findBannerList(parameter);
	}
	
	public List<ActiveListResp> findActiveList(ActiveListParam parameter) {
		return dao.findActiveList(parameter);
	}
}

`
