### ISSUE TITLE
springboot项目，如何配置输出sql语句在控制台上显示

### ISSUE THREAD

**Issue by longzhiwuing** [abel533/Mapper#119]

**Comment by longzhiwuing** [comment]
解决了，在application.properties中配置mybatis.config-location指定一个mybatis的config文件，指定settings为logImpl即可，有没有更优雅的方式？或者springboot里直接能在application.properties直接指定呢？

**Comment by abel533** [comment]
如果是spring boot，可以直接配置这个属性。
`mybatis.config.log-impl=`

**Comment by Lxjazni7** [comment]
logging:
  level:
    com.lxjazni.library.mapper: trace 我是这样配的 改成你自己的包应该就可以

**Comment by Joker1995** [comment]
默认采用Logback.xml配置日志,添加<logger name="com.xx.xx.mapper" level="trace"/>即可，其他不用配置
