### ISSUE TITLE
Mapper/src/main/java/tk/mybatis/mapper/util/StringUtil.java 第127行

### ISSUE THREAD

**Issue by jessezwd** [abel533/Mapper#12]
`public static char toUpperAscii(char c) {
        if (isUppercaseAlpha(c)) { //127
            c -= (char) 0x20;
        }
        return c;
    }`
` if (isUppercaseAlpha(c))` 应为` if (isLowercaseAlpha(c))`

**Comment by 269941633** [comment]
什么时候支持批量插入，是id没自增限制的

**Comment by abel533** [comment]
一直忘了注意这个问题，下个版本会修复。

**Comment by abel533** [comment]
3.3.8 已修复。
