### ISSUE TITLE
Example设计问题

### ISSUE THREAD

**Issue by nickt2007** [abel533/Mapper#125]
不确定是Example的设计问题，还是我自己没有考虑周全，
问题是这样的，

假如
```
example.createCriteria().andEqualTo("username", 参数);
mapper.deleteByExample(example);
```
如果此时，参数为非null值 ，则执行的SQL语句形如：delete from table where username=参数
但是，如果此时参数为null的话，执行SQL语句: delete from table，要命的问题就是，整个表内容都删除了（根据你的文档说明，为空的值不会放入where条件），
当然可以像下面这样处理，
```
if(参数 ==null) {
example.createCriteria().andIsNull("username");
}
else {
example.createCriteria().andEqualTo("username", 参数);
}
```
你能否把此判断逻辑整合进example当中呢？

**Comment by abel533** [comment]
```java
/**
 * 带exists参数的构造方法
 *
 * @param entityClass
 * @param exists      - true时，如果字段不存在就抛出异常，false时，如果不存在就不使用该字段的条件
 * @param notNull     - true时，如果值为空，就会抛出异常，false时，如果为空就不使用该字段的条件
 */
public Example(Class<?> entityClass, boolean exists, boolean notNull)
```

有这样的构造方法。第三个参数可以控制。

**Comment by nickt2007** [comment]
有时候当值为null值，并不希望抛出异常，也不希望丢掉此条件，而是希望SQL语句继续执行下去

**Comment by yangdq1** [comment]
@abel533  那如果不是Example，而是delete(T record)方法呢，个人觉得delete有点危险，是否可以加入deleteAll方法，而调整下原先的delete逻辑呢？谢谢～

**Comment by yangdq1** [comment]
@abel533  那如果不是Example，而是delete(T record)方法呢，个人觉得delete有点危险，是否可以加入deleteAll方法，而调整下原先的delete逻辑呢？谢谢～

**Comment by abel533** [comment]
@yangdq1 有过这种考虑。考虑增加。
