### ISSUE TITLE
想问下Mapper和mybatis-plus项目的异同和特色

### ISSUE THREAD

**Issue by quqiangsheng** [abel533/Mapper#126]
同类型的发现这两个用的都挺多，想请教一下涉及思想上和具体实现上有什么不同？或者说各自的最具特色的功能是什么呢？感谢作者

**Comment by abel533** [comment]
通用Mapper更轻量级，属于参考mybatis generator生成器实现的扩展，和mybatis集成更好，更接近mybatis.

mybatis-plus是直接重新实现mybatis许多类，替换了mybatis本身的许多功能，相对更重。他提供了各种各样的插件和功能，比单纯的通用Mapper要大。

关于两者对比，可以参考我从mybatis-plus改成通用Mapper的guns项目，对比地址如下：

https://github.com/abel533/guns/commit/6644cadaf612fb444b4d12ee557d11be6bf4eb24?diff=split

**Comment by quqiangsheng** [comment]
明白，感谢~
