### ISSUE TITLE
id是Long类型时的问题

### ISSUE THREAD

**Issue by zyw** [abel533/Mapper#129]
数据库的类型是bigint实体中的类型是Long，在调用通用Map的*ByPrimaryKey系列方法是会报
```java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer```异常。请问如何解决?

**Comment by abel533** [comment]
你实体类用的Integer，所以参数也要用int类型。

**Comment by zyw** [comment]
已经解决了，我的实体类里面是Long型，在id上添加@Id注解，就OK了，谢谢。
