### ISSUE TITLE
UUID主键

### ISSUE THREAD

**Issue by kingkong4646** [abel533/Mapper#13]
如果主键策略为UUID，新增后无法获取到生成的主键

**Comment by abel533** [comment]
UUID本来就不回写，文档都写了。。。

你再仔细看看文档。。

UUID另一种方式:

______________________下面这个提醒很重要______________________

重要提醒：IDENTITY除了上面这些选项外，还可以是任意可以执行的SQL，例如MySql的select uuid(),SqlServer的select newid()等等，这种情况下需要保证主键的类型和SQL的返回值一致。

利用这一个特点，我们就可以使用可以回写的UUID值，如果想获得更特殊的主键值，可以自己写函数调用。

**Comment by 010239** [comment]
反向生成的实体，应该实现序列化接口，因为要通过网络传输 。

**Comment by abel533** [comment]
@010239 看 mybatis.tk 上面的mbg文档，自己找其中一个插件！
