### ISSUE TITLE
请问通用mapper支持postgresql的sequence自增主键吗？

### ISSUE THREAD

**Issue by westmelon** [abel533/Mapper#130]

**Comment by abel533** [comment]
类似oracle序列方式还是mysql自增方式？

**Comment by westmelon** [comment]
类似oracle序列，写在xml里面类似下面这样
`<insert id="insert" parameterType="test.modelAgain.UserAgain" >
      <selectKey keyProperty="id" resultType="int" order="BEFORE">
        SELECT nextval('test_a_id_seq'::regclass) as id  
    </selectKey>
    
    insert into test_a (id, name)
    values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})
  </insert>`

请问怎么用mgb和tk插件生成上述功能？

**Comment by ccfish86** [comment]
这个我手动试过，但生成client代码的时候，总不理想。
dao里指定：
```
    @InsertProvider(type = BaseInsertProvider.class, method = "dynamicSQL")
    @Options(useGeneratedKeys = true, keyColumn = "id", keyProperty = "id")
    @Override
    int insertSelective(SmsSendResult record);
    
    @Options(useGeneratedKeys = true, keyColumn = "id", keyProperty = "id")
    @InsertProvider(type = BaseInsertProvider.class, method = "dynamicSQL")
    @Override
    int insert(SmsSendResult record);
```
然后在entity里指定
```
    @Id
    @Column(insertable = false)
    private Long id;
```
这样，自增主键id就可以取到返回的值了。而且这种设定，可能在mysql或oracle里也可以（有条件的帮忙测试下）。

PS：代码生成的那儿，什么时候能把`@Column(insertable = false)`生成到entity的字段里？？要不然这在动态sql(dao.insert)时，会造成id空值。

**Comment by abel533** [comment]
加这个注解或者调用sqlserver特有的insert方法都行，目的都是不让id出现在插入列中。

**Comment by ccfish86** [comment]
mybatis其实实际执行的时候已经支持insertable =false（updatable没确认）了，但在代码生成模块`tk.mybatis.mapper.generator.MapperCommentGenerator.addFieldComment(Field, IntrospectedTable, IntrospectedColumn)`，只支持`@Column -name`的定义，我是否应该自己拿过来改一下，让它支持这么搞:
```
        if (!column.equals(introspectedColumn.getJavaProperty())) {
            //@Column
            field.addAnnotation("@Column(name = \"" + getDelimiterName(column) + "\")");
        } else if (StringUtility.stringHasValue(beginningDelimiter) || StringUtility.stringHasValue(endingDelimiter)) {
            field.addAnnotation("@Column(name = \"" + getDelimiterName(column) + "\")");
        } else if(forceAnnotation){
            field.addAnnotation("@Column(name = \"" + getDelimiterName(column) + "\")");
        }
```
