### ISSUE TITLE
写了个java8才能用的扩展，帮忙看看能不能加入到特性中

### ISSUE THREAD

**Issue by liuyuyu** [abel533/Mapper#137]
https://github.com/liuyuyu/weekend
不想影响向下兼容，又不想在Example.Criteria拼条件的时候传字符串，就自己开了个新仓库。看看什么方式加入到Mapper比较靠谱

**Comment by abel533** [comment]
新增的这种方式非常好，可以考虑在不影响低版本使用的情况下，直接加到 Mapper 中。

我找时间好好看看。

**Comment by liuyuyu** [comment]
java8还不算特别普及，感觉放到扩展里更容易兼容

**Comment by abel533** [comment]
加个QQ吧：120807756
我准备试试下面这种方式：
这个项目单独用java8打jar包，然后引入到java6打包的mapper中。

**Comment by abel533** [comment]
已经测试成功了，最终可以将java8的代码打包到java6中。

在java8中可以用。

**Comment by liuyuyu** [comment]
嗯.... 刚刚才想起来 jackson对java8的支持也是这么搞的。但是如果放到另外的jar里，不能覆盖原来的字符串写法，估计还是习惯性的用原来的写法。另外QQ加你了，如果没收到。麻烦加我一下791411860

**Comment by windhc** [comment]
请问一下，这个功能加到当前版本了吗

**Comment by abel533** [comment]
@windhc 最新的几个版本已经有这个功能了。
