### ISSUE TITLE
可否直接使用@Autowired Mapper<ClassA> mapper

### ISSUE THREAD

**Issue by s-mop** [abel533/Mapper#138]
目前 我必须定义一个mapper的interface
public interface ClassAMapper extends Mapper<ClassA> {...}

才能够在ClassAService中像标题中那样使用mapper

有没有办法可以让我不必创建那个ClassAMapper,而是直接在service中使用`Mapper<ClassA> mapper`

**Comment by abel533** [comment]
没有办法，由于泛型调用和mybatis接口命名空间的关系，必须有具体的接口。

**Comment by s-mop** [comment]
多谢答疑
