### ISSUE TITLE
MyBatis Generator插件生成代码时可以去掉表前缀么？

### ISSUE THREAD

**Issue by xhusky** [abel533/Mapper#139]
比如表`sys_user`，这里`sys_`是模块名称，默认情况

model --> `SysUser` 
mapper --> `SysUserMapper`

可否设定为：

model  --> `User` 
mapper  --> `UserMapper`

多谢。

**Comment by abel533** [comment]
目前不行，官方最新MBG实现了这个功能，但是还没有发布。

**Comment by xhusky** [comment]
@abel533 好的，非常感谢，我关注一下
