### ISSUE TITLE
PDF的简单教程文档是不是该更新了？

### ISSUE THREAD

**Issue by isCoding** [abel533/Mapper#14]
我按照教程没有找到叫做MapperInterceptor的类，版本3.3.6

**Comment by abel533** [comment]
新版本早就去掉这个类了，看项目文档！

**Comment by isCoding** [comment]
@abel533 我下载了md中提到的`通用Mapper简单实用文档.pdf`，里面的配置还是旧的`MapperInterceptor`,可能会对我这样的新用的人产生误导。

**Comment by abel533** [comment]
这段去掉了。
