### ISSUE TITLE
通用mapper关于oracle中date,timestamp

### ISSUE THREAD

**Issue by emohee** [abel533/Mapper#140]
数据库是oracle；例如某个字段：ADDDATE，数据库中是Date型；现在用通用mapper生成后，XML中jdbcType="TIMESTAMP"，类中类型java.util.Date，通过通用mapper插入数据库中，参数转化为2017-08-29 21:22:30.927(Timestamp)，插入数据库中为2017-08-29 21:22:30；如果想用此字段作为检索条件，参数也会转化为2017-08-29 21:22:30.927(Timestamp)，检索不到数据；用typeHandler等转化暂时没实现参数2017-08-29 21:22:30，请指点下。

**Comment by abel533** [comment]
我简单测试了，日志如下：
```sql
DEBUG [main] - ==>  Preparing: select * from sys_user where create_time = ? 
DEBUG [main] - ==> Parameters: 2016-06-07 01:11:12.000000088(Timestamp)
TRACE [main] - <==    Columns: id, user_name, user_password, user_email, user_info, head_img, create_time
TRACE [main] - <==        Row: 1, admin, 123456, admin@mybatis.tk, <<BLOB>>, <<BLOB>>, 2016-06-07 01:11:12.0
DEBUG [main] - <==      Total: 1
```
Parameters 显示的 timestamp 是调用的`toString` 方法，数据库真正使用的值不是这个，我使用这种方式能正确查询出数据。

我用的mysql，开启sql日志后，mysql真正执行的sql如下：
```sql
select * from sys_user where create_time = '2016-06-07 01:11:12.0'
```

**Comment by abel533** [comment]
oracle上日期查询一般都是`to_char`进行比较吧。

**Comment by abel533** [comment]
把对象和调用代码发出来看看！
