### ISSUE TITLE
重复生成selectByExample等

### ISSUE THREAD

**Issue by Erik-Augustus** [abel533/Mapper#145]
使用的是maven插件
![m 81 nz7 _pvsu0ky4m75ht](https://user-images.githubusercontent.com/10594972/30311203-c0405f8a-97c6-11e7-878e-8c396bbab209.png)

## 生成出来的mapper文件和项目文档里描述的不一样了，多了这5个方法，其中selectByExample在接口中也有定义，导致项目无法启动！**

![mw6 2oyuo 65ithgjx23bxv](https://user-images.githubusercontent.com/10594972/30311204-c2cccf18-97c6-11e7-8601-93caa6d37967.png)

不知道是什么配置有问题

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">

<generatorConfiguration>
    <classPathEntry location="C:\Users\Administrator\.m2\repository\mysql\mysql-connector-java\5.1.43\mysql-connector-java-5.1.43.jar" />

    <context id="Mysql" targetRuntime="MyBatis3"  defaultModelType="flat">

        <plugin  type="tk.mybatis.mapper.generator.MapperPlugin">
        <property name="mappers" value="tk.mybatis.mapper.common.Mapper"/>
        </plugin>

        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://192.168.18.117:3306/api_platform"
                        userId="root"
                        password="11111111">
        </jdbcConnection>

        <javaModelGenerator targetPackage="com.fcr.api_platform.model.base.bo" targetProject="E:\api_platform\src\main\java">
            <property name="enableSubPackages" value="true" />
            <property name="trimStrings" value="true" />
        </javaModelGenerator>

        <sqlMapGenerator targetPackage="com.fcr.api_platform.model.base.mapper"  targetProject="E:\api_platform\src\main\java">
        </sqlMapGenerator>

        <javaClientGenerator type="XMLMAPPER" targetPackage="com.fcr.api_platform.model.base.mapper"  targetProject="E:\api_platform\src\main\java">
            <property name="enableSubPackages" value="true" />
        </javaClientGenerator>

        <table tableName="project"></table>
        <table tableName="endpoint"></table>
        <table tableName="project_config"></table>
        <table tableName="service"></table>

    </context>
</generatorConfiguration>

**Comment by abel533** [comment]
targetRuntime="MyBatis3" 错了。
