### ISSUE TITLE
mysql 数据库名、表名、字段名，包含关键词，报sql异常

### ISSUE THREAD

**Issue by qlnujsjlzy** [abel533/Mapper#147]
mysql 数据库名、表名、字段名，包含关键词，自动拼接的sql，没有添加` 反勾号（Esc下面的那个键）做转义。导致查询报sql错误。如  `describe`

**Comment by qlnujsjlzy** [comment]
项目历史原因，字段名包含关键词

**Comment by abel533** [comment]
加注解指定：@Column(name="\`describe\`")

**Comment by qlnujsjlzy** [comment]
thank you

**Comment by qzmer1104** [comment]
不能生成器，或者拼接脚本时处理一下吗？
