### ISSUE TITLE
使用聚合模型泛型到通用mapper中启动报错

### ISSUE THREAD

**Issue by AmadeusSys** [abel533/Mapper#148]
使用如下model 就会启动异常, 这是
```java
public class CateRuleDTO {

    private CateDO cateDO = new CateDO();

    private RuleDO ruleDO = new RuleDO();
}
```
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.pagehelper.autoconfigure.MapperAutoConfiguration': Invocation of init method failed; nested exception is tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
```

**Comment by AmadeusSys** [comment]
我主要是想解决联合查询model碎片化 ,其他关联查询使用DTO的形式储存查询结果集,那么需要在model中直接创建DO ,主要问题有两个 能否根据get方法获取查询字段,为何在model中使用new 就不能启动了呢~

**Comment by abel533** [comment]
加注解忽略非表字段，另外，表中必须有字段。

**Comment by nickzhangf** [comment]
@abel533 您好，我也遇到同样的问题，由于集成的是第三方的数据库，可能表的字段命名不太规范，但是我已经给每个字段加了“ @Column()”注解；另外我也仔细比对了每个字段，应该没问题，请问还有什么情况会报这个错，谢谢

**Comment by AmadeusSys** [comment]
我后来没有采用聚合模型的通用查询，因为聚合模型应用场景没有办法标准化各有个的需求，所以放弃了这个想法，不过你可以使用@Transient字段忽略字段，并且通用mapper要求一个model下必须有一个属性空的类是不可以使用的

**Comment by nickzhangf** [comment]
@AmadeusSys 我没有要忽略的字段，model和表字段是一一对应的，报了那个错，搞不懂

**Comment by abel533** [comment]
各位还有错吗？
