### ISSUE TITLE
通用mapper 如何才能自定义查询结果的影射呢，是通过xml吗？

### ISSUE THREAD

**Issue by AmadeusSys** [abel533/Mapper#149]
我想自己重新定义数据到model之间的影射 但是没找到方法

**Comment by abel533** [comment]
通用Mapper用的注解。自己写的方法需要自己配置映射关系。

**Comment by 30743905** [comment]
通用mapper用注解，自己xml用配置resultMap，要同时维护两份配置，有没有共同使用一种方式的？

**Comment by dcy10000** [comment]
不通用一个 resultmap，这个实在太坑了。这个不解决，感觉还不如不用
