### ISSUE TITLE
什么时候支持批量插入，是id没自增限制的

### ISSUE THREAD

**Issue by 269941633** [abel533/Mapper#15]
什么时候支持批量插入，是id没自增限制的

**Comment by abel533** [comment]
你是指不需要考虑id？

**Comment by 269941633** [comment]
是的，id预先设置的了，不需要使用策略自动生成

**Comment by 269941633** [comment]
`/**
     * 批量插入，支持批量插入的数据库可以使用，例如MySQL,H2等，另外该接口限制实体包含`id`属性并且必须为自增列
     *
     * @param recordList
     * @return
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @InsertProvider(type = SpecialProvider.class, method = "dynamicSQL")
    int insertList(List<T> recordList);

    /**
     * ======如果主键不是id怎么用？==========
     * 假设主键的属性名是uid,那么新建一个Mapper接口如下
     * <pre>
        public interface InsertUidListMapper<T> {
            @Options(useGeneratedKeys = true, keyProperty = "uid")
            @InsertProvider(type = SpecialProvider.class, method = "dynamicSQL")
            int insertList(List<T> recordList);
        }
     * 只要修改keyProperty = "uid"就可以
     *
     * 然后让你自己的Mapper继承InsertUidListMapper<T>即可
     *
     * </pre>
     */`

按照源码这说法就是id要自增。。。。同时看了下生成的sql，insert的sql,它去掉了id

**Comment by abel533** [comment]
以后增加这样的方法。

**Comment by ltylty** [comment]
现在有这个方法了没？
