### ISSUE TITLE
继承MyMapper方法后调用delete方法，若所传参数为null，则会删除全表

### ISSUE THREAD

**Issue by liangjiange** [abel533/Mapper#151]
通用Mapper 3.3.9版本，自动生成的PeopleHasCardMapper extends MyMapper<T>
若delete方法中所传参数为null，则会删除全表

比如
`        PeopleHasCard peopleHasCard = peopleHasCardMapper.selectByPeople((byte) 0, renterId);
          peopleHasCardMapper.delete(peopleHasCard);
`
若此处peopleHasCard为null，调用peopleHasCardMapper的delete方法时，会删除people_has_card全表数据

**Comment by abel533** [comment]
做好非null参数校验！

**Comment by drtrang** [comment]
从设计上来看没什么问题，`mapper.delete()` 方法接收一个 JavaBean 作为参数，那么参数自然可以为 null，尽量从 dao 的 上层保证参数校验。
也可以用其它实现方式，例如通过 druid 的 wall-filter 来禁止 deletelAll 行为。

**Comment by abel533** [comment]
4.0 增加了 safeDelete 参数，配置后不能进行删除全表的操作。

**Comment by drtrang** [comment]
@abel533 4.0 有发布时间点吗？

**Comment by abel533** [comment]
@drtrang  这个周末会发布 beta 版，正式版估计还需要时间。

目前可以使用 4.0.0-SNAPSHOT 测试。
