### ISSUE TITLE
请问能为目前mapper提供的MBG生成实体添加模板生成自定义的方法吗？

### ISSUE THREAD

**Issue by BigBroB** [abel533/Mapper#153]
目前mapper提供的MBG生成实体只能生成geter， seter方法，
无法自定义生成自己想要的其他方法，例如builder等。
这个功能能否加入呢？

**Comment by abel533** [comment]
目前不能，后续也没计划。

最简单的办法是用lombok，加个注解就行了。

**Comment by drtrang** [comment]
通用Mapper生成Model类是通过 `tk.mybatis.mapper.generator.MapperPlugin` 实现的，如果不满意可以自定义一个 MapperPlugin，我这有个作为参考：![MapperPlugin](https://github.com/drtrang/mybatis-generator-extension/blob/master/src/main/java/com/github/trang/mybatis/generator/plugins/MapperPlugin.java)

**Comment by BigBroB** [comment]
谢谢
