### ISSUE TITLE
通过通用Mapper保存时，如何返回Oracle序列生成的ID值

### ISSUE THREAD

**Issue by void0720** [abel533/Mapper#155]
`public interface InsertMapper<T> {

    /**
     * 保存一个实体，null的属性也会保存，不会使用数据库默认值
     *
     * @param record
     * @return
     */
    @InsertProvider(type = BaseInsertProvider.class, method = "dynamicSQL")
    int insert(T record);

}`

**Comment by abel533** [comment]
看文档中oracle序列方式
