### ISSUE TITLE
mapper.xml中自定义条件的查询 无法查询到相应结果

### ISSUE THREAD

**Issue by waveChou** [abel533/Mapper#156]
<select id="selectQuestionByKeywords" parameterType="java.lang.String" resultMap="BaseResultMap">
      SELECT * FROM question WHERE id=1
    </select>
这个sql 能查询到结果，因为id的model 注解有@Id.    **用其他字段作为条件时，就不能查询到结果。**
    <select id="selectQuestionByKeywords" parameterType="java.lang.String" resultMap="BaseResultMap">
      **SELECT * FROM question WHERE keywords="入库";**
    </select>
就算这个sql 写上固定的where 条件都不能查询到正确数据。  有没有人遇到过这个问题？

**Comment by abel533** [comment]
把真实代码贴出来看看。

**Comment by waveChou** [comment]
@Service
public class QuestionService extends BaseService<QuestionMapper, Question> {

    @Autowired
    QuestionMapper questionMapper;

    /**
     * @param keywords
     * @return Question
     */
    public Question selectQuestionByKeywords(String keywords) {
        System.out.println("QuestionService selectQuestionByKeywords keywords:" + keywords);
        return questionMapper.selectQuestionByKeywords(keywords);
//        return questionMapper.selectQuestionByKeywords("入库");
    }
}


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.duolun.robot.mapper.QuestionMapper">
    <resultMap id="BaseResultMap" type="com.duolun.robot.model.Question">
        
        <result column="id" jdbcType="BIGINT" property="id"/>
        <result column="type" jdbcType="VARCHAR" property="type"/>
        <result column="keywords" jdbcType="VARCHAR" property="keywords"/>
        <result column="is_used" jdbcType="BIT" property="isUsed"/>
        <result column="is_deleted" jdbcType="BIT" property="isDeleted"/>
        <result column="answer" jdbcType="LONGVARCHAR" property="answer"/>
    </resultMap>
    <select id="selectQuestionByKeywords" parameterType="java.lang.String" resultMap="BaseResultMap">
      SELECT * FROM question WHERE keywords=#{keywords}
    </select>
</mapper>


@Table(name = "question")
public class Question {
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private Long id;

    @Column(name = "type")
    private String type;

    @Column(name = "keywords")
    private String keywords;

    @Column(name = "is_used")
    private Boolean isUsed;

    @Column(name = "is_deleted")
    private Boolean isDeleted;

    @Column(name = "answer")
    private String answer;
get set 略
}

**Comment by waveChou** [comment]
**感谢作者大神的回复！**
现在问题已经发现，原因是：别人改动了db的链接编码，与本地环境不一致造成的问题！pull 下来的文件太多。没有看到并想到这个问题。
希望大家统一编码！切记！标准规范，提高质量和效率！
