### ISSUE TITLE
InsertListMapper.insertList这个接口是不是不支持动态表名

### ISSUE THREAD

**Issue by nickt2007** [abel533/Mapper#157]
版本：3.4.0
InsertListMapper.insertList这个接口是不是不支持动态表名（IDynamicTableName）？

**Comment by abel533** [comment]
支持。。可以在这个方法断点看生成的xml。。

**Comment by nickt2007** [comment]
我试过的，不支持，会报错 
通过debug,会进入tk.mybatis.mapper.util.OGNL.isDynamicParameter(Object parameter)方法，
此时这个参数parameter的类型是class org.apache.ibatis.session.defaults.DefaultSqlSession$StrictMap

if (parameter != null && parameter instanceof IDynamicTableName) {
            return true;
        }
这个判断明显返回false, 就取不到动态表名。

**Comment by abel533** [comment]
明白了，确实不支持，因为参数是个集合，取不到。

**Comment by nickt2007** [comment]
我自己改了一下，下面这样就可以支持了

public static boolean isDynamicParameter(Object parameter) {
    	if (parameter != null && parameter instanceof Map) {
    		Map<String, Object> map = (Map<String, Object>)parameter;
    		List<Object> list = (List<Object>)map.get("list");
    		if (CollectionUtils.isNotEmpty(list)) {
    			if(list.get(0) instanceof IDynamicTableName) {
    				IDynamicTableName dynamicTableName = (IDynamicTableName)list.get(0);
    				map.put("dynamicTableName", dynamicTableName.getDynamicTableName());
    				return true;
    			}
    		}
    	}
        if (parameter != null && parameter instanceof IDynamicTableName) {
            return true;
        }
        return false;
    }

**Comment by chenquan1992** [comment]
请问一下isDynamicParameter在哪里修改的？

**Comment by qxwei** [comment]
@nickt2007 重新生成jar包了吗？ 不生成可以实现吗？

**Comment by qxwei** [comment]
@abel533 优化下咯，或者我发个request
