### ISSUE TITLE
通用mapper的select(T)功能能做到like查询吗??

### ISSUE THREAD

**Issue by reesechou2014** [abel533/Mapper#164]
1.假设T的实例 x有值的话,那么查询的sql就会用等于号,能不能做到我传个值,拼接的sql 是"like x%" 这种的??
2.还有,如果x='' 的话,能不能不让这个x出现在where语句中?目前 会拼接成 where x='' 

以上,还请解惑

**Comment by abel533** [comment]
这个方法就是用的 `=` 号方式。

想要特殊的可以用 `Example`.
