### ISSUE TITLE
Weekend增加JAVA8的属性查询

### ISSUE THREAD

**Issue by leohsu91** [abel533/Mapper#165]
public Example select(Fn<T, Object> ... fns) {
        Set<String> properties = new HashSet<>();
        for (Fn<T, Object> fn : fns) {
            String fieldName = Reflections.fnToFieldName(fn);
            if(fieldName != null) {
                properties.add(fieldName);
            }
        }
        return  super.selectProperties(properties.toArray(new String[properties.size()]));
    }

**Comment by leohsu91** [comment]
OrderBy一样
![image](https://user-images.githubusercontent.com/8965956/32714328-49056a6c-c888-11e7-96c8-8403fa486bac.png)
![image](https://user-images.githubusercontent.com/8965956/32714339-57323c1e-c888-11e7-9e1b-9d599c60c38a.png)

**Comment by abel533** [comment]
直接 fork https://github.com/abel533/weekend 这个项目 PR 吧，谢谢~
