### ISSUE TITLE
生成bean时，我想总是生成@Column，能否通过生成工具那个xml配置实现？

### ISSUE THREAD

**Issue by blacklong** [abel533/Mapper#18]
如这个：
    @Column(name = "url")
    private String url;
## 我想总是生成@Column(name="url")这个东西。

因为表结构里面，有的是userName，有的是user_name，两种命名方式。
通过style属性应该是固定一种吧？
我也不想生成bean之后再加那个什么NameStyle注解。
之前我是改的你的jar包，让它总生成@column注解的，觉得麻烦。

**Comment by abel533** [comment]
以后考虑加个参数控制。或者你加个参数给我PR

**Comment by blacklong** [comment]
哈哈，我不懂，你来弄吧~~谢谢

**Comment by abel533** [comment]
3.4.3
`MapperPlugin` 增加 `forceAnnotation` 参数，默认 `false`，设置为 `true` 后一定会生成`@Table`和`@Column`注解。
