### ISSUE TITLE
有没有可能（或有必要）提供一个类似全文搜索的通用mapper接口？

### ISSUE THREAD

**Issue by Ngone51** [abel533/Mapper#180]
例如：
查询字段countryname或countrycode（不考虑id）以‘C’开头的Country;
```
String text = "C";
List<Country> countries = mapper.selectFullText(text, Country.class);
```
对应的sql语句:
SELECT * FROM country WHERE countryname like ‘C%’ OR countrycode like ‘C%’

应用场景：过滤表格数据

**Comment by Ngone51** [comment]
@abel533

**Comment by abel533** [comment]
这个方法是自动把 String 类型的字段都 like 了？

这个方法很难通用，Example可能更容易控制。
