### ISSUE TITLE
insert接口能否返回主键或者持久化的对象？

### ISSUE THREAD

**Issue by hchaojie** [abel533/Mapper#182]
像jpa里面保存接口都是这样： T save(T t), 即把持久化对象返回，里面包含新增数据的主键。我们能支持么？

**Comment by abel533** [comment]
从一开始就支持。。

直接在 `t.getId()`，详细配置看文档中的主键策略部分。

**Comment by hchaojie** [comment]
ok，确实没想到对象保存后就有主键了，简单方便！谢谢
