### ISSUE TITLE
泛型注入怎么使用？

### ISSUE THREAD

**Issue by jwang0512** [abel533/Mapper#187]
因为db操作的表数量很大，但都比较简单，不打算给每个表都写一个dao，于是打算泛型注入service
在XxxService中：写 `@Autowired private Mapper<XxxItem> mapper;` 但一直注入不成功
配置为：
`
    <bean class="tk.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="com.xxx.dao" />
    </bean>
`
时，提示：No qualifying bean of type 'tk.mybatis.mapper.common.Mapper<com.xxx.XxxxItem>' available

配置为：
`
    <bean class="tk.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="basePackage" value="tk.mybatis.mapper.common,com.xxx.dao" />
    </bean>
`
时，提示
org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'insertMapper' for bean class [tk.mybatis.mapper.common.sqlserver.InsertMapper] conflicts with existing, non-compatible bean definition of same name and class [tk.mybatis.mapper.common.base.insert.InsertMapper]

请问注入泛型Mapper的正确姿势，baidu搜下来不是太旧就是都不靠谱

**Comment by IrvingZhao** [comment]
```
public abstract class BaseDao<T, PK extends Serializable, M extends CustomMapper<T>> implements IBaseDao<T, PK> {
    @Resource
    protected M mapper;
}
```
然后有不同的Dao类，Service中注入不同的Dao，Mapper也是对应的多个，IBaseDao里面是一些基础的操作方法

**Comment by abel533** [comment]
首先需要spring4+。

其次每个要注入的类型都必须有对应的 `XXMapper extends Mapper<XX>`

**Comment by jwang0512** [comment]
明白了，感谢！看来是我理解不对，我以为可以不用写空的Mapper了。
