### ISSUE TITLE
也许MapperHelper#fromMapperClass 里面应该用getMethod，而不是getDeclaredMethods 

### ISSUE THREAD

**Issue by jacarrichan** [abel533/Mapper#189]
https://github.com/abel533/Mapper/blob/34982116880d8b8d3f3e5684411d414e00fe529b/src/main/java/tk/mybatis/mapper/mapperhelper/MapperHelper.java#L100

**Comment by abel533** [comment]
这里只获取当前接口中定义的方法没有问题。

不同接口都是分别处理的。

**Comment by jacarrichan** [comment]
有时候我们会把一些常见的增删改方法放在一个Mapper里面，然后其它mapper继承它。

**Comment by abel533** [comment]
这里会递归往上找，会处理所有父接口，所以没问题。
