### ISSUE TITLE
可以与XML 同时使用吗？

### ISSUE THREAD

**Issue by oaksharks** [abel533/Mapper#19]
*.java 与*.xml 放在同一目录 貌似xml 并没有被扫描，xml的中的方法没有被生成代理类

**Comment by abel533** [comment]
你对maven不熟，放到src/main/resources下面，或者自学maven的resources配置。

**Comment by abel533** [comment]
你对maven不熟，放到src/main/resources下面，或者自学maven的resources配置。

**Comment by FuckDoctors** [comment]
@abel533 xml有了sqlmap的话，使用mapper会提示已经被注册了。xmlmapper中的方法与Mapper通用类的方法一致的话可不可以以xmlmapper中的为优先？比如先读入xml中的内容，如果xml中已经配置了sql的话，就不使用Mapper通用类里的方法了？xml中没有的话再使用Mapper通用类里的sql。
刚接触Spring&Mybatis，不知道你能不能看懂。。。

**Comment by abel533** [comment]
不能优先，不能重名。

**Comment by 5452** [comment]
mapper不可以自定义方法吗？比如生成文件后，在xml配置id为getByXXX的sql语句，在mapper中配置这个方法，总是报org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)。

**Comment by abel533** [comment]
@5452 你扫描XML了吗？命名空间和接口是否一致？

**Comment by 5452** [comment]
给您回复邮件了，您帮忙看下，还需要什么其他的配置和文件，您直接回邮件就可以了
