### ISSUE TITLE
驼峰命名有问题

### ISSUE THREAD

**Issue by geemu** [abel533/Mapper#193]
数据库写updateTime生成的实体是updateTime,但是SQL却是id,account,password,email,data_flag,is_delete,create_time,update_time,create_id,update_id  FROM user_info_secondary  WHERE       (  account = ?                                                and password = ? )

SQL带了下划线

**Comment by abel533** [comment]
默认是下划线和驼峰互转，可以配置全局的 nameStyle 或者局部类用注解，也可以给字段加 `@Column` 注解。

**Comment by Diluka** [comment]
使用注解没有生效，还是应用的全局配置 @abel533
