### ISSUE TITLE
建议在sqlmap里增加Base_Column_List

### ISSUE THREAD

**Issue by leongongye** [abel533/Mapper#195]
mybatis默认的generator默认会生成Base_Column_List，这样在需要手动编写扩展sqlmap（一些复杂查询）时，可以直接引用。
```
<sql id="Base_Column_List" >
    id, username, is_deleted
</sql>
```

**Comment by abel533** [comment]
默认的加不了，但是能通过新版本中的代码生成器生成这个。

**Comment by drtrang** [comment]
@leongongye 我之前写过一个插件可以满足你的需求，地址在这：[MapperSqlMapConfigPlugin.java](https://github.com/drtrang/mybatis-generator-extension/blob/master/src/main/java/com/github/trang/mybatis/generator/plugins/MapperSqlMapConfigPlugin.java).

该类属于 [mybatis-generator-extension](https://github.com/drtrang/mybatis-generator-extension) 项目，使用时需要把 Jar 包加入 MBG 的运行时环境中，如果你用的是 `mybatis-generator-maven-plugin` 方式，只需在依赖中添加该项目的 Maven 坐标：

![image](https://user-images.githubusercontent.com/13851701/34867369-d19ba574-f7ba-11e7-8b5e-dc7181b796b7.png)

然后在 MBG 的配置文件中声明 MapperSqlMapConfigPlugin 即可：

![image](https://user-images.githubusercontent.com/13851701/34867399-f1339996-f7ba-11e7-85a0-6457253853e9.png)

如有不明白的地方，请查看示例：[generatorConfig-example.xml](https://github.com/drtrang/mybatis-generator-extension/blob/master/src/main/resources/examples/generatorConfig-example.xml)

**Comment by leongongye** [comment]
@drtrang 不错，赞！

**Comment by xiongzhao1217** [comment]
@drtrang 感谢，在你的基础上实现了和tk的集成
1. 添加maven依赖
`<dependency>
            <groupId>com.github.drtrang</groupId>
            <artifactId>mybatis-generator-extension</artifactId>
            <version>0.0.4</version>
            <scope>test</scope>
        </dependency>`
2. 新建MyMyMapperPlugin继承tk.mybatis.mapper.generator.MapperPlugin
`/**
 * 自定义mapper xml生成内容
 * @author xz
 */
public class MyMapperPlugin extends MapperPlugin {

    public boolean sqlMapDocumentGenerated(Document document, IntrospectedTable introspectedTable) {
        this.generateSqlBaseColumns(document, introspectedTable);
        return true;
    }

    /**
     * mapper.xml生成Base_Column_List
     * @param document
     * @param introspectedTable
     */
    private void generateSqlBaseColumns(Document document, IntrospectedTable introspectedTable) {
        XmlElement rootElement = document.getRootElement();
        XmlElement sqlElement = new XmlElement("sql");
        Attribute attr = new Attribute("id", "Base_Column_List");
        sqlElement.addAttribute(attr);
        TextElement comment = new TextElement("");
        StringBuilder columnsBuilder = new StringBuilder();
        List columnList = introspectedTable.getAllColumns();
        Iterator columns = columnList.iterator();

        while(columns.hasNext()) {
            IntrospectedColumn content = (IntrospectedColumn)columns.next();
            columnsBuilder.append(introspectedTable.getAliasedFullyQualifiedTableNameAtRuntime() + '.' + content.getActualColumnName()).append(", ");
        }

        String columns1 = columnsBuilder.substring(0, columnsBuilder.length() - 2);
        TextElement content1 = new TextElement(columns1);
        sqlElement.addElement(comment);
        sqlElement.addElement(content1);
        rootElement.addElement(new TextElement(""));
        rootElement.addElement(sqlElement);
        rootElement.addElement(new TextElement(""));
    }
}`
3. 在 MBG 的配置文件中声明 MyMapperPlugin 即可
