### ISSUE TITLE
typehandler问题

### ISSUE THREAD

**Issue by abel533** [abel533/Mapper#198]
各位大佬有没有遇到过引入TKmybatis后客户化后的handler（继承BaseTypeHandler）就不能用了这样的问题？

但是发现只有自定义的SQL才会执行这个handler

数据库中的字段有的是存的json字符串，想在读取出来后可以自动封装成VO数组
![1](https://user-images.githubusercontent.com/1787798/34752108-5312186c-f5eb-11e7-93e3-1535de3bab54.png)

![2](https://user-images.githubusercontent.com/1787798/34752112-5553d246-f5eb-11e7-83d5-3b914895ff44.png)

![3](https://user-images.githubusercontent.com/1787798/34752113-561f651e-f5eb-11e7-855b-bf8f2db573cd.png)

**Comment by CarlJia** [comment]
额，我刚加 insertList UUID方法，发现你新版本已经有了，我刚加 UniversalEnumHandler 发现你也在弄。。。
没发现问题，我用的
compile group: 'tk.mybatis', name: 'mapper-spring-boot-starter', version: '1.1.4'
insert，selectAll，select 都可以正常解析枚举，json 数组的没试过

**Comment by CarlJia** [comment]
貌似父子类，复杂对象，会报找不到 type handler
比如
```
class Order{
private String id;
}
```

```
class OrderDetail {
private Order main;
}
```

**Comment by neXtack** [comment]
我在3.5.0的版本中遇到了这个问题
```xml
<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper</artifactId>
    <version>3.5.0</version>
</dependency>
```

我写了一个通用的枚举的处理器，继承自`BaseTypeHandler`，然后在`insert`，`insertList`就不生效了，更多没有尝试，然后就回滚了版本

**Comment by abel533** [comment]
@neXtack 先用上个版本吧，最近会处理3.5.0出现的问题。

**Comment by neXtack** [comment]
@abel533 嗯 已经在用上个版本了 :)

**Comment by abel533** [comment]
4.0 增加了对 typehandler 的完整测试，目前没有问题。

**Comment by springCkWyy** [comment]
你好， 我用的tk.mybatis.mapper 3.4.0版本，为了进行enum转换， 自定义了TypeHandler，继承了BaseTypeHandler。 发现查询的时候没有执行getNullableResult、getNullableResult等方法，报错如下：
"nested exception is org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column 'status' from result set.  Cause: java.lang.IllegalArgumentException: No enum constant com.enums.StatusEnum.2，  请问基于此版本怎么解决呢？

**Comment by abel533** [comment]
已解决，可以看这里：https://github.com/abel533/Mapper/wiki/7.2.typehandler

**Comment by yaowang99** [comment]
4.0版本依然存在这个问题。加入自定义的handler对string类型做null转empty处理，未生效

**Comment by abel533** [comment]
@yaowang99 这个和 mapper 无关。

**Comment by ChenYi1125** [comment]
> 已解决，可以看这里：https://github.com/abel533/Mapper/wiki/7.2.typehandler

大佬，我们需要转换字符集，自定义的StringTypeHandler只有手写sql才有用，用Mapper自带的方法或者Example就只走默认的StringTypeHandler，有解决方法吗？
