### ISSUE TITLE
请在接口中增加批量添加的功能

### ISSUE THREAD

**Issue by jiang539** [abel533/Mapper#2]
请在接口中增加批量添加的功能
谢谢

**Comment by abel533** [comment]
由于批量添加和数据库支持有关，这个没法做到通用。

如果你能想到更多Mysql中的通用方法，可以在此列出来，如果足够多，我就会专门给Mysql提供一个MysqlMapper<T>

**Comment by zhangygit** [comment]
接口 中 参数为list 怎么处理 
比如list<T> recods 在 MappedStatement ms 这怎么获取 list的 size 值
既然对 <if> 标签做了处理 那也增加个对<<foreach>标签的处理吧

**Comment by tonnyyi** [comment]
希望作者能提供一个批量操作的例子(针对Mysql数据库), 放在项目文档或博客里, 多谢

**Comment by abel533** [comment]
@tonnyyi 项目测试代码中提供了一个hsqldb的批量插入例子，和mysql基本上是一样的。

在将来的3.0.0版本中会提供更多单一的简单接口。

**Comment by abel533** [comment]
很早之前的3.0版本增加了针对MySql的批量插入，支持ID回写。
