### ISSUE TITLE
可否在@Column上支持 updatable

### ISSUE THREAD

**Issue by mataoxf** [abel533/Mapper#20]
建议：
在@Column上支持 updatable，为false时，不参与update。

缘由：
由于数据库表里有update_date字段，由MYSQL自动生成更新时间。所以要限制业务层的改写。

现象：
在update数据时，SPRING MVC 通过ModelAttribute进行 MERGE，然后就永远是第一次更新的时间了。

**Comment by abel533** [comment]
从3.3.1 - 2015-12-09  @Column注解增加对insertable和updatable属性的支持。

**Comment by mataoxf** [comment]
经测试，子类属性上有效，在父类属性上注解无效。

**Comment by abel533** [comment]
测试了，没有问题。
