### ISSUE TITLE
请问如何同时使用mapper和传统的xml配置？

### ISSUE THREAD

**Issue by myfreeway** [abel533/Mapper#202]
请问如何同时使用mapper和传统的xml配置？因为我需要方便的写复杂的sql。

**Comment by abel533** [comment]
就跟你没用通用Mapper一样，直接混合用就行。。自己写的方法或XML中的id不要和已经存在的方法重名即可。

**Comment by lalapalooza** [comment]
使用BaseService<T> 后 maper文件中增加自己的方法会报错： 绑定出错 ？ @abel533

**Comment by abel533** [comment]
@lalapalooza 什么错？

**Comment by chinleo** [comment]
@abel533 你的意思是, 使用tk的MapperScan可以兼容mybatis的xml?

**Comment by abel533** [comment]
@chinleo 可以
