### ISSUE TITLE
很期待加入weekend类似Builder的链式写法哦

### ISSUE THREAD

**Issue by chinaerserver** [abel533/Mapper#203]
Example example = new Example.Builder(User.class).where(Sqls.custom().andIn("age", Arrays.asList(1, 2, 3)))
				.build();
		List<User> users = userMapper.selectByExample(example);
==================><==================
Weekend<User> weekend = Weekend.of(User.class);
		weekend.weekendCriteria().andIn(User::getAge, Arrays.asList(1, 2, 3));
		List<User> users userMapper.selectByExample(weekend);

**Comment by abel533** [comment]
下一步是计划集成官方的动态sql，example可能不会变了。

如果你能PR，咱们可以一起看看。

**Comment by chinaerserver** [comment]
已经提交pr 大部分的方法只是重载Sqls工具类里面的方法  感觉使用方法引用这一特性能够有效避免手工输入对象参数出错的问题

**Comment by jwang0512** [comment]
weekend这个名字很让人费解，建议改掉。跟原作者沟通下我想不是什么问题。
另外weekend有bug，因为在source里面没找到对应的代码，我没法直接PR，具体就是：
tk.mybatis.mapper.weekend.reflection.Reflections.fnToFieldName(Fn fn)方法：
String fieldName = Introspector.decapitalize(getter.replace("get", ""));
应改为
String fieldName = Introspector.decapitalize(getter.substring(3));

否则当你的字段名中带有get字符是就会出错。例如你的字段名是target时

**Comment by abel533** [comment]
@jwang0512 这个bug已经处理，下个版本就没了。

这个名字原作者是同意改的，但是因为没人能提供更合适的名字，因此就保留下来了。
