### ISSUE TITLE
乐观锁相关问题请教

### ISSUE THREAD

**Issue by yangdq1** [abel533/Mapper#204]
您好，更新了最新版本，新增加了update乐观锁功能，很棒，还有些小疑问：
1.如果我需要版本冲突直接报错，在哪里拦截处理比较好（不想写在业务代码里，想统一处理）；
2.delete也有乐观锁要求；

谢谢

**Comment by abel533** [comment]
在通用mapper的这部分逻辑中，没法抛出异常。所以更合理的办法是在service层封装一下，对返回数进行校验。

**Comment by abel533** [comment]
如果是 java8，增加个默认方法进行判断也可以。

**Comment by abel533** [comment]
delete 这个可以有。

**Comment by yangdq1** [comment]
好的 谢谢～
