### ISSUE TITLE
Example实体类找不到表名，打包部署后报错。

### ISSUE THREAD

**Issue by TiantianLee** [abel533/Mapper#208]
工程并未使用devtools，在eclipse启动未报错。打包部署时，采用内置打包法，启动未报错。采用外部打包法时报错。打包插件配置如下
```xml
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>com.abc.Application</mainClass>
							<addClasspath>true</addClasspath>
							<classpathPrefix>lib/</classpathPrefix>
						</manifest>
						<manifestEntries>
							<Class-Path>. conf/</Class-Path>
						</manifestEntries>
					</archive>
 					<excludes>
						<exclude>*.properties</exclude>
						<exclude>*.xml</exclude>
						<exclude>*.yml</exclude>
					</excludes> 
				</configuration>
			</plugin>
```

**Comment by TiantianLee** [comment]
[http://blog.51cto.com/alex233/1885759](url)
就像这个文章第二种方法的打包方式。 @abel533

**Comment by abel533** [comment]
如果是spring boot，就用 boot 的插件。。

**Comment by TiantianLee** [comment]
maven-jar-plugin加上maven-assembly-plugin，用来把配置文件和lib放在fat-jar外面，方便部署不同环境。暂时把<classpathPrefix>lib/</classpathPrefix>改成了<classpathPrefix>BOOT-INF/lib</classpathPrefix>是可以的，这样lib还在jar内，配置文件在conf目录下了。情况还可以接受。

**Comment by guan25** [comment]
> maven-jar-plugin加上maven-assembly-plugin，用来把配置文件和lib放在fat-jar外面，方便部署不同环境。暂时把lib/改成了BOOT-INF/lib是可以的，这样lib还在jar内，配置文件在conf目录下了。情况还可以接受。

请问，这个问题解决了没，我也遇到，困扰了好久.... 不解决，有规避方案么
