### ISSUE TITLE
3.5.0中，对基础数据类型的支持

### ISSUE THREAD

**Issue by xiezhaofeng** [abel533/Mapper#212]
```
 @Column(name = "test_id")
    private int testId;
```
当属性使用int定义的时候，在使用3.5.0的时候，无法设置testId的值进行插入操作，包括insert，insertSelective。我将版本切回3.4.X，又可以支持。不知道这是个异常还是设计就是这样的。

**Comment by abel533** [comment]
就是这么设计的。。不要在实体类用基本类型。

**Comment by jwang0512** [comment]
感觉这样的设计对开发不友好，编译期间发现不了问题，运行时发现数据不对才会回去查问题所在。建议支持基本类型，虽然一般来说不会使用基础类型。

**Comment by abel533** [comment]
4.0 中增加：
### 3.10  usePrimitiveType

为了方便部分还在使用基本类型的实体，增加了该属性，只有配置该属性，并且设置为 `true` 才会生效，启用后，会扫描 8 种基本类型。

配置方式如下：

```
usePrimitiveType=true
```
