### ISSUE TITLE
关于updateByPrimaryKeySelective的疑惑

### ISSUE THREAD

**Issue by Yuxiao97** [abel533/Mapper#214]
今天在使用该方法时,发现其执行的sql为: UPDATE table_name SET id = ?,name = ? WHERE id = ? AND name = ? AND...... 类似这样的更新操作,原本以为会输出类似下面的sql: update table_name set name = ? where id =  ?

希望作者改进 或提供额外的方法声明 比如 updateSelectiveByPrimaryKey  谢谢!

**Comment by abel533** [comment]
你没指定主键，这种情况下所有字段是联合主键。

**Comment by Yuxiao97** [comment]
@abel533 哈哈哈 一语惊醒梦中人 谢谢 鄙人太大意了
