### ISSUE TITLE
springboot配置多数据源后如何使用通用mapper

### ISSUE THREAD

**Issue by wangzhihaolighter** [abel533/Mapper#215]
springboot项目，配置了多数据源，两个mybatis的config配置，mapper和xml也分别放在mapper.primary和mapper.second下。mybatis注解扫描对应不同包下的mapper和xml，而通用mapper配置扫描的是mapper包。结果，通用mapper只使用主库的配置。纯mybatis则可以正常分别访问不同的库，请问通用mapper这种情况下怎么配置实现这种效果呢？麻烦作者了

**Comment by abel533** [comment]
通用mapper为什么需要配置扫描mapper包？

**Comment by wangzhihaolighter** [comment]
spring boot注册通用mapper不设置basepage报错。。。提示required

**Comment by abel533** [comment]
用的 `@MapperScan` 注解？

**Comment by wangzhihaolighter** [comment]
是的，多数据源配置类上用的`@MapperScan`，而通用mapper注册一个多个bean效果一样，只用primary的数据库配置

**Comment by wangzhihaolighter** [comment]
抱歉，注册一个通用mapper扫描mapper，可以做到多数据源的操作，是我配置DataSource属性的错误

**Comment by wangzhihaolighter** [comment]
谢谢作者答复，麻烦了
