### ISSUE TITLE
3.5.2中，很多数据类型获取不到值

### ISSUE THREAD

**Issue by cocosjiang** [abel533/Mapper#216]
如Timestamp 在3.4.x读数据库是可以拿到值，在3.5.x拿到的都是空

**Comment by abel533** [comment]
4.0 版本增加了针对性的测试，目前可以从 4.0 分支查看。

tk.mybatis.mapper.issues._216_datetime.DateTimeTest;

**Comment by abel533** [comment]
3.x 的最新版本是因为 simpleType 中没有包含 java.sql.Timestamp 导致的。
