### ISSUE TITLE
3.3.8之后, 列名的大小写出现问题. 

### ISSUE THREAD

**Issue by imzhuli** [abel533/Mapper#22]
3.3.7是正确如下:
Preparing: INSERT INTO app_user ( app_user_id,app_user_name,app_user_gender,app_user_image_url,create_time ) VALUES( ?,?,?,?,? ) 
而到了3.8:
Preparing: INSERT INTO app_user ( APP_uSER_iD,APP_uSER_nAME,APP_uSER_gENDER,APP_uSER_iMAGE_uRL,CREATE_tIME ) VALUES( ?,?,?,?,? )

**Comment by abel533** [comment]
好像合并过一个解决这个问题的PR，我在看看。

**Comment by sgq0085** [comment]
同问！ 能不能驼峰转下划线+转小写一起配置上？

**Comment by abel533** [comment]
这个可以考虑，有时间的时候，改成数组，可以组合。

2016-07-15 16:31 GMT+08:00 gqshao <notifications@github.com>:

**Comment by abel533** [comment]
`@NameStyle`注解支持多种方式。
