### ISSUE TITLE
通用mapper使用BaseTypeHandler

### ISSUE THREAD

**Issue by dengqz** [abel533/Mapper#221]
使用通用接口如何配置继承了BaseTypeHandler的类型转换器？

**Comment by dengqz** [comment]
能给个例子学习一下吗？是注解吗？怎么配置

**Comment by abel533** [comment]
```java
/**
 * 这个例子中，在 XML 配置了缓存，这里使用注解引用 XML 中的缓存配置
 *
 * namespace 有两种配置方法，参考下面两行注解
 */
@CacheNamespaceRef(CountryCacheRefMapper.class)
//@CacheNamespaceRef(name = "tk.mybatis.mapper.cache.CountryCacheRefMapper")
public interface CountryCacheRefMapper extends Mapper<Country> {

    /**
     * 定义在 XML 中的方法
     *
     * @param id
     * @return
     */
    Country selectById(Integer id);
}

```

```xml
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="tk.mybatis.mapper.cache.CountryCacheRefMapper">
    <!--这个例子是在 XML 中定义缓存，在接口中引用 XML 中配置的缓存-->
    <cache/>
    <select id="selectById" resultType="tk.mybatis.mapper.base.Country">
        select * from country where id = #{id}
    </select>
</mapper>

```

**Comment by abel533** [comment]
只用接口的时候：

```java
/**
 * 只有接口时，加下面的注解即可
 */
@CacheNamespace
public interface CountryCacheMapper extends Mapper<Country> {

}
```

**Comment by springCkWyy** [comment]
您好 我在bean 做了如下配置：    
@ColumnType(
            column = "status",
            jdbcType = JdbcType.INTEGER,
            typeHandler = MyEnumTypeHandler.class)
    private StatusEnum status;

数据库存入的是int， 要求请求体和返回都是string,  现在返回可以根据int 返回对应的string。 但是插入的时候，string 无法自动转换为int。 其setNonNullParameter 不会执行， 请问还需要其他配置吗

**Comment by dengqz** [comment]
import com.ceying.chx.common.enums.BaseEnum;
import org.apache.ibatis.type.BaseTypeHandler;
import org.apache.ibatis.type.JdbcType;

import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class UniversalEnumHandler<E extends BaseEnum> extends BaseTypeHandler<E> {

    private Class<E> type;
    private E [] enums;

    /**
     * 设置配置文件设置的转换类以及枚举类内容，供其他方法更便捷高效的实现
     * @param type 配置文件中设置的转换类
     */
    public UniversalEnumHandler(Class<E> type) {
        if (type == null){
            throw new IllegalArgumentException("Type argument cannot be null");
        }
        this.type = type;
        this.enums = type.getEnumConstants();
        if (this.enums == null) {
            throw new IllegalArgumentException(type.getSimpleName()
                    + " does not represent an enum type.");
        }
    }

    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, E parameter,
                                    JdbcType jdbcType) throws SQLException {
        //BaseTypeHandler已经帮我们做了parameter的null判断
        ps.setObject(i,(String)parameter.getValue(), jdbcType.TYPE_CODE);
    }

    @Override
    public E getNullableResult(ResultSet rs, String columnName)
            throws SQLException {
        // 根据数据库存储类型决定获取类型，本例子中数据库中存放String类型
        String i = rs.getString(columnName);
        if (rs.wasNull()) {
            return null;
        } else {
            // 根据数据库中的value值，定位PersonType子类
            return locateEnumStatus(i);
        }
    }

    @Override
    public E getNullableResult(ResultSet rs, int columnIndex)
            throws SQLException {
        // 根据数据库存储类型决定获取类型，本例子中数据库中存放String类型
        String i = rs.getString(columnIndex);
        if (rs.wasNull()) {
            return null;
        } else {
            // 根据数据库中的value值，定位PersonType子类
            return locateEnumStatus(i);
        }
    }

    @Override
    public E getNullableResult(CallableStatement cs, int columnIndex)
            throws SQLException {
        // 根据数据库存储类型决定获取类型，本例子中数据库中存放String类型
        String i = cs.getString(columnIndex);
        if (cs.wasNull()) {
            return null;
        } else {
            // 根据数据库中的value值，定位PersonType子类
            return locateEnumStatus(i);
        }
    }

    /**
     * 枚举类型转换，由于构造函数获取了枚举的子类enums，让遍历更加高效快捷
     * @param value 数据库中存储的自定义value属性
     * @return value对应的枚举类
     */
    private E locateEnumStatus(String value) {
        for(E e : enums) {
            if(e.getValue().equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("未知的枚举类型：" + value + ",请核对" + type.getSimpleName());
    }
}

**Comment by dengqz** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE configuration SYSTEM "http://mybatis.org/dtd/mybatis-3-config.dtd" PUBLIC "-//mybatis.org//DTD Config 3.0//EN">

-<configuration>





-<typeAliases>

<typeAlias alias="Integer" type="java.lang.Integer"/>

<typeAlias alias="Long" type="java.lang.Long"/>

<typeAlias alias="HashMap" type="java.util.HashMap"/>

<typeAlias alias="LinkedHashMap" type="java.util.LinkedHashMap"/>

<typeAlias alias="ArrayList" type="java.util.ArrayList"/>

<typeAlias alias="LinkedList" type="java.util.LinkedList"/>




</typeAliases>


-<typeHandlers>

<typeHandler jdbcType="VARCHAR" javaType="com.ceying.chx.common.enums.EnumPriorityType" handler="com.ceying.chx.common.util.typehandler.UniversalEnumHandler"/>

</typeHandlers>

</configuration>

**Comment by dengqz** [comment]
<configuration>
    
        <typeAliases>
            <typeAlias type="java.lang.Integer" alias="Integer"  />
            <typeAlias type="java.lang.Long" alias="Long" />
            <typeAlias type="java.util.HashMap" alias="HashMap" />
            <typeAlias type="java.util.LinkedHashMap" alias="LinkedHashMap" />
            <typeAlias type="java.util.ArrayList" alias="ArrayList" />
            <typeAlias type="java.util.LinkedList" alias="LinkedList"  />
        </typeAliases>
    <typeHandlers>
        <typeHandler handler="com........typehandler.UniversalEnumHandler"
                     javaType="com..........enums.EnumPriorityType" jdbcType="VARCHAR"/>
    </typeHandlers>
</configuration>

**Comment by springCkWyy** [comment]
我目前是这个处理的  但是插入的时候 类型无法转换 不走setNonNullParameter方法，我插入的时候按照collector.setStatus(StatusEnum.NEWED);  报错：  Incorrect integer value: 'NEWED' for column 'status'  ， 字符串还是无法转换为Int

**Comment by dengqz** [comment]
extends BaseTypeHandler？？？？？

**Comment by springCkWyy** [comment]
是的。   
Typehander如下：
public class MyEnumTypeHandler extends BaseTypeHandler<StatusEnum> {  
      
    private Class<StatusEnum> type;  
       
    private final StatusEnum[] enums;  
   
    /** 
     * 设置配置文件设置的转换类以及枚举类内容，供其他方法更便捷高效的实现 
     * @param type 配置文件中设置的转换类 
     */  
    public MyEnumTypeHandler(Class<StatusEnum> type) {  
        if (type == null)  
            throw new IllegalArgumentException("Type argument cannot be null");  
        this.type = type;  
        this.enums = type.getEnumConstants();  
        if (this.enums == null)  
            throw new IllegalArgumentException(type.getSimpleName()  
                    + " does not represent an enum type.");  
    }  
  
    @Override
    public void setNonNullParameter(PreparedStatement ps, int i,  
            StatusEnum parameter, JdbcType jdbcType) throws SQLException {  
        // baseTypeHandler已经帮我们做了parameter的null判断  
        if(jdbcType == null) {  
            ps.setString(i, parameter.name());  
        } else {  
            ps.setObject(i, parameter.name(), jdbcType.TYPE_CODE);  
        }            
    }  
  
        
      
    public StatusEnum getNullableResult(ResultSet rs, String columnName)  
            throws SQLException {  
        // 根据数据库存储类型决定获取类型，本例子中数据库中存放INT类型  
        int i = rs.getInt(columnName);  
           
        if (rs.wasNull()) {  
            return null;  
        } else {  
            // 根据数据库中的code值，定位EnumStatus子类  
            return locateEnumStatus(i);  
        }  
    }  
  
      
    public StatusEnum getNullableResult(ResultSet rs, int columnIndex)  
            throws SQLException {  
        // 根据数据库存储类型决定获取类型，本例子中数据库中存放INT类型  
        int i = rs.getInt(columnIndex);  
        if (rs.wasNull()) {  
            return null;  
        } else {  
            // 根据数据库中的code值，定位EnumStatus子类  
            return locateEnumStatus(i);  
        }  
    }  
  
      
    public StatusEnum getNullableResult(CallableStatement cs, int columnIndex)  
            throws SQLException {  
        // 根据数据库存储类型决定获取类型，本例子中数据库中存放INT类型  
        int i = cs.getInt(columnIndex);  
        if (cs.wasNull()) {  
            return null;  
        } else {  
            // 根据数据库中的code值，定位EnumStatus子类  
            return locateEnumStatus(i);  
        }  
    }  
      
    /** 
     * 枚举类型转换，由于构造函数获取了枚举的子类enums，让遍历更加高效快捷 
     * @param code 数据库中存储的自定义code属性 
     * @return code对应的枚举类 
     */  
    private StatusEnum locateEnumStatus(int code) {  
        for(StatusEnum status : enums) {  
            if(status.getStatus()==(Integer.valueOf(code))) {  
                return status;  
            }  
        }  
        throw new IllegalArgumentException("未知的枚举类型：" + code + ",请核对" + type.getSimpleName());  
    }  


statusEnum:

    DELETED(-1), NEWED(0), INGESTED(1), STARTED(2), PASUED(3), STOPPED(4);

    private int status;
    
    StatusEnum(int status){
        this.status = status;
    }
    
    public int getStatus() {
        return status;
    }
------------------------------------------------
我参考了其他的，是这么做的。
<insert id="insertUser" parameterType="org.sang.bean.User">
        INSERT INTO user4(username,password,regTime) VALUES (#{username},#{password},#{regTime,javaType=Date,jdbcType=VARCHAR,typeHandler=org.sang.db.MyDateTypeHandler})
    </insert>

但是通用mapper 是自己实现了插入， 我们自己无法定义其typehandler，  需要哪里配置吗？ 现在Typehander get方法可以执行， set debug 进不去，  不知道需要怎么设置下

**Comment by dengqz** [comment]
int  integer

**Comment by dengqz** [comment]
https://www.cnblogs.com/jerrylz/p/5814460.html

**Comment by springCkWyy** [comment]
@dengqz  你使用typehander 成功过吗  插入的时候是成功

**Comment by springCkWyy** [comment]
各位老大，我使用是自定义typehandler，set方法调用不到，除非map.xml自定义insert语句，老大让我手动改写所有的Insert  update了， 感觉这样就浪费了通用mapper，  恳求各位了

**Comment by abel533** [comment]
@springCkWyy 看文档：https://github.com/abel533/Mapper/wiki/7.2.typehandler

已经很详细了。
