### ISSUE TITLE
怎么获取插入后的主键

### ISSUE THREAD

**Issue by sandyfog** [abel533/Mapper#226]
```java
userMapper.insert(user);
System.out.println(user.getId());
```
输出是null，id设置成自增的，改怎么获取插入后的id呢？

**Comment by abel533** [comment]
文档中的主键策略有介绍。

**Comment by shx1545** [comment]
![qq 20180225154723](https://user-images.githubusercontent.com/29303050/36639240-31909156-1a43-11e8-8b69-d9f7de715faf.png)
使用这种注解，使用insert会报错。
报错信息如下：
```
Error invoking SqlProvider method (tk.mybatis.mapper.provider.SpecialProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider
```

**Comment by cavonchen** [comment]
同样问题，mysql环境，无法获取自动递增的id

**Comment by shx1545** [comment]
1. 类字段和表字段名称一致id，且自增。
2. 配置了mappers根据文档，且SuperMapper不被扫到。
![image](https://user-images.githubusercontent.com/29303050/36656554-e76dd374-1b03-11e8-9078-1e80bfc3eec1.png)
3. 换了几个mysql自增@GeneratedValue注解的配置报的都是一个错。
4. 发现只要添加上面的注解，insert和insertSelective也报同一个错。
很郁闷，不知道什么问题。

**Comment by abel533** [comment]
`SuperMapper` 发一下这个接口的定义。。

你也可以升级到 4.0.0 ，然后给你这个接口加个 `@RegisterMapper` 注解，就不需要配置 mappers 了。
