### ISSUE TITLE
selectByExampleAndRowBounds分页是伪分页吗？

### ISSUE THREAD

**Issue by tsaimn** [abel533/Mapper#228]
我打开MyBatis的SQL日志发现控制台打出来的分页SQL语句是没有加"limit"的，然后去查MySQL执行日志也是没有limit

**Comment by abel533** [comment]
是内存分页，这个方法本意是和分页插件结合用的。

想要物理分页需要考虑不同数据库，会让这里变得复杂。

分页插件：https://github.com/pagehelper/Mybatis-PageHelper
