### ISSUE TITLE
以下两种写法为什么不是等价的？在Example对象中的notNull属性没有起作用么？

### ISSUE THREAD

**Issue by tsaimn** [abel533/Mapper#229]
表单中的查询条件都不是必选项，当其中有属性传值为null时，写法1就会SQL语法错误，原因是只拼接了条件没有值（控制台打印SQL: SELECT id,operation_code,creater,type,os,browser,ip,mac,execute_time,description,request_param,create_time FROM sy_log WHERE ( create_time <= and create_time >= and operation_code = and creater = ) order by id Desc）

源码中的注释“@param notNull     - true时，如果值为空，就会抛出异常，false时，如果为空就不使用该字段的条件”
******************************************写法1*********************************************************
       Example example1 = Example.builder(Log.class).where(Sqls.custom()
                .andLessThanOrEqualTo("createTime", endTime)
                .andGreaterThanOrEqualTo("createTime", startTime)
                .andEqualTo("operationCode", operationCode)
                .andEqualTo("creater", creater)
        ).orderByDesc("id").build();

******************************************写法2*********************************************************
        Example example = new Example(Log.class);
        Example.Criteria criteria = example.createCriteria();
        if (StringUtils.isNotEmpty(endTime)) {
            criteria.andLessThanOrEqualTo("createTime", endTime);
        }
        if (StringUtils.isNotEmpty(startTime)) {
            criteria.andGreaterThanOrEqualTo("createTime", startTime);
        }
        if (StringUtils.isNotEmpty(operationCode)) {
            criteria.andEqualTo("createTime", operationCode);
        }
        if (StringUtils.isNotEmpty(creater)) {
            criteria.andEqualTo("createTime", creater);
        }
        example.orderBy("id").desc();
使用的版本为3.5.2

**Comment by abel533** [comment]
可能null时应该用第二种。
