### ISSUE TITLE
通用mappper 继承BaseTypeHandler，set的时候可以自定义jdbcType吗

### ISSUE THREAD

**Issue by kadisyy** [abel533/Mapper#230]
如下：
 public void setNonNullParameter(PreparedStatement ps, int i,  
            StatusEnum parameter, JdbcType jdbcType) throws SQLException {  
        // baseTypeHandler已经帮我们做了parameter的null判断  
        if(jdbcType == null) {  
            ps.setInt(i, parameter.getStatus());  
        } else {  
            ps.setObject(i, parameter.getStatus(), jdbcType.TYPE_CODE);  
        }            
    }  

请问可以在哪里定义jdbcType吗 发现都是null

**Comment by abel533** [comment]
`@ColumnType(jdbcType=xxx)`
