### ISSUE TITLE
引入了mapper-mapper-spring-boot-starter之后发现JPA不能使用了

### ISSUE THREAD

**Issue by HusenHuang** [abel533/Mapper#231]
Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: javax.persistence.spi.PersistenceUnitInfo.getValidationMode()Ljavax/persistence/ValidationMode;

**Comment by abel533** [comment]
排除 Mapper 中的 jpa 依赖即可
