### ISSUE TITLE
updateByPrimaryKeySelective这个方法会把所有参数都当作条件传入sql

### ISSUE THREAD

**Issue by qq253498229** [abel533/Mapper#232]
updateByPrimaryKeySelective这个方法会把所有参数都当作条件传入sql
最后生成的sql是这样的
![image](https://user-images.githubusercontent.com/31200516/36976355-3da145be-20b8-11e8-9a5d-657eb73b5523.png)
而且where后面的这些参数都是更新之后的参数，导致根本查不到，也就更新不了。
请问我是哪里配置错误了吗

**Comment by abel533** [comment]
没有 `@Id` 导致的，你应该也解决了。
