### ISSUE TITLE
4.0.0-beta3 测试版反馈

### ISSUE THREAD

**Issue by abel533** [abel533/Mapper#233]
通用 Mapper 4.0.0-beta2 测试版已经发布了，希望大家可以积极参与测试，让正式版更快发布。

同时对应的 Spring Boot Starter 已经更新到 2.0.0-beta2 版本。

**Starter 已知问题**：由于官方 2.0 版本和之前的测试版存在不同，因此使用 `Binder` 绑定配置时会返回一个 null 而导致出现错误，临时解决办法就是随便在项目中配置一个参数，例如下面的配置：
```
mapper.use-java-type=true
```
**特别注意**：官方 2.0 已经不支持随意的 Relax 绑定，升级时注意看官方说明。
>https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0

### 基本依赖

```xml
<dependency>
	<groupId>tk.mybatis</groupId>
	<artifactId>mapper</artifactId>
	<version>4.0.0-beta3</version>
</dependency>
```

### 使用 Spring Boot 时，引入下面的依赖即可

```xml
<dependency>
	<groupId>tk.mybatis</groupId>
	<artifactId>mapper-spring-boot-starter</artifactId>
	<version>2.0.0-beta3</version>
</dependency>
```

如果其他仓库还没有从 Maven 同步过来，可以先添加下面的仓库：
```xml
<repositories>
    <repository>
        <id>oss</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
    </repository>
</repositories>
```

## 文档

大家是测试时可以通过 wiki 查看最新的配置、参数介绍等文档：

https://github.com/abel533/Mapper/wiki

其中部分不是很关键的文档还在继续完善中。

## 欢迎参与测试

**凡是真正参与该版本测试的朋友，都可以由群主邀请加入专门的微信群，大家在回复时备注上自己的微信账号即可，群主邀请后会把这里的账号去掉。**

**请大家认真回复，谢谢！**

**Comment by wysnxzm** [comment]
wysnxzm
徐志摩实名支持!

**Comment by yongxinwuMr** [comment]
你好

**Comment by yongxinwuMr** [comment]
wyx15930221877
