### ISSUE TITLE
主键生成UUID后该如何回显插入的主键？

### ISSUE THREAD

**Issue by MuenYu** [abel533/Mapper#235]
问题同[整合通用Mapper后 ，如何获取的 insert 成功后的 主键值 UUID](https://www.oschina.net/question/3439071_2239104)

给出我的配置：
```properties
#通用mapper
mapper.mappers=org.boot.ssm.wxshop.common.BaseMapper
mapper.not-empty=false
mapper.identity=MYSQL
mapper.before=true
```

```java
//实体类id
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY,generator = "select uuid()")
private String id;
```

谢谢

**Comment by abel533** [comment]
文档地址：https://mapperhelper.github.io/docs/3-2.mapper-uuid/

你给出配置没有问题，你这里没法返回主键？发个日志看看。

你也可以试试 4.0.0-beta3 中的 [@KeySql 注解](https://github.com/abel533/Mapper/wiki/2.3-generatedvalue#233-%E9%80%9A%E8%BF%87%E5%BA%8F%E5%88%97%E5%92%8C%E4%BB%BB%E6%84%8F-sql-%E8%8E%B7%E5%8F%96%E4%B8%BB%E9%94%AE%E5%80%BC)。

**Comment by MuenYu** [comment]
谢谢作者热情的解答，根据文档已经解决了问题，是因为通用Mapper方法和自己写的方法重名导致的。
