### ISSUE TITLE
能否通过泛型确定主键类型？

### ISSUE THREAD

**Issue by FrancisLee513** [abel533/Mapper#239]
在使用`T selectByPrimaryKey(Object key)`过程中可能会因为“手滑”传入了错误的类型。
能否通过泛型限制其主键类型？类似如：
(参考自Spring Data Jpa)
```
public interface SelectByPrimaryKeyMapper<T , ID> {
    T selectByPrimaryKey(ID key);
}
```
使用：
```
public interface UserMapper extends Mapper<User , Long>
```
其他相关方法：
* `int deleteByPrimaryKey(Object key);`
* .....

盼复。

**Comment by abel533** [comment]
已经在考虑中，不过不会改现有的，会考虑通过提供一个 base 包的替代。

**Comment by FrancisLee513** [comment]
😀

**Comment by FrancisLee513** [comment]
可使用 ： https://github.com/abel533/mapper-base2

**Comment by liugdxd** [comment]
期待

**Comment by abel533** [comment]
@liugdxd 可使用 ： https://github.com/abel533/mapper-base2
