### ISSUE TITLE
配置项 mapper.ORDER=BEFORE 设置无效

### ISSUE THREAD

**Issue by jiaozhu** [abel533/Mapper#242]
该配置在 mapper-spring-boot-starter **1.2.3** 版本中，正常使用。

但升级到 mapper-spring-boot-starter **2.0** 之后，ID就无法获得了。

数据库：**Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production**

```java
@Id
@Column(name = "ID")
@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select sys_guid() from dual")
private String id;
```

不知道是不是升级版本之后还需要有别的更改。

**Comment by abel533** [comment]
### 3.3  ORDER(别名: order, before)

`<selectKey>`中的`order`属性，可选值为`BEFORE`和`AFTER`。

后来为了方便在 Spring Boot 中配置该参数，符合 Boot 的规范，增加了 `order`  和 `before` 两个别名。

在 3.1 的配置以及 2.3.2 和 2.3.3 中都提到了这个参数。

在支持主键递增，满足 2.3.2 中的情况时，配置如下：

```properties
//Properties 方式配置时
ORDER=AFTER
//还可以
order=AFTER
//或
before=false

//Spring Boot 中，比上面多个前缀，并且 ORDER 不能使用
mapper.order=AFTER
//或者（Spring Boot）
mapper.before=false
```

在类似Oracle序列或者通用的 UUID 时，配置如下：

```properties
//Properties 方式配置时
ORDER=BEFORE
//还可以
order=BEFORE
//或
before=true

//Spring Boot 中，比上面多个前缀，并且 ORDER 不能使用
mapper.order=BEFORE
//或者（Spring Boot）
mapper.before=true
```

**上面示例中有多种写法，使用时按照需要选择一种即可，切勿同时配置！**


>目前 order 存在一个 bug，会尽快发布 4.0.1 和 2.0.1 版本解决此问题。

**Comment by jiaozhu** [comment]
再次更新到 mapper-spring-boot-starter 2.0 ，依次尝试了以下四种方式

```properties
#mapper.before=true
#mapper.order=BEFORE
#mapper.b-e-f-o-r-e=true
mapper.o-r-d-e-r=BEFORE
```

都不行....

**Comment by jiaozhu** [comment]
静等了，感谢！

**Comment by anlen667** [comment]
感谢，静候！
