### ISSUE TITLE
SpringBoot中如何使用生成器？

### ISSUE THREAD

**Issue by yihuishou** [abel533/Mapper#243]
`<plugin type="tk.mybatis.mapper.generator.MapperPlugin">`
`<plugin type="tk.mybatis.mapper.generator.TemplateFilePlugin">`
 IDE找不到插件

**Comment by abel533** [comment]
用的什么方式？maven插件？还是其他什么？

**Comment by yihuishou** [comment]
maven插件

**Comment by yihuishou** [comment]
```Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate (default-cli) on project iab-manager: Execution default-cli of goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate failed: A required class was missing while executing org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate: freemarker/cache/TemplateLoader```

**Comment by abel533** [comment]
参考示例中的配置，注意插件中的依赖：
https://github.com/abel533/MyBatis-Spring-Boot/blob/master/pom.xml

**Comment by yihuishou** [comment]
加了                
`
                  <dependency>
                        <groupId>tk.mybatis</groupId>
                        <artifactId>mapper-generator</artifactId>
                        <version>1.0.0</version>
                    </dependency>
`
IDEA依然提示错误，可用的补全只有：

**Comment by yihuishou** [comment]
![99001](https://user-images.githubusercontent.com/26241263/37942791-78e20bcc-31a7-11e8-9a86-9c63eaa9ab22.jpg)

**Comment by abel533** [comment]
IDE有问题，不用管。

**Comment by yihuishou** [comment]
emmm 后来发现这个是IDEA的第三方插件 Mybatis_Plug提供的提升功能~
