### ISSUE TITLE
update 根据主键更新的错误

### ISSUE THREAD

**Issue by kin-chen** [abel533/Mapper#247]
![image](https://user-images.githubusercontent.com/22582810/37822983-150a77d8-2ec3-11e8-9e06-d56dcb7acbe2.png)
在更新的时候，为什么还有set 主键。实体类如下：
![image](https://user-images.githubusercontent.com/22582810/37823030-353b3e34-2ec3-11e8-8d28-0ee72ed51774.png)
望哪位大神解答一下。

**Comment by abel533** [comment]
错误是什么呢？

id = id where id = ? 对 update 没任何影响。

**Comment by 17625693** [comment]
感谢大神的回复，今天重新尝试。还是依然报错。是否是和Sqlserver 有关。我使用 navicat 把生成的sql语句执行。报相同的错误。程序的错误如下：
![image](https://user-images.githubusercontent.com/22582810/37883626-21a7caa0-30de-11e8-81bb-d1e5048e00d7.png)
工具报错如下：
![image](https://user-images.githubusercontent.com/22582810/37883667-54f72324-30de-11e8-8355-b50e10f5d438.png)

**Comment by 17625693** [comment]
当我去除 id=id 尝试，就不会有这个错误。

**Comment by abel533** [comment]
这可能和数据库有关，下个版本增加配置：
https://github.com/abel533/Mapper/issues/249

**Comment by abel533** [comment]
updateable=false会排除。
