### ISSUE TITLE
mybatis-generator 插件能生成纯注解接口吗？

### ISSUE THREAD

**Issue by yihuishou** [abel533/Mapper#248]
继承通用Mapper但不想生成XML文件

**Comment by abel533** [comment]
能，看 MBG 的介绍。
http://mybais.tk 上面有个链接。

**Comment by yihuishou** [comment]
链接无效的说~

**Comment by abel533** [comment]
链接错了。。http://mybatis.tk

**Comment by abel533** [comment]
https://blog.csdn.net/isea533/article/details/42102297

**Comment by NaccOll** [comment]
@abel533 我想请问一下，当我不改动mbg的其他配置值加入
···xml
···
