### ISSUE TITLE
解决某些数据库 UPDATE 不能更新主键的问题。

### ISSUE THREAD

**Issue by abel533** [abel533/Mapper#249]
https://github.com/abel533/Mapper/blob/d591357b5a157d761bf652bde90d90328f5528f2/core/src/main/java/tk/mybatis/mapper/mapperhelper/SqlHelper.java#L477

这里增加对 `updateable` 的判断，以及增加全局参数 idupdateable。

**Comment by 17625693** [comment]
感谢。期待新的版本。通用mapper给我开发提供了很大帮助。特别是开发人员极少的情况下。可以省出很多时间。

**Comment by zhougod520** [comment]
请问下多少版本之后才支持这个功能？ 我当前的数据库也不支持set id =id

**Comment by abel533** [comment]
2022年准备发布的版本才有这个...
