### ISSUE TITLE
selectByExampleAndRowBounds未生成带limit的 查询语句

### ISSUE THREAD

**Issue by imzhuli** [abel533/Mapper#25]

**Comment by imzhuli** [comment]
selectByExampleAndRowBounds 未生成带limit的 查询语句
看了一下源码. 似乎没有实现这个功能 ?

**Comment by imzhuli** [comment]
还是说最终是通过JDBC的游标来实现的?

**Comment by abel533** [comment]
这个默认是内存分页，配合PageHelper 才能物理分页

2016-06-01 10:32 GMT+08:00 Zhu Li <notifications@github.com>:
