### ISSUE TITLE
xml配置EnumOrdinalTypeHandler使用通用接口查询失效

### ISSUE THREAD

**Issue by zjun2** [abel533/Mapper#251]
xml的resultMap中配置了字段使用了EnumOrdinalTypeHandler，通过xml配置的select语句可以成功查询数据。当使用通用接口查询数据时失效了，使用了默认的EnumTypeHandler处理报错。
看了[https://github.com/abel533/Mapper/wiki/7.2.typehandler](url)的使用教程，但是觉得太过于麻烦了，因我有很多个类都会有枚举类型，按教程的配置每一个枚举类型我都得创建一个对应的类继承EnumOrdinalTypeHandler。这似乎不太友好，想扩展来着但是技术不行不知从何下手.
有没有好的解决方案？

**Comment by 410919244** [comment]
能否给写一个通用枚举类型的TypeHandler，或者怎么修改让默认的枚举处理使用EnumOrdinalTypeHandler

**Comment by abel533** [comment]
mybatis新版本能配置默认的枚举处理器。
几周前本来要写个最完整的枚举用法，写了个开头就一直没继续。

**Comment by windyzj** [comment]
3.4.6可以把枚举直接写入字段什么都不用加，  但是3.5.2反而不行了  不知道是为什么，有什么简单的用法么

**Comment by abel533** [comment]
@windyzj https://github.com/abel533/Mapper/wiki/7.2.typehandler

**Comment by Chad2li** [comment]
还是没有解决？Mapper通用方法，无法使用通用枚举类型，即便是注册全局通用枚举也不行。
插入数据、使用XML文件写的查询SQL都可以。
但使用通用方法查询数据，无法解析自定义的枚举值。
有解决办法吗？
