### ISSUE TITLE
Mybatis-Generator 生成的Mapper缺包？

### ISSUE THREAD

**Issue by yihuishou** [abel533/Mapper#252]
[https://github.com/abel533/Mapper/wiki/4.2.codegenerator]文档中
`
        
        <plugin type="tk.mybatis.mapper.generator.MapperPlugin">
            <property name="mappers" 
              value="tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.hsqldb.HsqldbMapper"/>
            <property name="caseSensitive" value="true"/>
            <property name="forceAnnotation" value="true"/>
            <property name="beginningDelimiter" value="`"/>
            <property name="endingDelimiter" value="`"/>
        </plugin>
`
生成的Mapper提示缺失`tk.mybatis.mapper.hsqldb.HsqldbMapper`

在`mapper-spring-boot-starter` 1.2.4 中找不到？

**Comment by abel533** [comment]
HsqldbMapper 是测试中的代码。。你用这个干啥？

**Comment by yihuishou** [comment]
文档里是这样的~ 就粘贴过来了~
