### ISSUE TITLE
Spring Boot 中集成的问题

### ISSUE THREAD

**Issue by yihuishou** [abel533/Mapper#254]
yml中配置
`mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true
`
需要配合`@MapperScan`注解使用吗？

**Comment by abel533** [comment]
如果用 Starter，不需要这个注解。。

如果用注解可以不要 Starter。。注意看最新版本的文档。

**Comment by yihuishou** [comment]
使用Starter的正常姿势是什么样的呢？

文档中说mybatis-starter自动配置会失效，
那mybatis-starter全都要配置吗？

使用纯接口和注解配合通用Mapper，配置mapper: mappers:。
启动失败。

mappers这个指的是mapper本身？还是mapper所在的包？
如果是mapper本身，那有没有通配符？

大神能给出使用注解和使用XML 配合Mapper的完整示例吗？

**Comment by 17625693** [comment]
![image](https://user-images.githubusercontent.com/22582810/38012274-5c1bb5c8-3293-11e8-8907-82766f00e605.png)
以上是我在springboot中的配置。你可以参考。配置好以后，仅仅需要在启动类上面增加 @MapperScan即可

**Comment by yihuishou** [comment]
@17625693 emmm 那文档里写的第一种方式
`mapper:
            mappers:
`
配置方式怎么用？ 不是说不用@MapperScan？

**Comment by abel533** [comment]
文档写的还不够清楚吗？具体哪儿不明白？

**Comment by yihuishou** [comment]
基于Starter的自动配置.... 不加注解就找不到mapper了~

**Comment by qiuzhi** [comment]
不用@mapperscan注解，那就是每个Dao都要加@mapper注解，那个Starter自动配置才能找到Bean吧，不知道我说得对不

**Comment by qiuzhi** [comment]
或者用mybatis原生的那个mapperscan

**Comment by qiuzhi** [comment]
刚试了下，不用tk提供的@mapperscan注解，配置不成功，就是用的文档说的第一种方式，有没详细一点的样例？

**Comment by qiuzhi** [comment]
自动配置只能加上@Mapper注解才能用？原生的@MapperScan也不行，想不懂，程序可以跑起来，报：
java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()

**Comment by yihuishou** [comment]
文档里的第一种使用自动配置说明模糊不清，配置无法使用，示例也找不到~ QAQ

**Comment by yihuishou** [comment]
@abel533 大神能不能把之前楼层中的问题解答一下呢？ 文档里的描述看不懂~

**Comment by qiuzhi** [comment]
不用tk的mapperscan，就要在每个mapper添加mapper注解，原生mybatis的mapperscan注解应该是不起作用的了

**Comment by qiuzhi** [comment]
@abel533 ，好的，谢老大了，这个工程还是用了tk的mapperscan注解，有没不用的？用mybatis原生那个的？

**Comment by abel533** [comment]
@yihuishou 用 starter 的情况下，不需要mapperscan注解，如果想用就用 tk.mybatis 开头的。

**Comment by freeluck01** [comment]
@abel533 
spring-boot-starter-parent：2.0.0.RELEASE
mybatis-spring-boot-starter：1.3.2
mapper-spring-boot-starter：2.0.1
org.mybatis：mybatis 3.4.6
加和不加tk的MapperScan都报：At least one base package must be specified
换成org.mybatis.spring.annotation.MapperScan，报：
java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.base.BaseSelectProvider.<init>()
这个是哪里的问题呢？谢谢

**Comment by CodingOX** [comment]
@abel533 我也发现了相同的问题，您的代码或者文档确实存在问题。
即使添加了 start 的情况下，如果不在启动类上加 mapperscan 注解，也会报找不到bean 的错误。
我将您的 demo 项目:
做了2个小修改：
1. 启动类的 mapperscan 注释掉。
2. 在 dev 的配置中添加 
`# 配置mapper包所在位置
mapper.mappers=tk.mybatis.springboot.mapper
mapper.notEmpty=true`

同样报错如下，请核实：https://github.com/abel533/MyBatis-Spring-Boot
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'tk.mybatis.springboot.mapper.BlogMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`

这是 BUG 还是文档错误？

**Comment by abel533** [comment]
@CodingOX @freeluck01 在 mybatis-starter 设计上，application.properties 无法配置扫描路径，所以如果不使用 MapperScan 指定包名，就需要在接口上增加 @Mapper 注解。。否则 mybatis 也认不出来那个是 Mapper 接口。

文档会完善这部分介绍。

**Comment by chinleo** [comment]
难倒不是用`@RegisterMapper`注解标记?

**Comment by abel533** [comment]
不是这个标记，这个标记是给扩展接口用的。

**Comment by zhouxianjun** [comment]
![image](https://user-images.githubusercontent.com/5254523/39856735-9925be7c-5463-11e8-826b-d77c6bd5657a.png)

你们难道没有这个警告吗？

**Comment by abel533** [comment]
这个没影响。

**Comment by ftqh-johnny** [comment]
如何显示sql语句出来呢，比如自己添加的方法，运行时想看下自己的sql语句：
添加logging.level.com.mapper=debug 也是无法显示sql语句了。

**Comment by veritasw** [comment]
有人碰到过boot里读不到property配置的情况吗？我在yml里配的config-location和mapper-location都不生效，我是通过在MapperAutoConfiguration和MybatisProperties两个类里打断点跟踪定位的，this.properties的这两个属性都是null，不知道错在哪了。。现在扫不到mapper xml导致调用里面的方法时报invalid bound，愁人啊。。

**Comment by abel533** [comment]
@veritasw 你资源文件在 src/main/java 下面还是 resources 下面？

**Comment by fangsj** [comment]
**加和不加tk的MapperScan都报：At least one base package must be specified** 请问这个问题解决了嘛？我的也一直处于这个问题没办法解决

**Comment by jianghuzai** [comment]
我来给个基于 @MapperScan 注解的手工配置？

## pom.xml
> 不用starter，则需要引入tk.mybatis.mapper。(来源于基于java编码方式集成)

```xml
		<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
			<version>1.3.2</version>
		</dependency>
		<!--<dependency>-->
			<!--<groupId>tk.mybatis</groupId>-->
			<!--<artifactId>mapper-spring-boot-starter</artifactId>-->
			<!--<version>2.0.2</version>-->
		<!--</dependency>-->
		<dependency>
			<groupId>tk.mybatis</groupId>
			<artifactId>mapper</artifactId>
			<version>4.0.0</version>
		</dependency>
```
## application-dev.yml

```yml
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.ccsa.exam.server.model  # 注意：对应实体类的路径

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

mapper:
  mappers:
      - tk.mybatis.mapper.common.Mapper
      - tk.mybatis.mapper.common.Mapper2
```

## Application.java
```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import tk.mybatis.spring.annotation.MapperScan;

@SpringBootApplication
@MapperScan("cn.ccsa.exam.server.dao")
public class ServerApplication {

	public static void main(String[] args) {
		SpringApplication.run(ServerApplication.class, args);
	}
}
```

## 最后，
如果我用starter方式，总会报一个无法把String转成什么鬼的异常。如果有大神成功一starter方式跑起来， 请赐教

**Comment by cheneyjuu** [comment]
目前这个问题解决了没有？

**Comment by jkm6221** [comment]
用这个试试 
mybatis.mapper-locations: classpath*:mapper/*.xml
而不是
mybatis：
    mapper-locations: classpath*:mapper/*.xml
