### ISSUE TITLE
使用SqlServer进行数据存储的时候，不可以有主键的存在。

### ISSUE THREAD

**Issue by kin-chen** [abel533/Mapper#255]
在使用微软的Sqlserver进行数据存储的时候。生成的sql语句中有主键的字段。此时数据无法正常插入到数据库。目前解决办法是在主键上标注如下：
@Id
    @Column(name = "Id",**insertable = false**)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
希望的是可以根据数据库的类型。自动把主键的策略添加上。

**Comment by abel533** [comment]
主键策略只能自己设置。

如果在增加个数据库类型的参数，处理起来就更麻烦了。。所以提供了一个sqlserver专用的insert方法，你可以看看 https://github.com/abel533/Mapper/tree/master/base/src/main/java/tk/mybatis/mapper/common/sqlserver

**Comment by unbesito** [comment]
public interface MSBaseMapper<T> extends BaseSelectMapper<T>, SqlServerMapper<T>, BaseUpdateMapper<T>, BaseDeleteMapper<T> {
}
实现方式，sqlserver插入时报nosuchmethod错误

**Comment by abel533** [comment]
@unbesito 贴上完整的错误信息。

**Comment by leongfeng** [comment]
这么设：
>  @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY, generator="SqlServer")
    private Integer id;
