### ISSUE TITLE
Mapper Generator 提示问题~

### ISSUE THREAD

**Issue by yihuishou** [abel533/Mapper#259]
以后会为`Mapper Generator 1.0.0`提供`Mybatis Geneator 插件`参数提示功能吗？

**Comment by abel533** [comment]
什么提示？举个例子。

**Comment by yihuishou** [comment]
比如IDEA可以自动提示相关参数~ 比如阿里的`druid-spring-boot-starter`
IDE就能提示参数。

**Comment by abel533** [comment]
这是IDEA对 starter 的特殊处理。。MBG不行。

**Comment by yihuishou** [comment]
嗷QAQ
