### ISSUE TITLE
能否支持多租户？

### ISSUE THREAD

**Issue by maobole** [abel533/Mapper#261]
Mapper有没有机制可以支持租户识别，动态切换数据源？

**Comment by abel533** [comment]
如果不是基于 mycat 实现的。。就用spring的动态数据源可以实现。

**Comment by maobole** [comment]
感谢回复！你的这个插件非常棒，在我们项目中广泛使用！
咱们这个Mapper可以和mycat结合使用么？

**Comment by abel533** [comment]
可以和mycat结合用，需要你实现切换租户。

**Comment by maobole** [comment]
有没有和mycat结合的使用例子，多谢！

**Comment by abel533** [comment]
没有例子。

**Comment by ywj1352** [comment]
能否在每条SQL执行前更改schema

**Comment by liunewshine** [comment]
我们的多租户只有一个数据库，根据一个id区分是哪家，这个动态数据源实现不了吧
