### ISSUE TITLE
KeySql支持

### ISSUE THREAD

**Issue by fnwib** [abel533/Mapper#262]
tk.mybatis.mapper.entity.EntityColumn提供@tk.mybatis.mapper.annotation.KeySql 的属性

**Comment by abel533** [comment]
不知道是不是群里说过的一个问题，内容和当时说的有区别。

你是想从 entitycolumn获取这个注解的信息？通过 entitycolumn中的field字段能获取。

**Comment by abel533** [comment]
目前可能存在的一个 bug 是 insertList 不能识别。

**Comment by fnwib** [comment]
我从EntityColumn 获取到EntityField 可以拿到KeySql注解 我的问题解决了
