### ISSUE TITLE
IdsProvider中的疑问

### ISSUE THREAD

**Issue by geedys** [abel533/Mapper#264]
版本：mapper-base-1.0.0.jar
tk.mybatis.mapper.provider.IdsProvider中65行，90行代码
```sql.append(" in (${_parameter})");```
若果我的id参数是字符串类型，比如abc,def,拼接后的sql就是....in (abc,def).因为代码中使用的$符号。会导致sql执行失败。
提问：如果我需要字符串类型的id，就得使用‘abc’,'def'这样的传值。感觉不合理。作者是故意这样设计的吗？

**Comment by abel533** [comment]
这里就是这么设计的。。其实也可以有 `insertList(Iterable<T> iter)` 这样的方法。
