### ISSUE TITLE
关于数据库保留字的建议

### ISSUE THREAD

**Issue by FrancisLee513** [abel533/Mapper#265]
有时数据库的表名或列名会和数据中的保留字冲突，建议在生成SQL的时候统一使用( ` )字符包裹表名和列名。

**Comment by abel533** [comment]
看这里：https://github.com/abel533/Mapper/wiki/3.config#313--wrapkeyword

**Comment by FrancisLee513** [comment]
别忘记表名也要做处理哦

**Comment by abel533** [comment]
表名的处理已经提交了。

**Comment by FrancisLee513** [comment]
👍
