### ISSUE TITLE
无法获取实体类对应的表名

### ISSUE THREAD

**Issue by jacky1193610322** [abel533/Mapper#266]
你好，在最近的项目里面使用tk.mapper, 同时有一个服务类，需要提前加载数据库的资源作为缓存一样，常驻内存，使用@Bean(initMethod = )的方式来初始化，但是在实际执行查询的时候，报了无法获取实体类对应的表名，跟踪代码发现是MapperAutoConfiguration 加载的时机晚于程序定义的Bean加载，造成执行查询的时候mapper还没有注册，报错了，想问一下，有什么可以将MapperAutoConfiguration的加载顺序提前，或者如果使用了tk.mapper，如果可以在web启动的时候执行sql查询？我看了issue里面有类似的，我也尝试了，我把devtools 去掉之后，还是有这样的问题，我使用了tk 3.4.3 版本和4.0都还有这个问题。

**Comment by abel533** [comment]
换最新版本试试

**Comment by jacky1193610322** [comment]
谢谢你的回复， 可是我使用了最新版本4.0 还是有这个问题

**Comment by abel533** [comment]
在 starter 的逻辑中，如果你没有使用 @MapperScan 注解，你就需要在你的接口上增加 @Mapper 注解，否则 MyBatis 无法判断扫描哪些接口。

**Comment by jacky1193610322** [comment]
![image](https://user-images.githubusercontent.com/16514353/38561831-adc160c6-3d0b-11e8-87c7-88ca7b05fc00.png)
我使用mapperscan  如果不需要在程序启动的时候加载，一切都是正常的。

**Comment by abel533** [comment]
可以看文档中的 Configuration 方式。

**Comment by jacky1193610322** [comment]
好的，谢谢

**Comment by jacky1193610322** [comment]
你好，不知道是不是表达有误，我上面的配置是能正常使用的，只不过不能满足在服务启动的过程中去读取数据库这个需求，git上面的文档我看了，但是没有提到这个问题，你说的文档中的 Configuration 方式是指哪个文档？麻烦告知一下，谢谢

**Comment by jacky1193610322** [comment]
通过使用<tk.mybatis.starter.version>2.0.0</tk.mybatis.starter.version> 2.0版本解决了，谢谢
