### ISSUE TITLE
实体类有继承关系时,insert子类时,自动生成的sql将父类的列也包含进去了,怎么解决。

### ISSUE THREAD

**Issue by KsAlone** [abel533/Mapper#267]
实体类有继承关系时,insert子类时,自动生成的sql将父类的列也包含进去了.我想让sql只包含子类的列,应该怎么解决

**Comment by abel533** [comment]
父类的字段都加注解忽略

**Comment by KsAlone** [comment]
加什么注解呢？那加上注解之后，父类对象如果想插入表记录字段不会被忽略掉吗(我的父子对象都对应了各自的表)

**Comment by abel533** [comment]
会忽略掉。看这儿：https://github.com/abel533/Mapper/wiki/2.2-mapping#225-transient-%E6%B3%A8%E8%A7%A3jpa
