### ISSUE TITLE
根据主键批量删除

### ISSUE THREAD

**Issue by KsAlone** [abel533/Mapper#269]
请问有实现根据主键集合进行批量删除的方法吗？

**Comment by abel533** [comment]
昨天晚上增加了：https://github.com/abel533/Mapper/tree/master/extra/src/main/java/tk/mybatis/mapper/additional/idlist

测试：
https://github.com/abel533/Mapper/blob/master/extra/src/test/java/tk/mybatis/mapper/additional/idlist/IdListMapperTest.java

**Comment by KsAlone** [comment]
4.0.0版本没有增加吗？

**Comment by abel533** [comment]
以前版本有 IdsMapper 你自己看。
