### ISSUE TITLE
updateByPrimaryKey不更新对象字段

### ISSUE THREAD

**Issue by muling105** [abel533/Mapper#271]
Staff类中有一字段是如下（Organize是自定义的一个对象）：
@ManyToOne(fetch = FetchType.EAGER, targetEntity = Organize.class)
@JoinColumn(name = "ORGANIZE_ID", referencedColumnName="ORGANIZE_ID")
private Organize organize;//部门ID

更新前设置了
bean.setOrganize(organize);
staffService.update(bean);//执行更新操作
但是使用updateByPrimaryKey更新时，UPDATE语句并没有更新此字段，请问更新对象字段时该如何操作？

**Comment by abel533** [comment]
只支持单表。。如果想完整支持jpa，可以考虑hibernate。
