### ISSUE TITLE
MySQL数据库"virtual"关键字(保留字)没有列举到

### ISSUE THREAD

**Issue by chinleo** [abel533/Mapper#272]
查资料MySQL 5.7 新增了virtual关键字(保留字), 目前使用到的mapper-4.0.1中 `SqlReservedWords` 类中未覆盖到, 希望后续版本添加

**Comment by zlx** [comment]
维护者你好，最近项目升级也遇到了这个问题，请问目前这个功能是否支持？或者有没有办法可以自己扩展。
谢谢！
