### ISSUE TITLE
特殊查询列和插入列配置

### ISSUE THREAD

**Issue by abel533** [abel533/Mapper#273]
需求如下：
![image](https://user-images.githubusercontent.com/1787798/38723733-9be12974-3f34-11e8-9256-11553ccb7d32.png)

查询的时候需要用函数获取该列。。

insert 时，`value(fun('xxxx'))` 也要用到函数。

如果能够方便集成到现有方法就考虑。。

如果不能就考虑增加两个扩展方法用作示例。

**Comment by vision-ken** [comment]
@abel533 这个特性实现了吗？怎么使用？

**Comment by vision-ken** [comment]
@abel533 hello，在吗，方便回复下吗
