### ISSUE TITLE
typehandler 无效

### ISSUE THREAD

**Issue by mocking3** [abel533/Mapper#275]
updateByExample 不走设置的typehandler     
@ColumnType(typeHandler = xxx.class, jdbcType = JdbcType.VARCHAR)

**Comment by abel533** [comment]
由于 Example 的 xml 中不方便记录 typehandler 信息，暂时还没有好的办法解决这个问题。

**Comment by wulinjie122** [comment]
这个问题解决了吗？我们也遇到这个问题了，看来只能放弃这个框架了

**Comment by abel533** [comment]
example是动态的，不支持。。用非example方法
