### ISSUE TITLE
执行 selectOneByExample异常 here is no getter for property named 'distinct' in 'class tk.mybatis.mapper.entity.Example$Criteria'

### ISSUE THREAD

**Issue by gocreater** [abel533/Mapper#276]
执行 myMapper.selectOneByExample(Example(UserTokenEntity::class.java) .createCriteria().andEqualTo("token", token))
抛出异常：
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'distinct' in 'class tk.mybatis.mapper.entity.Example$Criteria'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)

**Comment by gocreater** [comment]
![Uploading TIM图片20180418210203.png…]()

**Comment by 1069355234** [comment]
同问

**Comment by abel533** [comment]
`xx.selectOneByExample(example)`
