### ISSUE TITLE
如果对应的mapper没有xml配置，它是怎么加载到mappedStatement中的呢？

### ISSUE THREAD

**Issue by JavaLover-ZYJ** [abel533/Mapper#279]
您好这点我没有看明白，我了解的是SqlSessionFactoryBean中通过配置(mapper路径)mapperLocations，通过mybatis源码同将xml及注解加载到mappedStatement中。但是有些mapper没有xml，怎么加载到mappedStatement中呢（加载到mappedStatement中才能把其中的sqlSource替换成自己生成的）？

**Comment by abel533** [comment]
这是用的注解方式，所以没有xml。

**Comment by JavaLover-ZYJ** [comment]
我了解了  MapperScannerConfigurer 也会扫描注解。

**Comment by JavaLover-ZYJ** [comment]
一直以为只有SqlSessionFactoryBean 它才会扫描xml及注解呢。  多谢大神
