### ISSUE TITLE
主键用JAVA方法生成的方式

### ISSUE THREAD

**Issue by ranjinpeng** [abel533/Mapper#280]
我原来使用 <selectkey> 标签的方式 配置的  调用我程序内部的方法生成id  是可以使用的。最近项目重建从普通的mybites 重构到tkmapper   我原来那种方式现在怎么实现呢？ 我看您文档上说@keysql 主键 对应的XML就是我原来的  但是我配置了@keysql注解 还是没办法注入id 。 这个问题困扰我好久了 能否解答呢。

**Comment by abel533** [comment]
4.0.2 版本增加了 genId 方法，详情看 Mapper 更新日志和这里：
https://blog.csdn.net/isea533/article/details/80040379
