### ISSUE TITLE
MBG生成的Model类中，如何将@GeneratedValue替换@KeySql？

### ISSUE THREAD

**Issue by tccoca** [abel533/Mapper#282]
看到最新的free-mapper 4文档，并实际操作了一把，发现MBG生成的Model类中依然是@GeneratedValue注解，那么如何替换成@KeySql这个新注解呢？

用的free-mapper版本是4.0.2，MBG版本是1.3.6。

**Comment by abel533** [comment]
目前还不支持直接生成。

一个好的主键用法是创建一个基类，配置好ID策略，其他类通过 `rootClass` 配置（保证mbg能访问到该类），这样就不需要配置主键。
