### ISSUE TITLE
WeekendSqls 方法参数类型修改

### ISSUE THREAD

**Issue by fnwib** [abel533/Mapper#283]
public WeekendSqls<T> orNotEqualTo(Fn<T, Object> fn, String value) {
        return this.orNotEqualTo(Reflections.fnToFieldName(fn), value);
}

public WeekendSqls<T> orNotEqualTo(Fn<T, Object> fn, String value) {
        return this.orNotEqualTo(Reflections.fnToFieldName(fn), value);
}
建议第二个参数修改为Object类型

**Comment by abel533** [comment]
确实需要改。

**Comment by abel533** [comment]
目前就是 Object。

**Comment by fnwib** [comment]
有一些方法是Object,有一些是String ，应该把所有的String改成Object

**Comment by abel533** [comment]
like 方法是 String，其他都是 Object，没问题吧？
