### ISSUE TITLE
关于联合主键，使用insertList遇到的问题

### ISSUE THREAD

**Issue by whyalwaysmea** [abel533/Mapper#284]
业务场景是多对多的情况下，有一个中间表，中间表中是任务id和用户id
表结构如下：
```sql
CREATE TABLE `record` (
   `task_id` bigint(20) NOT NULL COMMENT '任务id',
   `user_id` varchar(36) NOT NULL COMMENT '用户id',
   PRIMARY KEY (`task_id`,`user_id`)
 ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 
```

entity如下：
```java
public class Record {
    @Id
    private Long taskId;
    @Id
    private String userId;
    // 省略setter/getter
}
``` 

当插入单条数据不会有问题:
```java
Record record = new Record();
record.setTaskId(123456L);
record.setUserId("oiFEY45nkdB561Rne68LNqqJqVFA");
recordMapper.insert(record);
``` 

但是调用insertList时会出错
```java
Record record1 = new Record();
record1.setTaskId(123456L);
record1.setUserId("oiFEY45nkdB561Rne68LNqqJqVFA");

Record record2 = new Record();
record2.setTaskId(456789L);
record2.setUserId("asd23sdfzcgd61dRe41LFD9j1A");

List<Record> list = new ArrayList<>();
list.add(record1);
list.add(record2);
recordMapper.insertList(list);
```
打印的SQL如下：
```
t.m.s.m.A.insertList                     : ==>  Preparing: INSERT INTO record VALUES  
t.m.s.m.A.insertList                     : ==> Parameters:    
```
如果我把entity中的`@Id`取消，那么insertList就是正确的。  

请问这是什么原因导致的呢？ 该如何正确的处理？

**Comment by abel533** [comment]
换这个：https://github.com/abel533/Mapper/blob/master/extra/src/main/java/tk/mybatis/mapper/additional/insert/InsertListMapper.java

**Comment by whyalwaysmea** [comment]
我的recordMapper是继承了[MyMapper](https://github.com/abel533/MyBatis-Spring-Boot/blob/master/src/main/java/tk/mybatis/springboot/util/MyMapper.java)，MyMapper是继承了MySqlMapper，进而继承了InsertListMapper。 
不过InsertListMapper是包`tk.mybatis.mapper.common.special`下的，不知道有何区别。maven依赖版本如下
```xml
<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper-spring-boot-starter</artifactId>
    <version>2.0.1</version>
</dependency>
```

**Comment by veritasw** [comment]
借着这个问题，想问一下用联合主键时该怎么查询？selectByPrimaryKey支持联合主键么？

**Comment by abel533** [comment]
支持联合主键，传实体类。

**Comment by whyalwaysmea** [comment]
我的recordMapper是继承了[MyMapper](https://github.com/abel533/MyBatis-Spring-Boot/blob/master/src/main/java/tk/mybatis/springboot/util/MyMapper.java)，MyMapper是继承了MySqlMapper，进而继承了InsertListMapper。 
不过InsertListMapper是包`tk.mybatis.mapper.common.special`下的，不知道有何区别。maven依赖版本如下
```xml
<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper-spring-boot-starter</artifactId>
    <version>2.0.1</version>
</dependency>
```

所以这样还是有问题，那么应该怎么做呢？

**Comment by abel533** [comment]
方法上都有注释说明，按说明用。。可以试试2.0.3-beta1 版本。

**Comment by frank-zg** [comment]
感觉对联合主键的insertList还是支持的不太友好. InsertUidListMapper中对keyProperty的描述也没有说明联合主键的填写规则
