### ISSUE TITLE
有没有批量插入的方法

### ISSUE THREAD

**Issue by chenwuwen** [abel533/Mapper#286]
我在这个连接里看到有批量插入的方法，但是我下载了最新版的通用Mapper 4.0.1 没有发现批量的方法啊
https://github.com/abel533/Mapper/issues/184

**Comment by abel533** [comment]
https://github.com/abel533/Mapper/blob/master/extra/src/main/java/tk/mybatis/mapper/additional/insert/InsertListMapper.java

**Comment by blessingsi** [comment]
> abel533 commented on 26 Apr
> https://github.com/abel533/Mapper/blob/master/extra/src/main/java/tk/mybatis/mapper/additional/insert/InsertListMapper.java

 @abel533 请问有类似于insertSelective的批量插入实现吗？数据库中某系字段设置了默认值，希望能够使用数据库的设置。

**Comment by leiyong316** [comment]
@blessingsi 我也遇到这种问题， insertList 数据库默认字段没有值

**Comment by abel533** [comment]
@blessingsi @leiyong316 没有根据判断插入。。因为所有列在开头就定义好了，后面的都是values。

**Comment by WenTao-Love** [comment]
这个InsertListMapper.java在sqlserver数据库环境下，不怎么靠谱。碰到Date类型就会发疯了。就是要insert 那批数中如果部分数据有date字段有值，部分没有值就会报错了

**Comment by abel533** [comment]
MyBatis 批量提交 - BATCH：CH：https://blog.csdn.net/isea533/article/details/80922305

**Comment by Apollo666** [comment]
在Oracle数据源下，用 insertList 报错：“命令行未结束”，不知所措了！！！
