### ISSUE TITLE
在扩展自己的通用mapper的时候，出现了类型转换异常

### ISSUE THREAD

**Issue by zhangshen023** [abel533/Mapper#287]
tk.mybatis.mapper.mapperhelper.MapperHelper cannot be cast to org.apache.ibatis.plugin.Interceptor

**Comment by abel533** [comment]
通用mapper不需要拦截器，你怎么配置的？

**Comment by zhangshen023** [comment]
我后来明白了，有一个MapperScannerConfigurer这个类，mapper中一个这个类，而mybatis也有，故一直不行
