### ISSUE TITLE
java+oracle数据库调用updateByPrimaryKeySelective、insertSelective等方法抛异常，无效的列类型: 1111

### ISSUE THREAD

**Issue by 602468816** [abel533/Mapper#29]
nested exception is org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='remark', mode=IN, javaType=class java.lang.String, jdbcType=null, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting null for parameter #2 with JdbcType OTHER . Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. Cause: java.sql.SQLException: 无效的列类型: 1111
六月 23, 2016 11:37:13 上午 org.apache.catalina.core.StandardWrapperValve invoke

**Comment by abel533** [comment]
用注解设置 JDBCTYPE试试

**Comment by 602468816** [comment]
试过了，还是会报错

**Comment by abel533** [comment]
settings 配置 `jdbcTypeForNull` 为 NULL

**Comment by liuxiang** [comment]
# 治标
`settings 配置 jdbcTypeForNull 为 NULL` 只能治标,后面会遇到新的异常`ORA-01400: 无法将 NULL 插入`

# 治本
1. 更新主键,sequence
```
    /**
     * 主键
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select SEQ_COUNTRY.nextval from dual")
    private Integer id;
```

2.保证序列先执行`ORDER=BEFORE`
```
<bean class="tk.mybatis.spring.mapper.MapperScannerConfigurer">
    <property name="basePackage" value="com.isea533.mybatis.mapper"/>
    <!-- 3.2.2版本新特性，markerInterface可以起到mappers配置的作用，详细情况需要看Marker接口类 -->
    <property name="markerInterface" value="com.isea533.mybatis.util.MyMapper"/>
    <!-- 通用Mapper通过属性注入进行配置，默认不配置时会注册Mapper<T>接口 -->
    <property name="properties">
        <value>
            ORDER=BEFORE
        </value>
    </property>
</bean>
```

可参考`mybatis-oracle`分支项目：(建议跑起来感受)
https://github.com/abel533/Mybatis-Spring/blob/mybatis-oracle/README.md

我的练习项目：https://github.com/liuxiang/bright_frame
