### ISSUE TITLE
mysql自增长的id如何自定义GenId实现类

### ISSUE THREAD

**Issue by chenwuwen** [abel533/Mapper#291]
使用mysql的自增长id，用到了通用mapper的insertList接口，查看文档需要自定义GenId的实现，我看了一下您的例子，一个是使用时间戳做主键，一个使用uuid做主键，那么自增长的主键要如何定义

**Comment by abel533** [comment]
mysql自增的有专门的方法。

**Comment by chenwuwen** [comment]
当我在model类的主键列上添加 @KeySql(sql = "select @@IDENTITY")注解
insertList依然报错： Error getting generated key or setting result to parameter object. Cause: org.apache.ibatis.binding.BindingException: Parameter 'id' not found. Available parameters are [list, collection]

**Comment by chenwuwen** [comment]
已解决，写下来帮助别人，之前之所以不行，是因为我定义的的baseMapper 继承了MySqlMapper这个接口，而这个接口他继承了tk.mybatis.mapper.common.special.InsertListMapper接口，自定义的接口应该继承tk.mybatis.mapper.additional.insert.InsertListMapper; 接口，主键列添加注解@KeySql(useGeneratedKeys = true) 即可
