### ISSUE TITLE
关于@select或xml自定义sql的bug

### ISSUE THREAD

**Issue by zhelunJiang** [abel533/Mapper#293]
关于@select或xml自定义sql的bug，无法识别数据表中型如：xxx_xxx 的列名，导致返回的数据为空。使用了@nameStyle也没有用。

**Comment by zhelunJiang** [comment]
加@Colum也没用

**Comment by abel533** [comment]
自己写的方法自己用mybatis方式处理映射。

**Comment by zhougod520** [comment]
+1，也遇到了这个问题，求解决办法

**Comment by abel533** [comment]
@zhougod520 自己在SQL中用别名映射，或者用 resultMap 自己配置。

**Comment by zhelunJiang** [comment]
这个问题还没解决么
