### ISSUE TITLE
使用WeekEndSqls是参数为空的问题。。

### ISSUE THREAD

**Issue by yongjiW** [abel533/Mapper#295]
您好，
    请问下，我在使用 WeekEndSqls 这种写法的时候  遇到一个问题，就是我们传入的参数是可为空的 但是在查询中 生成的sql 里面会出现  ‘select * from user where username = ’ 这种sql 然后就出现错误，请问 这种情况 我是否有好的方法用WeekEndSqls 还是说不能用这个查询 只能用其他方法了吗  谢谢

**Comment by abel533** [comment]
有可能是 bug，我会测试看看
