### ISSUE TITLE
指定列的jdbcType还是报错

### ISSUE THREAD

**Issue by frame-faker** [abel533/Mapper#298]
![image](https://user-images.githubusercontent.com/24647589/40017358-c18b585a-57eb-11e8-94ac-252777051f62.png)
![image](https://user-images.githubusercontent.com/24647589/40017379-cbf01286-57eb-11e8-95da-d320ffc33600.png)

**Comment by frame-faker** [comment]
数据库字段是varchar，模型里面是 String ，无论做什么,加各种主键，删字段,还是报错
'1.5355032596E10' in column '3' is outside valid range for the datatype INTEGER.

**Comment by abel533** [comment]
为什么关闭了？
