### ISSUE TITLE
多sqlSessionFactory可能性

### ISSUE THREAD

**Issue by chinaerserver** [abel533/Mapper#299]
使用框架的时候发现默认只会使用唯一的一个SqlSessionFactory 无论是自己定义的还是@conditiononmissingbean自动注入的，然而在分布式事务的场景下，即使使用AbstractRoutingDataSource，由于SqlSessionFactory会缓存事务第一次使用的数据源，因此导致分布式事务切换数据源失效，进而抛出SQL异常，即不会使用切换过来的数据源配置，具体实验结果可以发现只会使用第一个数据源后续不再改变  详见[](url)http://www.itboth.com/d/2IfMnu/jta-abstractroutingdatasource-spring

因此考虑是否可以支持多SqlSessionFactory的模式 大致思路是在配置文件中指定继承某个特定接口的所有接口均使用同一个SqlSessionFactory ，如果有类似分布式事务需要使用多个SqlSessionFactory则必须指定多个接口

**Comment by chinaerserver** [comment]
@abel533 实验均使用当前最新版本 分布式数据源使用atomikos-starter

**Comment by abel533** [comment]
支持多个 SqlSessionFactory ，也支持动态数据源。。

我在工作中都用过。。

出问题的原因应该是你 mybatis 配置的有问题（还涉及不到mapper）。

一个多 SqlSessionFactory 的例子：https://blog.csdn.net/isea533/article/details/46815385

动态数据源和mapper就没任何关系了，只要动态数据源可以正常用，通用mapper就一定没问题。如果有问题，你可以试试非通用mapper的方法，一样有问题。

**Comment by ioandy** [comment]
@chinaerserver 我也遇到多数据源事务这个问题，照网上资料重写了SqlSessionTemplate, 数据源是切换过来了，但是报这个问题：
Error invoking SqlProvider method (tk.mybatis.mapper.provider.ExampleProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.ExampleProvider 
，我的mapper版本是2.1.5的, 请问你是怎么解决的？

**Comment by ioandy** [comment]
@chinaerserver 我也遇到多数据源事务这个问题，照网上资料重写了SqlSessionTemplate, 数据源是切换过来了，但是报这个问题：
Error invoking SqlProvider method (tk.mybatis.mapper.provider.ExampleProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.ExampleProvider 
，我的mapper版本是2.1.5的, 请问你是怎么解决的？

**Comment by abel533** [comment]
@ioandy 这个错是 Mapper 没有初始化导致的。 wiki faq 有几种情况。
