### ISSUE TITLE
保存或修改时，如果参数内容含$符号，会报错

### ISSUE THREAD

**Issue by 269941633** [abel533/Mapper#30]
保存或修改时，如果参数内容含$符号，会报错
nested exception is org.apache.ibatis.exceptions.PersistenceException: \n### Error updating database.  Cause: java.lang.IllegalArgumentException: Illegal group reference\n### Cause: java.lang.IllegalArgumentException: Illegal group reference

**Comment by abel533** [comment]
什么数据库？能不能提供代码看看？

**Comment by 269941633** [comment]
`public void update(Survey survey) {
		if(StringUtils.isBlank(survey.getId())){
			throw new RuntimeException("id不能为空");
		}
		this.surveyMapper.updateByPrimaryKey(survey);
		
	}`
mysql 数据库

**Comment by abel533** [comment]
某个值中包含 $ ?

**Comment by 269941633** [comment]
是的，比如说保存User，如果name=$。。。。我用的版本是3.3.7的

**Comment by 269941633** [comment]
你那边不能重现吗？

**Comment by abel533** [comment]
测试了，对象某个值包含$没有问题。。你这儿name=$ 是什么意思？直接写在SQL中？

**Comment by 269941633** [comment]
不，不是直接写sql，是一个entity对象，里面某个字段的内容含有$符号的时候，调用通用接口的保存或更新时，都会报错，当去掉$符号的时候，有能正常保存或更新了

**Comment by 269941633** [comment]
难道有哪个配置地方需要配置说明转义的吗？

**Comment by abel533** [comment]
你可以试试Mapper中测试的例子（hsqldb）或者 mybatis.tk 上面spring4的集成项目(mysql)。

**Comment by abel533** [comment]
```
t.m.s.m.C.updateByPrimaryKey             : ==>  Preparing: UPDATE country SET countryname = ?,countrycode = ? WHERE Id = ? 
t.m.s.m.C.updateByPrimaryKey             : ==> Parameters: Australia(String), $U(String), 10(Integer)
t.m.s.m.C.updateByPrimaryKey             : <==    Updates: 1
```

**Comment by 269941633** [comment]
好的，谢谢

**Comment by 269941633** [comment]
`
				
				<bean
					class="com.pubframework.springmybatis.dao.helper.Performance.PerformanceInterceptor">
				</bean>`

找到原因了，是因为加了这个性能分析日志打印导致的，去掉它就正常了

**Comment by shaohui-wang** [comment]
我也是写了个拦截器才出现问题了，感谢楼上

**Comment by 269941633** [comment]
将拦截到的sql这样处理就OK了sql.replaceFirst("\\?", Matcher.quoteReplacement(result));，我完整的拦截器是这样的，这拦截器只是为了打印sql
`package com.fei.springboot.config.dbconfig;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.ibatis.executor.Executor;
import org.apache.ibatis.mapping.BoundSql;
import org.apache.ibatis.mapping.MappedStatement;
import org.apache.ibatis.mapping.ParameterMapping;
import org.apache.ibatis.mapping.ParameterMode;
import org.apache.ibatis.plugin.*;
import org.apache.ibatis.reflection.MetaObject;
import org.apache.ibatis.session.Configuration;
import org.apache.ibatis.session.ResultHandler;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.TypeHandlerRegistry;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.regex.Matcher;

/**
 * MyBatis 将mybatis要执行的sql拦截打印出来
 *
 * @since 1.0.0
 */
@Intercepts
({
        @Signature(type = Executor.class, method = "query", args = {MappedStatement.class, Object.class, RowBounds.class, ResultHandler.class}),
        @Signature(type = Executor.class, method = "update", args = {MappedStatement.class, Object.class})
})
public class SqlPrintInterceptor implements Interceptor {

	private static Log logger = LogFactory.getLog(SqlPrintInterceptor.class);
	
    private static final DateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    @Override
    public Object intercept(Invocation invocation) throws Throwable {
        MappedStatement mappedStatement = (MappedStatement) invocation.getArgs()[0];
        Object parameterObject = null;
        if (invocation.getArgs().length > 1) {
            parameterObject = invocation.getArgs()[1];
        }

        long start = System.currentTimeMillis();

        Object result = invocation.proceed();
        
        String statementId = mappedStatement.getId();
        BoundSql boundSql = mappedStatement.getBoundSql(parameterObject);
        Configuration configuration = mappedStatement.getConfiguration();
        String sql = getSql(boundSql, parameterObject, configuration);

        long end = System.currentTimeMillis();
        long timing = end - start;
        if(logger.isInfoEnabled()){
        	logger.info("执行sql耗时:" + timing + " ms" + " - id:" + statementId + " - Sql:" );
        	logger.info("   "+sql);
        }
       
        return result;
    }

    @Override
    public Object plugin(Object target) {
        if (target instanceof Executor) {
            return Plugin.wrap(target, this);
        }
        return target;
    }

    @Override
    public void setProperties(Properties properties) {
    }

    private String getSql(BoundSql boundSql, Object parameterObject, Configuration configuration) {
        String sql = boundSql.getSql().replaceAll("[\\s]+", " ");
        List<ParameterMapping> parameterMappings = boundSql.getParameterMappings();
        TypeHandlerRegistry typeHandlerRegistry = configuration.getTypeHandlerRegistry();
        if (parameterMappings != null) {
            for (int i = 0; i < parameterMappings.size(); i++) {
                ParameterMapping parameterMapping = parameterMappings.get(i);
                if (parameterMapping.getMode() != ParameterMode.OUT) {
                    Object value;
                    String propertyName = parameterMapping.getProperty();
                    if (boundSql.hasAdditionalParameter(propertyName)) {
                        value = boundSql.getAdditionalParameter(propertyName);
                    } else if (parameterObject == null) {
                        value = null;
                    } else if (typeHandlerRegistry.hasTypeHandler(parameterObject.getClass())) {
                        value = parameterObject;
                    } else {
                        MetaObject metaObject = configuration.newMetaObject(parameterObject);
                        value = metaObject.getValue(propertyName);
                    }
                    sql = replacePlaceholder(sql, value);
                }
            }
        }
        return sql;
    }

    private String replacePlaceholder(String sql, Object propertyValue) {
        String result;
        if (propertyValue != null) {
            if (propertyValue instanceof String) {
                result = "'" + propertyValue + "'";
            } else if (propertyValue instanceof Date) {
                result = "'" + DATE_FORMAT.format(propertyValue) + "'";
            } else {
                result = propertyValue.toString();
            }
        } else {
            result = "null";
        }
        return sql.replaceFirst("\\?", Matcher.quoteReplacement(result));
    }
}
`
