### ISSUE TITLE
update 的时候where后面跟上了我要set的值

### ISSUE THREAD

**Issue by raozhidan** [abel533/Mapper#309]
updateMapper中  通过 updateByPrimaryKey OR updateByPrimaryKeySelective  生成的UPDATE语句 为update xxx set id = id, a =1,b=2 where id =id and a =1 and b =2
这样的update语句并不能更新我的数据啊？？？

**Comment by abel533** [comment]
你实体类为什么不加 `@Id` 注解？没有主键吗？

**Comment by raozhidan** [comment]
哦哦，好的，谢谢
