### ISSUE TITLE
Style属性在Spring集成中该如何使用

### ISSUE THREAD

**Issue by ting4937** [abel533/Mapper#31]
Style是控制驼峰的方法，我看java集成中可以通过Config来设置的，Spring集成该如何设置这个属性的

**Comment by abel533** [comment]
https://github.com/abel533/Mapper/blob/master/wiki/mapper3/2.Integration.md

https://github.com/abel533/Mapper/blob/master/wiki/Changelog.md#320---2015-09-02

style=normal
