### ISSUE TITLE
请问通用Mapper是不是会导致MyBatis的批处理失效呢？

### ISSUE THREAD

**Issue by ghost** [abel533/Mapper#312]
注意我说的MyBatis批量执行，不是foreach遍历执行。即：
```xml
<bean id="sqlSession" class="org.mybatis.spring.SqlSessionTemplate">  
  <constructor-arg name="sqlSessionFactory" ref="sqlSessionFactory" />  
  <constructor-arg name="executorType" value="BATCH" />  
</bean> 
```
我发现我单独使用Mybatis批处理是没问题，与Spring整合也是没问题，但是使用通用Mapper则不行？

发现一个奇怪的问题是，当我把主键（ID）的生成策略中加上【generator = "JDBC"】就没有问题，如：
```java
//如果把【generator = "JDBC"】去掉则批处理失效。
@Id @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "JDBC") private Long id;
```
备注：使用的是MySQL数据库。并且不论我使用【strategy】的值是什么，都没有问题。

另外，QQ群加不进去。

**Comment by Xanthuim** [comment]
发现一个奇怪的问题是，当我把主键（ID）的生成策略中加上【generator = "JDBC"】就没有问题，如：
`
@Id
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "JDBC")
private Long id;
`
如果把【generator = "JDBC"】去掉则批处理失效。

备注：使用的是MySQL数据库。并且不论我使用【strategy】的值是什么，都没有问题。

**Comment by abel533** [comment]
你这说有问题的只是 insert ？
自增时，需要`@GeneratedValue(generator = "JDBC")`，更多方法还可以看文档中的主键策略。

**Comment by Xanthuim** [comment]
只有在批处理的时候才会出现这种问题，普通的insert则没有。
