### ISSUE TITLE
insertSelective为什么插入自动主键

### ISSUE THREAD

**Issue by ww56ww77** [abel533/Mapper#314]

**Comment by ScOrPiOzzy** [comment]
SQLServer数据库，ID自增的情况下？？
我有两个解决办法：
1、使用insertUseGeneratedKeys。
2、使用insert方法，同时指定ID不插入，如：
`    @Column(insertable=false)`
`    private Integer id;`

具体是什么原因还不清楚。目前我是先这样应对这个问题的。希望对你有用

**Comment by JKTerrific** [comment]
我也遇到了这个问题 Mysql下。对主键字段设置了@Id和@GeneratedValue(generator = "JDBC") 。在调用insertSelective仍然会将为null的主键插入

**Comment by abel533** [comment]
楼上说的对。。和数据库有关。
