### ISSUE TITLE
请问如何实现一对多、多对一、一对一级联查询

### ISSUE THREAD

**Issue by Shawn-De** [abel533/Mapper#315]
如题，想直接通过mapper实现级联操作，试过@ManyToOne注解发现没有作用，在文档中也没有发现类似的功能，请问目前是否支持这样的需求？如果支持，该如何操作或配置呢？

**Comment by ScOrPiOzzy** [comment]
来到群里问啊，群里比这里活跃

**Comment by abel533** [comment]
只有单表。。其他的可以自己实现。

**Comment by BaiMingxu** [comment]
为什么加不了群？

**Comment by abel533** [comment]
@BaiMingxu 可以加啊。。mybatis.tk 上面有链接，版本号在这个网站下面也能找到。
