### ISSUE TITLE
关于insertList方法 数据库默认字段为空

### ISSUE THREAD

**Issue by leiyong316** [abel533/Mapper#323]
当数据库有默认值的字段时 , 假如默认0,  int default 0

调用insertList时，默认值是空， 不是0

**Comment by qrqhuang** [comment]
这个insertList 无法解决， 因为其是全字段插入，一定会写入一个值。
可以在实体类上初始默认值  private int xxx = 0;

**Comment by abel533** [comment]
insertList解决不了，但是也没法insertListSelective
