### ISSUE TITLE
加了乐观锁@Version后deleteByPrimaryKey方法执行失败

### ISSUE THREAD

**Issue by maoxinrong** [abel533/Mapper#326]
加了乐观锁@Version后deleteByPrimaryKey方法执行失败，打印日志看到 sql 有个version对应的参数，这个版本号如何传参？

**Comment by maoxinrong** [comment]
是否能够扩展一个deleteByPrimaryKeyAndVersion的方法？

**Comment by abel533** [comment]
删除的时候也需要版本正确才能删除。

**Comment by maoxinrong** [comment]
是的 需要版本，但是deleteByPrimaryKey 方法里没有传递版本参数

**Comment by abel533** [comment]
@maoxinrong 你用的什么版本？最新的肯定支持。

**Comment by abel533** [comment]
新版本所有 delete 都不使用乐观锁作为条件。
