### ISSUE TITLE
MapperScan 无效

### ISSUE THREAD

**Issue by sxm20074428** [abel533/Mapper#328]
import tk.mybatis.spring.annotation.MapperScan;

@SpringBootApplication
//@MapperScan(basePackages = "com.sxm.springboot.mapper")
public class Application implements CommandLineRunner {

报错，找不到mapper

**Comment by maoxinrong** [comment]
需要加@Mapper  比如：

@Mapper
@Repository
public interface xxMapper extends tk.mybatis.mapper.common.Mapper<xx>{

}
