### ISSUE TITLE
保存或修改时，如果参数内容含$符号，会报错，希望尽快解决

### ISSUE THREAD

**Issue by 269941633** [abel533/Mapper#33]
Mysql数据，保存或修改时，如果参数内容含$符号，会报错，希望尽快解决

**Comment by abel533** [comment]
测试了，没有任何问题。

**Comment by 269941633** [comment]
`
				
				<bean
					class="com.pubframework.springmybatis.dao.helper.Performance.PerformanceInterceptor">
				</bean>`

找到原因了，是因为加了这个性能分析日志打印导致的，去掉它就正常了
