### ISSUE TITLE
为什么加不了群？

### ISSUE THREAD

**Issue by BaiMingxu** [abel533/Mapper#332]
我想实现多表操作必须自定义么？

**Comment by abel533** [comment]
mybatis.tk 上面的按钮就能加群。。

多表需要自定义。。建议手写！！！

**Comment by diaodiaofly** [comment]
@abel533 mybatis.tk 上面的按钮就能加群。。
mac  点击上面的按钮加不了群  --    刚提了一个问题  不知道是不是缺陷   - - 帮忙看看呗

**Comment by abel533** [comment]
@diaodiaofly 已经在首页增加QQ号

**Comment by tomgao365** [comment]
![image](https://user-images.githubusercontent.com/13798931/42674838-e27fcdd4-86a3-11e8-849c-c4ddfa9e7a4c.png)
禁止加入了。。。

**Comment by lcstar** [comment]
根据文档使用通用mapper 整合springboot

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true
配置mapper2 进行单元测试 一直报异常 并且在工具包里并没有找到tk.mybatis.mapper.common.Mapper2 这个类

把mapper2删除 就可以进行正常的单元测试 想问下是否是文档写错了？？

**Comment by abel533** [comment]
@tomgao365 不是禁止加入，是群满了。。我看看怎么处理。

**Comment by abel533** [comment]
@tomgao365 可以加群了。

**Comment by tomgao365** [comment]
@abel533 好的，已经恢复了。
