### ISSUE TITLE
请求添加java8 time 包的支持

### ISSUE THREAD

**Issue by adoubee** [abel533/Mapper#333]
<table tableName="user">
            <generatedKey column="id" sqlStatement="JDBC"/>
            <columnOverride column="create_time">
                <property name="property" value="createTime"/>
                <property name="javaType" value="java.time.LocalDateTime"/>
                <property name="jdbcType" value="TIMESTAMP"/>
            </columnOverride>
        </table>
generatorConfig.xml里面的 table 标签里重写字段名无效(如上),
 能否添加对 java8 里新的 time 类型的支持(如使用 java.time.LocalDateTime 替换掉 java.util.Date )

**Comment by ycg000344** [comment]
@wds--moon  你好，不清楚 `columnOverride`这个字段配置在哪个节点下面，能否描述些？或者贴下 `generatorConfig.xml` ？ 谢谢。

**Comment by wds--moon** [comment]
@ycg000344 
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>
    <context id="test" targetRuntime="MyBatis3">


        <property name="autoDelimitKeywords" value="true"/>
        <property name="beginningDelimiter" value="`"/>
        <property name="endingDelimiter" value="`"/>

        <plugin type="tk.mybatis.mapper.generator.MapperPlugin">
            
            <property name="mappers" value="com.shandong.culture.search.common.config.TkMapper"/>
            <property name="caseSensitive" value="true"/>
            <property name="forceAnnotation" value="true"/>
            <property name="beginningDelimiter" value="`"/>
            <property name="endingDelimiter" value="`"/>
        </plugin>
        <plugin type="com.chrm.mybatis.generator.plugins.LombokPlugin" >
            <property name="hasLombok" value="true"/>
        </plugin>
        <commentGenerator>
            
            
            <property name="suppressDate" value="true"/>
            
            <property name="suppressAllComments" value="true"/>
        </commentGenerator>
        
        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://192.168.2.127:3306/culture" userId="root" password="damei2018">
        </jdbcConnection>
        <javaTypeResolver>
            
            <property name="forceBigDecimals" value="false"/>
            
            <property name="useJSR310Types" value="true"/>
        </javaTypeResolver>
        
        <javaModelGenerator targetPackage="com.shandong.culture.search.entity" targetProject="src/main/java"/>
        <sqlMapGenerator targetPackage="com.shandong.culture.search.mapper" targetProject="src/main/resources"/>
        <javaClientGenerator targetPackage="com.shandong.culture.search.mapper" targetProject="src/main/java"
                             type="XMLMAPPER"/>
        <table tableName="t_article" domainObjectName="Article" enableCountByExample="false"
               enableUpdateByExample="false" enableDeleteByExample="false" enableSelectByExample="false"
               selectByExampleQueryId="false">

            
            <property name="useActualColumnNames" value="false"/>
            <generatedKey column="id" sqlStatement="Mysql" identity="true"/>
            
            
            <columnOverride     column="create_time" javaType="java.time.LocalDateTime"   jdbcType="TIMESTAMP" typeHandler="org.apache.ibatis.type.LocalDateTypeHandler"  delimitedColumnName="false" />
            <columnOverride     column="last_update" javaType="java.time.LocalDateTime"   jdbcType="TIMESTAMP" typeHandler="org.apache.ibatis.type.LocalDateTypeHandler"  delimitedColumnName="false" />
        </table>
    </context>
</generatorConfiguration>`

**Comment by ycg000344** [comment]
@wds--moon 感谢，有效。

**Comment by xzour** [comment]
@ycg000344  我也照了这个方法试了,但是无效.
```
<table tableName="res_order_info">
            <generatedKey column="id" sqlStatement="JDBC"/>
            <columnOverride column="date" javaType="java.time.LocalDate" jdbcType="DATE" typeHandler="org.apache.ibatis.type.LocalDateTypeHandler"/>
  </table>
```
```
<xml>
<result column="date" jdbcType="DATE" property="date" typeHandler="org.apache.ibatis.type.LocalDateTypeHandler" />

```
```
Error attempting to get column 'date' from result set.  Cause: java.sql.SQLFeatureNotSupportedException\n; null; nested exception is java.sql.SQLFeatureNotSupportedException",
```
