### ISSUE TITLE
增加时间戳后Example方式查询无结果

### ISSUE THREAD

**Issue by cloudhuang** [abel533/Mapper#334]
为实体增加了一个时间戳字段(createdAt Date)之后，原来正常的通过Example方式查询，变得没有返回结果了，从生成的SQL看，增加了createdAt这个查询参数

> ==> Preparing: SELECT Id,version,created_by,created_date,last_modified_by,last_modified_date,...... FROM user_info WHERE Id = ? AND created_at = ? AND name = ? 
==> Parameters: ef0c8f6197d64a4a8ae3a5a5d26976b4(String), 2018-06-11 18:39:12.421(Timestamp), 测试Example查找(String)

从绑定的参数和debug从对象的值的时间看是一样的，都是 2018-06-11 18:39:12.421(Timestamp)

Mapper Version: 4.0.2
Database: H2 1.4.197

**Comment by IrvingZhao** [comment]
AND created_at = ?   
这个参数设置的到毫秒，你的数据里肯定没有在这个时间点创建的数据，才会出现这个情况的
检查一下，时间戳过滤，是点时间，还是范围时间

**Comment by cloudhuang** [comment]
@IrvingZhao 谢谢回复，这个我是在单元测试里测试的，用的是同一个时间。`AND created_at = ?` 这个是通用Mapper添加的，这里使用的是Example方式的查找。

**Comment by abel533** [comment]
example怎么用的？默认不可能随便加条件。

**Comment by cloudhuang** [comment]
@abel533 
贴出测试的代码，UserInfo表就是一些基本的字段，和时间戳的createdAt，updatedAt字段。
```
    @Test
    @Ignore
    // 通过Example的方式查找，如果有时间戳，查询结果会有问题
    public void findByExample() {
        UserInfo userInfo = new UserInfo();
        userInfo.setName("测试Example查找");
        userInfoMapper.insert(userInfo);

        List<UserInfo> select = userInfoMapper.select(userInfo);
        assertThat(select.size(), is(1));

        UserInfo info = select.get(0);
        assertThat(info.getName(), is("测试Example查找"));
    }
```

**Comment by abel533** [comment]
贴的这段代码根本没有example。。
