### ISSUE TITLE
@column对xml里的sql无效

### ISSUE THREAD

**Issue by 17722623782** [abel533/Mapper#335]
您好，我model的实体类是驼峰的，userName对数据库的user_name，
实体类配置映射@colum(name="user_name")，
在xml里面写了 select * from  t_user，得到的结果 userName为空，请问下通用mapper @Column只对xml外的方法有用吗，xml是不是必须要写resultMap配置关系啊

**Comment by FantaZZ** [comment]
同问

**Comment by cuivip** [comment]
是说这个吗？

mybatis:   
  mapper-locations: classpath*:com/aa/bb/mapper/mapping/*.xml  
  type-aliases-package: com.aa.*.po
  configuration: 
     mapUnderscoreToCamelCase: true

**Comment by 17722623782** [comment]
@cuivip 这个是mybatis自带的，我打开这个会报错，没有继续找原因，你打开这个ok吗

**Comment by abel533** [comment]
如果报错就换 `map-underscore-to-camel-case: true` 试试。

**Comment by 17722623782** [comment]
ok的，报错是我其他的地方出问题了，mapper可以支持默认的驼峰配置，感谢提醒
