### ISSUE TITLE
自定义方法返回null

### ISSUE THREAD

**Issue by silloy** [abel533/Mapper#339]
自定义方法 返回null
`@Mapper
public interface OrderInfoMapper extends BaseMapper<OrderInfo> {
    @Select("select order_info_id, order_id from order_info ")
    List<OrderInfo> selectALLLLLL(Long id);
}`
调用这个方法返回 
![image](https://user-images.githubusercontent.com/12909107/41460425-459ecf1e-70bf-11e8-810c-11150a241fb7.png)

**Comment by abel533** [comment]
你需要手工处理字段映射。。。或者配置mybatis开启自动映射。
