### ISSUE TITLE
使用通用查询时无法找到对应的表名

### ISSUE THREAD

**Issue by suiyueqiannian** [abel533/Mapper#342]
有个奇怪的问题，我在 idea 中使用通过查询没问题，查询时对应的表名会对应到实体类上注解 `@Table(name = 'B_TEST') public class Test{}` 的名称，但是将项目打包时却无法找到注解上的表的名称，打印的sql 查询的表名是 类名的小写 test , 使用的是 tkmapper 4.0.2版本。使用Weekend来查询

**Comment by abel533** [comment]
能不能把Weekend的用法代码贴出来。

**Comment by suiyueqiannian** [comment]
@abel533 我将 spring-devtools 排除掉，将tkmapper 升级到4.0.3就可以了

**Comment by abel533** [comment]
用4.0.3的时候，可以试试恢复devtools。
