### ISSUE TITLE
selectByPrimaryKey根据id主键查询，查询的时候给每个字段赋值了【急】

### ISSUE THREAD

**Issue by diaodiaofly** [abel533/Mapper#343]
我使用的版本是2.0.2
代码如下：
Service：
`public OnlineOrder selectOrderInfo(String id) {
        return onlineOrderMapper.selectByPrimaryKey(id);
    }`

Mapper：
`public interface OnlineOrderMapper extends Mapper<OnlineOrder> {
}`
然而生成查询sql的时候给每个属性都赋值成了id的值，最后导致查询不到结果？

**Comment by abel533** [comment]
你的实体类中没有设置 `@Id`，默认就是所有字段。
