### ISSUE TITLE
mybatis-spring-boot-starter2.0.2版本如何使用二级缓存呢？

### ISSUE THREAD

**Issue by diaodiaofly** [abel533/Mapper#346]
全局开启：<setting name="cacheEnabled" value="true"/>
mapper xml      <cache />

官网说的这个注解@CacheNamespaceRef 再boot版本里面好像没有实现

**Comment by diaodiaofly** [comment]
@abel533   感谢

**Comment by abel533** [comment]
全局配置开启了？单独的文件用注解或者XML配置二级缓存即可。

wiki有详细介绍：https://github.com/abel533/Mapper/wiki/7.1.cache

**Comment by diaodiaofly** [comment]
@abel533 嗯  全局开启    只是文档里面提到的注解在springboot版本里面好像没有    于是我采用mapper xml 原始的标签开启   也没有效果

**Comment by abel533** [comment]
@diaodiaofly 把你所有针对缓存的配置贴出来看看。

**Comment by diaodiaofly** [comment]
这个问题 @CacheNamespaceRef+ 全局二级缓存验证通过  感谢
