### ISSUE TITLE
Mapper 生成的sql 列名不正确。

### ISSUE THREAD

**Issue by sirs05** [abel533/Mapper#35]
为user表创建了一个唯一主键列userid，然而mapper映射出来的sql语句中总是user_id。在任何配置文件中都找不到 user_id这个字段，请问可能是什么原因？？

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'USER_iD' in 'field list'

**Comment by abel533** [comment]
默认驼峰转下划线，看文档。

2016-07-09 10:07 GMT+08:00 sirs05 <notifications@github.com>:

**Comment by sirs05** [comment]
明白了，谢谢
