### ISSUE TITLE
mapperScan 扫描不到子包中的mapper注解？

### ISSUE THREAD

**Issue by lshb** [abel533/Mapper#354]
如题，springboot多模块项目，mapper在一个jar中，mapperscan的项目依赖mapper的jar，启动程序扫描不到mapper，程序不报错，报了一个warn ：ClassPathMapperScanner - No MyBatis mapper was found in '[${mapperscan所在上层包名}]' package. Please check your configuration. 如果我想要能够扫描到mapper要怎么做？

**Comment by lshb** [comment]
已经解决

**Comment by liangerll113** [comment]
为何不把怎么解决的写出来？

**Comment by lshb** [comment]
没必要用mapperscan  用start jar就可以

**Comment by dian884** [comment]
请问在哪个版本解决 这个问题。 现在碰到一样的问题。 在2.0.2中还在

**Comment by abel533** [comment]
这个警告没影响。
