### ISSUE TITLE
generator插件能不能在生成的Model类中加上列名常量定义？

### ISSUE THREAD

**Issue by ljskr** [abel533/Mapper#36]
例如User类有列名id、username等，那么User类里面生成列名的常量定义：
`public class User {
    ......
    static public final String ID = "id";
    static public final String USERNAME = "username";
    ......
}`
这样方便其他地方用到，如Criteria类的方法需要传property，就可以引用这些常量。

或者 是否有其他插件可以实现这个功能？

**Comment by abel533** [comment]
你可以自己写个插件加上。
