### ISSUE TITLE
bug—以下方式即可生成UUID，但是不能回显，就是保存之后不会返回id

### ISSUE THREAD

**Issue by skythinking** [abel533/Mapper#362]
`<table tableName="mp_order_detail">
            <generatedKey column="id" sqlStatement="UUID" identity="false" type="pre" ></generatedKey>
        </table>`
按这种方式配置,可以生成主键,但在保存到数据库以后,返回的主键为null,请问怎么解决?

**Comment by abel533** [comment]
新版本已经没有这种用法了，你可以看看 https://github.com/abel533/Mapper/wiki 中的主键策略。
