### ISSUE TITLE
setCountProperty设置的count属性无用

### ISSUE THREAD

**Issue by mostcool** [abel533/Mapper#363]
` Example e = new Example(Template.class);

e.setCountProperty("crop");

e.createCriteria().andEqualTo("crop", crop);

templateMapper.selectCountByExample(e); `

crop不是Template的主键，主键是templateId

期望生成的语句是：SELECT COUNT(crop) FROM template WHERE ( crop = ? )

但实际生成的语句是：SELECT COUNT(template_id) FROM template WHERE ( crop = ? )

setCountProperty 设置无用？该如何实现呢？

**Comment by abel533** [comment]
4.x 测试没有发现问题，你当初用的什么版本？
