### ISSUE TITLE
tk.mybatis.mapper.annotation.Version注解配合updateByExampleSelective方法使用乐观锁功能时报参数不匹配异常。

### ISSUE THREAD

**Issue by lazyguy21** [abel533/Mapper#365]
tk.mybatis.mapper.annotation.Version注解配合updateByExampleSelective方法使用乐观锁功能时报参数不匹配异常。
```java
default Integer updateByExampleSelectiveWithVersion(T record, Object example) {
    Integer result = updateByExampleSelective(record, example);
    if (result == 0) {
      logger.error("use updateByExampleSelective update failed, record:{},example:{}"
          + "reason may version or id didn't match", record,example);
      throw new ValidateException(ExceptionConstants.DB_OPTIMISTIC_LOCK);
    }
    return result;
  }
```

Caused by: org.apache.ibatis.binding.BindingException: Parameter 'version' not found. Available parameters are [record, param1, example, param2]

**Comment by abel533** [comment]
参考 updateByExampleSelective 方法，给你这个默认方法加上 `@Param` 注解试试。

**Comment by lazyguy21** [comment]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'version' not found. Available parameters are [record, param1, example, param2]
为自己写的default方法加上注解后任然不行

**Comment by lazyguy21** [comment]
updateByExampleSelective这个方法是根据复杂条件更新record实体么，当我的实体里面有一个@Version注解的属性private Long version的时候，（我想使用乐观锁特性）会报错。
      类似的updateByPrimaryKeySelective按照wiki提供的例子封装则可以成功https://github.com/abel533/Mapper/wiki/2.4-version
      而按照wiki的描述updateByExampleSelective应该也能这样实现

**Comment by lazyguy21** [comment]
updateByExampleSelective这个方法是根据复杂条件更新record实体么，当我的实体里面有一个@Version注解的属性private Long version的时候，（我想使用乐观锁特性）会报错。
      类似的updateByPrimaryKeySelective按照wiki提供的例子封装则可以成功https://github.com/abel533/Mapper/wiki/2.4-version
      而按照wiki的描述updateByExampleSelective应该也能这样实现

**Comment by lazyguy21** [comment]
updateByExampleSelective这个方法是根据复杂条件更新record实体么，当我的实体里面有一个@Version注解的属性private Long version的时候（我想使用乐观锁特性）会报错。
      类似的updateByPrimaryKeySelective按照wiki提供的例子封装则可以成功https://github.com/abel533/Mapper/wiki/2.4-version
      而按照wiki的描述updateByExampleSelective应该也能这样实现
