### ISSUE TITLE
updateByPrimaryKeySelective更新无效

### ISSUE THREAD

**Issue by smile-everyday** [abel533/Mapper#367]
调用此方法未报错，返回-1，数据库也没更改成功，排查了一早上没找到原因，下午重新试了一下什么都没改，发现可以成功修改数据库了，求解惑！！！

**Comment by zlren** [comment]
兄弟，你有这个问题吗？https://github.com/abel533/Mapper/issues/364

**Comment by smile-everyday** [comment]
@zlren 对啊

**Comment by smile-everyday** [comment]
@abel533 有的，sql打印出来也是正常的，弄了一早上，到下午就自动好了
