### ISSUE TITLE
怎么实现的一个方法根据不同的业务操作不同的表？

### ISSUE THREAD

**Issue by zou33** [abel533/Mapper#369]
怎么实现的一个方法根据不同的业务操作不同的表？

**Comment by zou33** [comment]
怎么实现的一个方法根据不同的业务操作不同的表？

**Comment by zou33** [comment]
公司有个项目，用了通用mapper，
Transaction类上有注解@Table(name = "tb_transaction")

public int update(Transaction transaction) {
        return transactionMapper.updateByPrimaryKey(transaction);
   }
但是我们数据库没有tb_transaction这个表，有tb_transaction_a，tb_transaction_b这样的表，但是a业务调这个update会去更新tb_transaction_a表，b业务调这个update会去更新tb_transaction_b表。
我现在不明白的是，这个是怎么实现的？

**Comment by abel533** [comment]
@zou33 通用mapper支持动态表名。

**Comment by zou33** [comment]
它是根据什么条件去生成的不同的表名，使其支持动态表名？能贴下代码嘛

**Comment by zou33** [comment]
比如我现在新增一个tb_transaction_c表，我怎么样才能让业务去查询的是tb_transaction_c这个表呢？
public int update(Transaction transaction) {
return transactionMapper.updateByPrimaryKey(transaction);
}
要在Transaction 这个类里面，做什么呢？

**Comment by somewhater** [comment]
1：给个@Table注解，给个默认的表名，不写也可以，但是要驼峰转下划线匹配
@Table(name = "conf_default")
2：添加非表字段参数，用于接受动态表名参数
@Transient//声明非数据库字段
    private String tableName;
3：实现接口IDynamicTableName，实现如下方法，2中的属性是为了给这个东西
public String getDynamicTableName() {
        return tableName;
    }
4：使用如下方式动态查询表
 Condition condition = new Condition(ConfDefault.class);
        condition.setTableName("conf");//动态配置表明
        condition.createCriteria().andCondition("`key` like '%1%'").andCondition("`value` like '%1%'");
        condition.setOrderByClause("`key` desc");
        List<ConfDefault> list = confDefaultMapper.selectByExample(condition);
生成的sql就是这样了：
 SELECT module,`key`,`value`,`desc` FROM conf WHERE ( `key` like '%1%' and `value` like '%1%' ) order by `key` desc

**Comment by qxwei** [comment]
> 1：给个@table注解，给个默认的表名，不写也可以，但是要驼峰转下划线匹配
> `@Table(name = "conf_default")`
> 2：添加非表字段参数，用于接受动态表名参数
> `@Transient`//声明非数据库字段
> `private String tableName;`
> 3：实现接口IDynamicTableName，实现如下方法，2中的属性是返回表名
> 
> ```
> public String getDynamicTableName() {
>        return tableName;
> }
> ```
> 源码中这样说的：
> 
> ```
> /**
>  * 实现动态表名时，实体类需要实现该接口
>  *
>  * @author liuzh
>  * @since 2015-10-28 22:20
>  */
> public interface IDynamicTableName {
> 
>     /**
>      * 获取动态表名 - 只要有返回值，不是null和''，就会用返回值作为表名
>      *
>      * @return
>      */
>     String getDynamicTableName();
> }
> ```
> 4：使用如下方式动态查询表
> 
> ```
> Condition condition = new Condition(ConfDefault.class);
> condition.setTableName("conf");//动态配置表明
> condition.createCriteria().andCondition("`key` like '%1%'").andCondition("`value` like '%1%'");
> condition.setOrderByClause("`key` desc");
> List<ConfDefault> list = confDefaultMapper.selectByExample(condition);
> ```
> 生成的sql就是这样了：
> 
> ```
> SELECT module,`key`,`value`,`desc` FROM conf 
> WHERE ( `key` like '%1%' and `value` like '%1%' ) order by `key` desc
> ```

完美解决，谢谢。
