### ISSUE TITLE
如何支持Mysql Json字段？

### ISSUE THREAD

**Issue by maobole** [abel533/Mapper#371]

**Comment by SonicWW** [comment]
同问

**Comment by abel533** [comment]
能不能提供一个mybatis用json的例子给我参考看看？

**Comment by fnwib** [comment]
可以使用typeHandler手动处理一下

**Comment by SonicWW** [comment]
在对象中使用@ColumnType(typeHandler = UserAttributeTypeHandler.class)
再写一个UserAttributeTypeHandler类
public class UserAttributeTypeHandler extends JsonTypeHandler<User.Attribute> {
    public UserAttributeTypeHandler(Class<User.Attribute> clazz) {
        super(clazz);
    }
}
