### ISSUE TITLE
请问delete方法返回的int是什么？

### ISSUE THREAD

**Issue by tcsx** [abel533/Mapper#375]
> /**
     * 根据实体属性作为条件进行删除，查询条件使用等号
     *
     * @param record
     * @return
     */
    @DeleteProvider(type = BaseDeleteProvider.class, method = "dynamicSQL")
    int delete(T record);

> 
    /**
     * 根据主键字段进行删除，方法参数必须包含完整的主键属性
     *
     * @param key
     * @return
     */
    @DeleteProvider(type = BaseDeleteProvider.class, method = "dynamicSQL")
    int deleteByPrimaryKey(Object key);

另外insert时如果主键为空会怎么样？会自动变成update吗？类似insertOrUpdate的机制？

**Comment by cuivip** [comment]
关于delete的那个问题，你自己试下不就知道了？是删除的记录条数。
被insert的对象可以指定主键策略，你好像没好好看文档。
`
     @Id
     @KeySql(genId = GeneratorUUID.class)
     private String userId;
`
这样的问题看wiki就好了

**Comment by cuivip** [comment]
你的意思是不通过主键如何更新？可以用updatebycondition

**Comment by tcsx** [comment]
嗯，我知道updatebycondition。我的意思是判断主键在数据库中已经存在则进行更新，如果没有主键不存在就执行插入，类似hibernate种的saveOrUpdate(). 好像还没有这种接口。

**Comment by abel533** [comment]
MYSQL能实现这种通用方法。
