### ISSUE TITLE
编写wiki使用相对路径

### ISSUE THREAD

**Issue by jianghuzai** [abel533/Mapper#376]
目前想里面的md文件，在链接到其他文件时，全都是用了外链。

这样我想看某一个版本的wiki时，都无法跳转来看，一点，就跳到最新版的wiki，，，报个404出来，超级不方便。

如果使用相对路径，我clone下来，切换到某个版本，点wiki的链接就不会出现上面的困扰了。

之前用了mapper3，觉得tkmapper真的方便，现在想用发现直接到4了，，，，而4的文档，有这么简洁…
那个通用接口大全不见了，，，，，

**Comment by abel533** [comment]
https://mapperhelper.github.io/all/

**Comment by jianghuzai** [comment]
@abel533 这个好， 我还在想，怎么把接口文档给撤掉了，，，谢谢大神
