### ISSUE TITLE
mysql 配置问题

### ISSUE THREAD

**Issue by LIANGQI0811** [abel533/Mapper#378]
我已经指定了
    DENTITY: MYSQL
但是还是报错了
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: ARTICLES in statement [select * from articles where id = 1]
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: ARTICLES in statement [select * from articles where id = 1]
后面还有一大堆 org.hsqldb.jdbc包下的错误，我该怎么办？

**Comment by abel533** [comment]
找不到表 ARTICLES
