### ISSUE TITLE
有时，当表中某个字段的值为null时，会出现部分字段数据丢失问题

### ISSUE THREAD

**Issue by fssgh** [abel533/Mapper#379]
有时，当表中某个字体为null时，会出现部分字段数据丢失问题？
mapper V4.0.2/V4.0.3;
mybatis V3.4.6;
有谁遇到过吗？是什么问题呢？

**Comment by abel533** [comment]
看不懂你说的。

**Comment by fssgh** [comment]
@abel533 谢谢大神，留言！是这样，一个表中的字段名，有的有下划线，有的没有下划线，有多个byte[]类型的字段，当表中某个没有下划线字段值为null时，查询表的所有字段数据时会出现部分字段数据丢失（查询结果字段值为null,实际数据库中对应的字段是有值的）。是什么问题导致的呢？

**Comment by abel533** [comment]
是不是你查询列和类字段映射的问题？最好贴个类的代码和你查询方法的SQL

**Comment by abel533** [comment]
看不出来什么问题。

查询有问题时的SQL日志有吗？

**Comment by fssgh** [comment]
我更新spring boot 到2.0.5 和spring 到 5.0.9后，问题就不存在了。。。。
