### ISSUE TITLE
select方法报错

### ISSUE THREAD

**Issue by initeasylife** [abel533/Mapper#38]
ProviderSqlSource.class
85行  sql = (String) providerMethod.invoke(**providerType.newInstance()**, parameterObject);

BaseSelectProvider.class中没有空的构造函数，无法实例化

**Comment by abel533** [comment]
这不是bug，是你通用方法没有初始化造成的，看文档配置好就行。

2016-07-19 17:26 GMT+08:00 initeasylife <notifications@github.com>:

**Comment by initeasylife** [comment]
我没有配置spring，只是单纯地当做一个orm框架在用
    String resource = "com/spd/conf.xml";
    InputStream is = Resources.getResourceAsStream(resource);
    SqlSessionFactory sessionFactory = new
SqlSessionFactoryBuilder().build(is);
    SqlSession sqlSession = sessionFactory.openSession();
    CountryMapper mapper = sqlSession.getMapper(CountryMapper.class);
    List<Eleme> countryList = mapper.select(new Eleme());


配置文件如下
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN" "
http://mybatis.org/dtd/mybatis-3-config.dtd">
    <configuration>
        <environments default="development">
            <environment id="development">
                <transactionManager type="JDBC" />
                
                <dataSource type="POOLED">
                    <property name="driver" value="com.mysql.jdbc.Driver" />
                    <property name="url"
value="jdbc:mysql://localhost:3306/eleme" />
                    <property name="username" value="root" />
                    <property name="password" value="root" />
                </dataSource>
            </environment>
        </environments>
        <mappers>
 <mapper class="com.spd.task.CountryMapper" />
</mappers>
    </configuration>

2016-07-19 22:39 GMT+08:00 Liuzh <notifications@github.com>:

**Comment by abel533** [comment]
参考文档中java注册通用Mapper的方法。

**Comment by initeasylife** [comment]
是我看文档不仔细，打扰了

2016-07-20 15:58 GMT+08:00 Liuzh <notifications@github.com>:
