### ISSUE TITLE
枚举类型处理

### ISSUE THREAD

**Issue by xiaobzhou** [abel533/Mapper#380]
博主，枚举类型处理的时候有没有扩展点，现在的版本可以通过@ColumnType来指定，但是太麻烦，在解析时遇到枚举有没有预留扩展点 通过自己的来找TypeHandler 找不到在通过@ColumnType获取

**Comment by abel533** [comment]
这个逻辑在 mybatis 中，可以看看能不能扩展 mybatis 实现。
