### ISSUE TITLE
使用@Version乐观锁时，执行UpdateByExample报BindingException: Parameter 'version' not found

### ISSUE THREAD

**Issue by ztyzbb** [abel533/Mapper#385]
错误信息：
`org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.binding.BindingException: Parameter 'version' not found. Available parameters are [record, param1, example, param2]`
动态SQL（部分简化了一下，这里是UPDATE table SET后面的部分）：
`a= a,b= #{record.b},c= #{record.c},version = ${@tk.mybatis.mapper.version.VersionUtil@nextVersion(@tk.mybatis.mapper.version.DefaultNextVersion@class, version)},`
可以看到前面的值都用record.打头，version没有，导致表达式解析失败，翻了一下源码，对应的位置在tk\mybatis\mapper\mapperhelper\SqlHelper.class的471行，应为
`.append(entityName).append('.').append(column.getProperty()).append(")},");`
麻烦检查一下，这是一个Bug，还是使用方法的错误？
此外，deleteByPrimaryKey的乐观锁似乎有问题，调用deleteByPrimaryKey("111")时，生成的SQL为WHRER id='111' AND version='111'，很明显在ByPrimaryKey系列的方法中，插件并没有办法获取version的值，是否应该删除这些方法的乐观锁支持？

**Comment by ztyzbb** [comment]
core\src\main\java\tk\mybatis\mapper\entity\EntityColumn.java第75行注释应为`返回格式如:colum = #{entityName.age,jdbcType=NUMERIC,typeHandler=MyTypeHandler}`少了一个entityName.

**Comment by ztyzbb** [comment]
尝试修复了BindingException，但似乎UpdateByExample和UpdateByExampleSelective并没有在WHERE条件中加入乐观锁的字段，只有来自Example的Where。
另外发现一个问题，我把deleteByPrimaryKey的Object key换成T record，无法编译，看源码deleteByPrimaryKey似乎可以只传主键或传整个实体对象，但只传主键且实体上有乐观锁字段时，会导致上面我最早发的问题，生成的SQL为WHRER id=#{id} AND version=#{id}

**Comment by JiangYongKang** [comment]
`deleteByPrimaryKey` 只传主键的确会加上乐观锁条件。
它的实现代码是这样的：
```java
    /**
     * 通过主键删除
     *
     * @param ms
     */
    public String deleteByPrimaryKey(MappedStatement ms) {
        final Class<?> entityClass = getEntityClass(ms);
        StringBuilder sql = new StringBuilder();
        sql.append(SqlHelper.deleteFromTable(entityClass, tableName(entityClass)));
        //增加 @Version 乐观锁支持
        sql.append(SqlHelper.wherePKColumns(entityClass, true));
        return sql.toString();
    }
```
通过这个方法生成的SQL语句有点问题：
```java
mapper.deleteByPrimaryKey(100);
```
```console
==>  Preparing: DELETE FROM users WHERE id = ? AND lock_version = ? 
==> Parameters: 100(Integer), 100(Integer)
<==    Updates: 0
```
我觉得按主键进行删除的话，不必判断一下乐观锁字段吧？

**Comment by yangdq1** [comment]
今天升级到最新版本，发现删除没有乐观锁了，之前传ID也会添加乐观锁字段确实不合理，但是能否保留传对象仍进行乐观锁校验的功能，或者添加一个可配置项，业务上还是有这种要求的，谢谢

**Comment by abel533** [comment]
update Example相关方法都是批量操作，不适合用乐观锁进行控制。
