### ISSUE TITLE
实体类中Blob类型报错

### ISSUE THREAD

**Issue by initeasylife** [abel533/Mapper#39]
mybatis源码中TypeHandlerRegistry.class中register了
register(JdbcType.LONGVARBINARY, new BlobTypeHandler());
register(JdbcType.BLOB, new BlobTypeHandler());

但是我实体类中定义
Blob test;
test的type是interface java.sql.Blob或者class com.mysql.jdbc.Blob
而不是Blob
会导致java.lang.IllegalStateException: No typehandler found for property test

**Comment by abel533** [comment]
Blob对应的java类型为byte[]
