### ISSUE TITLE
InsertProvider拼接dynamicSQL不支持<selectKey>标签

### ISSUE THREAD

**Issue by JiangWen002** [abel533/Mapper#394]
数据库类型：Oracle 
自定义的InsertProvider中拼接动态sql,不支持<selectKey>标签
 ibatis.builder.buildException解析报错
Unknown element \<selectKey\> in SQLstatement
请问这是正常的吗？如何解决

**Comment by somewhater** [comment]
insert方法直接返回主键塞到了入参中，直接取entity.get主键就行了。

**Comment by JiangWen002** [comment]
@somewhater 不好意思 忘记说数据库类型了 我的是Oracle 是不支持自增主键的 必须采用selectKey

**Comment by abel533** [comment]
就是不支持，所以通用mapper中额外处理的。

如果你写的通用Mapper扩展，你可以看看这个类：https://github.com/abel533/Mapper/blob/master/core/src/main/java/tk/mybatis/mapper/mapperhelper/SelectKeyHelper.java
