### ISSUE TITLE
spring-boot中启动后，getEntityTable为null

### ISSUE THREAD

**Issue by shen0834** [abel533/Mapper#40]
EntityTable entityTable = entityTableMap.get(entityClass);
        if (entityTable == null) {
            throw new RuntimeException("无法获取实体类" + entityClass.getCanonicalName() + "对应的表名!");
        }

能否解决下，在热部署(restart classLoader)的状态下，entityTable是null的情况？

**Comment by abel533** [comment]
不支持热部署。

**Comment by shen0834** [comment]
顺便问下，mapper有防止sql injection的措施吗？
