### ISSUE TITLE
IdListMapper 启动检测约束条件太强

### ISSUE THREAD

**Issue by cuivip** [abel533/Mapper#401]
自己写的统一接口中继承了 IdListMapper ，导致无法启动。
Invocation of init method failed; nested exception is tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: tk.mybatis.mapper.MapperException: 继承 ByIdList 方法的实体类[com.opespro.admin.po.SysCode]中必须只有一个带有 @Id 注解的字段

实际使用中，弄了个大接口:
`
public interface IMapper<T> extends BaseMapper<T>, ConditionMapper<T>,ExampleMapper<T>,IdListMapper<T, String>{}
`
系统中大多数情况下，表都是单主键的，所有都继承 IMapper 是没有问题，但是也有例外情况，多主键的情况。这时就会导致系统无法启动。
是否可以将异常抛出的时间点后置到 具体方法调用的时候呢？
我现在倒是通过分配不同的接口处理了该问题，但是感觉方案太繁琐，如果后置的话，就简洁多了。

**Comment by abel533** [comment]
运行时出错就是隐藏的大bug了。
