### ISSUE TITLE
支持Lombok的实体Bean的生成

### ISSUE THREAD

**Issue by nettm** [abel533/Mapper#402]
目前生成的实体Bean都有set和get方法，能否提供一个plugin，支持生成Lombok的实体Bean呢，因为目前使用Lombok也比较多，如果生成后自己去改的话也比较麻烦，谢谢！

**Comment by nettm** [comment]
可以参考一下：https://github.com/softwareloop/mybatis-generator-lombok-plugin 项目

**Comment by nettm** [comment]
如果生成的实体Bean有继承基类的话，需要添加Lombok的@EqualsAndHashCode(callSuper = true)注解

**Comment by abel533** [comment]
和通用 Mapper 可以直接集成吗？

**Comment by nettm** [comment]
需要自己写plugin实现吧，集成很容易。

**Comment by qrqhuang** [comment]
关联 #296  已实现
