### ISSUE TITLE
是否有使用ID注解得情况下，不配置ID生成规则，而使用我自己set得字段

### ISSUE THREAD

**Issue by weixuedong** [abel533/Mapper#403]
是否有使用ID注解得情况下，不配置ID生成规则，而使用我自己set得字段。
用@Id因为我这边还有其他关于id得通用化方法，但是不想用任何策略空指ID 只想用我自己set的

**Comment by miaogr86** [comment]
可以的

**Comment by cuivip** [comment]
不配置 @KeySql 不就可以了

**Comment by abel533** [comment]
不配置任何主键策略即可。。也别用自增专用的插入方法。
