### ISSUE TITLE
SqlServer的id自增问题

### ISSUE THREAD

**Issue by jwang0512** [abel533/Mapper#408]
之前一直用mysql没有问题，最近用到sqlserver出现一些问题，
配置项已设置了mapper.identity=SQLSERVER
求解决方案。以表a为例，表a中含有自增主键f1,和其他字段f2。f1的实体类属性设置了@Id @KeySql(useGeneratedKeys = true)
问题1:
insertSelective方法会将自增id字段写入SQL语句，INSERT a(f1,f2) VALUES(NULL,'aaa')。这时sqlserver报错：无法更新标识列 'f1'。sqlserver不允许给自增主键写值。

通过给f1设置@Column(insertable = false)后可以解决，但：

问题2:
updateByPrimaryKeySelective方法也会将自增id字段写入SQL语句，UPDATE a  SET f1 = f1,f2 = ? WHERE  f1 = ?。这时sqlserver报错：无法更新标识列 'f1'。sqlserver不允许给自增主键写值。

是不是在insert或者update中去掉useGeneratedKeys的@id字段对数据库的适应性更好？

或者我理解有问题？求解决方案

**Comment by miaogr86** [comment]
问题2：f1字段上加注解@javax.persistence.Column(updatable="false")

**Comment by jwang0512** [comment]
@miaogr86 可以这么操作，但这样是不是把简单的问题复杂化了呢。SET f1=f1，这样的语句是不是没必要？@abel533

**Comment by miaogr86** [comment]
个人感觉修改主键完全没有必要，而且有些数据库还不支持

**Comment by abel533** [comment]
f1=f2 是为了防止出现 `set where` 中间缺东西导致语法错误。

**Comment by superlee9527** [comment]
@jwang0512 我这边设置id为@column(insertable = false)
但是插入后id无法回传了，sqlserver要怎么配置？我的IdentityDialect设置的是sqlserver

**Comment by superlee9527** [comment]
@abel533 
我设置为Jdbc3KeyGenerator也不行，没有主键回传

**Comment by superlee9527** [comment]
但是很奇怪，我这边设置为sqlserver IdentityDialect，无法回传的
我该用Jdbc3KeyGenerator就能拿到回传的id了

**Comment by abel533** [comment]
set id = id 功能会在 4.1.1 版本去掉。
