### ISSUE TITLE
数据库pg动态序列名怎么实现

### ISSUE THREAD

**Issue by qxwei** [abel533/Mapper#409]
使用pg数据库，由于表会重建，字段一样的，序列名称不一样，
主键注解如下：
`@ld
@Column(name = "pool_id")
@GeneratedValue(strategy= GenerationType.IDENTITY,generator= "SELECT nextval('fbc_pool_ pool_ id_ seq')")
private Long poolld;`

现在需要动态修改fbc_pool_ pool_ id_ seq 为fbc_pool_2_ pool_ id_ seq，试过修改注解无效，元数据貌似在启动的时候在entityhelper缓存了，请作者不吝赐教。

**Comment by qrqhuang** [comment]
通过serial4建的表，其主键会被自动更新。
insert的时候直接忽略该字段交由DB插入即可
`  @Column(insertable=false)`
