### ISSUE TITLE
selectOne() 不返回主键？

### ISSUE THREAD

**Issue by shoo-be-doo** [abel533/Mapper#41]
selectOne() 是本来就不返回主键，还是说我的配置有问题？

**Comment by abel533** [comment]
所有列都查。

**Comment by shoo-be-doo** [comment]
找到原因了，是我的问题，Model 的 JPA 注解配置写在 getter 方法上了，应该写在字段声明上。

**Comment by abel533** [comment]
方法声明也支持，需要配置一个参数开启。
