### ISSUE TITLE
怎样通过mybatis generator自动添加乐观锁注解@Version

### ISSUE THREAD

**Issue by tastypinenut** [abel533/Mapper#414]
https://github.com/abel533/Mapper/wiki/2.4-version
这个文档有介绍@Version注解用于乐观锁，但怎样可以通过mybatis generator自动为Entity类添加乐观锁注解呢？

**Comment by cuivip** [comment]
自己写套代码生成器吧

**Comment by tastypinenut** [comment]
> 自己写套代码生成器吧

如果有的话，就不用自己重复造轮子了

**Comment by tastypinenut** [comment]
@abel533 是否可以考虑增加配置，可以指定并添加乐观锁注解到entity类，不然手动修改后很容易不小心被再次生成的代码覆盖

**Comment by abel533** [comment]
@tastypinenut 有个简单快捷的方式，如果有一批表都有乐观锁，并且名字一样。。就可以增加一个 rootClass，在基类（可以包含主键和乐观锁等公共字段）中配置好注解。生成代码时会自动继承。

**Comment by abel533** [comment]
@tastypinenut 详细看 Mybatis Geneator 详解 http://blog.csdn.net/isea533/article/details/42102297

当类型定义完全相同的时候，不会生成父类中的字段，除非有不同的地方！

rootClass:设置所有实体类的基类。如果设置，需要使用类的全限定名称。并且如果MBG能够加载rootClass，那么MBG不会覆盖和父类中完全匹配的属性。匹配规则：

- 属性名完全相同
- 属性类型相同
- 属性有getter方法
- 属性有setter方法
