### ISSUE TITLE
请问weekend 可以和 Example.Criteria 互转么

### ISSUE THREAD

**Issue by guan25** [abel533/Mapper#418]
斜体部分想替换成weekend形式实现，其他部分代码尽量不动（因为是框架老代码）。请问可以实现么

Example example = new Example(poClass);
Example.Criteria criteria = example.createCriteria();
...
_**Example.Criteria criteria1 = example.createCriteria();
criteria1.andCondition("....");
example.and(criteria1);**_

...
List<C> list = mapper.selectByExample(example);

**Comment by abel533** [comment]
可以，weekend 最终生成的也是 Example。
