### ISSUE TITLE
IDynamicTableName不支持

### ISSUE THREAD

**Issue by programmer-luxw** [abel533/Mapper#419]
IDynamicTableName不生效，看了下DefaultEntityResolve类的源码，没有通过反射获取动态表的名字

**Comment by abel533** [comment]
动态表名在 XML 中获取的。在 SqlHelper 中。

**Comment by programmer-luxw** [comment]
> 动态表名在 XML 中获取的。在 SqlHelper 中。

我需要解决的场景是这样的：每个用户（可能很多）都有自己单独的数据库，但是里面的表都是一样的，
如果用原始的mybatis框架，我只需要把 ${数据库名字.表名}传参数到xml里面即可。但是我想要用Mapper框架直接进行curd操作,不想写XML，我本来想是实体类实现IDynamicTableName接口里面的方法，返回${数据库名字.表名}这个数据库+表名 字符串，Mapper框架会在不需要XML的时候 ，自己去拼接这个数据库+表名 的字符串 作为SQL语句 from 后面的表名子。不过框架好像现在还不支持这种形式。

**Comment by programmer-luxw** [comment]
> 动态表名在 XML 中获取的。在 SqlHelper 中。

在DefaultEntityResolve里面解析TableName的时候，是否可以判断是否实现了IDynamicTableName接口的方法，如果实现了则获取这个动态的表名。

**Comment by abel533** [comment]
DefaultEntityResolve这是初始化，和运行时不一样。

注意看这里：https://github.com/abel533/Mapper/blob/master/core/src/main/java/tk/mybatis/mapper/mapperhelper/SqlHelper.java#L50

```java
sql.append("<choose>");
            sql.append("<when test=\"@tk.mybatis.mapper.util.OGNL@isDynamicParameter(_parameter) and dynamicTableName != null and dynamicTableName != ''\">");
            sql.append("${dynamicTableName}\n");
            sql.append("</when>");
            //不支持指定列的时候查询全部列
            sql.append("<otherwise>");
            sql.append(tableName);
            sql.append("</otherwise>");
            sql.append("</choose>");
```

运行时判断的。
