### ISSUE TITLE
SpecialProvider没有newInstance方法，导致@MybatisTest注解时报错

### ISSUE THREAD

**Issue by cao2358** [abel533/Mapper#420]
通过@MybatisTest注解配合@AutoConfigureTestDatabase注解写单元测试时，报错。报错原因是：java.lang.NoSuchMethodException: tk.mybatis.mapper.provider.SpecialProvider.<init>()
断点调试进取发现该provider没有实现newInstance方法导致的

**Comment by abel533** [comment]
说明 Mapper 配置没有生效。
