### ISSUE TITLE
insertListMapper 的主键属性必须叫id吗？可以自定义吗？

### ISSUE THREAD

**Issue by qxwei** [abel533/Mapper#422]
insertListMapper 的主键属性必须叫id吗？可以自定义吗？

**Comment by abel533** [comment]
看方法注释：https://github.com/abel533/Mapper/blob/master/base/src/main/java/tk/mybatis/mapper/common/special/InsertListMapper.java

**Comment by qxwei** [comment]
看到了，已处理。

**Comment by abel533** [comment]
4.1.x 以后版本不需要在指定改名字。不必叫 `id`。
