### ISSUE TITLE
通用mapper是否支持association功能?

### ISSUE THREAD

**Issue by liudaomanbu** [abel533/Mapper#431]
单表CRUD是通用Mapper提供的时,能做到类似association的效果吗?
一个A表中,有2.3个字段实际上是一个对象.
比如说A表中有三个字段为地区code,地区全称,地区简称.
然后因为实际上这三个字段是一个地区对象,有对应的地区类,里面封装了方法.
所以我希望A表对应的Bean中没有这三个字段的属性,而是直接有一个地区对象的属性.
这个地区对象才是有这三个属性.
这种在原生mybatis中可以使用xml中resultMap的association来实现.

通用mapper中该如何实现?

**Comment by abel533** [comment]
不支持，除非自己扩展。

**Comment by liudaomanbu** [comment]
> 不支持，除非自己扩展。

请问有支持的计划吗?
如果要自己扩展,要从哪方面入手?
