### ISSUE TITLE
数据库为PostgreSQL，通用方法updateByPrimaryKey*的where条件过多，更新不成功

### ISSUE THREAD

**Issue by hideondeveloper** [abel533/Mapper#434]

**Comment by qrqhuang** [comment]
不成功有什么错误信息吗
能把生成的sql发出来看下？
你这样的提问，别人怎么帮你看

**Comment by hideondeveloper** [comment]
> 不成功有什么错误信息吗
> 能把生成的sql发出来看下？
> 你这样的提问，别人怎么帮你看

抱歉，忘记加sql语句了，就是控制台打印的内容是数据库所有的字段都在where条件后面，然后我更换数据源为mysql数据库，可以成功更新，where条件后面只有表的主键

**Comment by abel533** [comment]
你没有 `@Id` 注解，这种情况下，默认所有字段作为联合主键。
