### ISSUE TITLE
全局配置useGeneratedKeys后， update语句于oracle中均报错

### ISSUE THREAD

**Issue by qrqhuang** [abel533/Mapper#435]
之前有个版本中更新日志：

update 上面的 @Options 注解在 3.2.x 版本时会影响清空二级缓存，已经去掉该注解

` @Options(useCache = false, useGeneratedKeys = false)`

但去掉该注解后，oracle update 方法都会报错。需要回归。。

具体报错信息同该网站一致：

[Mybaties Update 不允许的操作 ](https://ask.csdn.net/questions/167655)

**Comment by qrqhuang** [comment]
有配置全局主键生成策略
`mybatis-config`
`<setting name="useGeneratedKeys" value="true" />`

**Comment by abel533** [comment]
useGeneratedKeys 在任何情况下都不适用于 Oracle 数据库。。关了吧。

**Comment by qrqhuang** [comment]
@abel533 insert适用呀， 可以回写
