### ISSUE TITLE
自定义的注解查询下划线字段无法转换成驼峰类型

### ISSUE THREAD

**Issue by yukihosoul** [abel533/Mapper#437]
`@Select("SELECT id,product_id FROM activity ")`
用自定义的注解查询出来的没有下划线的字段(product_id )，只有id，
我设置了style为camelhump也没有作用，请问如何解决呢？

**Comment by abel533** [comment]
手写SQL需要自己处理映射。。

下划线和驼峰的可以配置 mapUnderscoreToCamelCase
