### ISSUE TITLE
连续插入数据，id重复问题

### ISSUE THREAD

**Issue by lslkk** [abel533/Mapper#447]
![default](https://user-images.githubusercontent.com/20640759/47976168-2441dd00-e0ec-11e8-9997-6836c24a5211.png)
![default](https://user-images.githubusercontent.com/20640759/47976204-50f5f480-e0ec-11e8-9a62-1ea09c69e446.png)
![default](https://user-images.githubusercontent.com/20640759/47976229-666b1e80-e0ec-11e8-9bc4-ff796b9ec4b5.png)
![default](https://user-images.githubusercontent.com/20640759/47976306-c792f200-e0ec-11e8-9f71-c27d8005c2b1.png)

如上图所示，在连续使用insert时，第一条数据能成功插入，但是第二条数据不能插入，这边提示是主键问题。策略的话，配置的是自增策略。测试了多次，每次都是第一次能成功插入，但第二条就提示主键重复

**Comment by abel533** [comment]
你插入的是同一个对象吧，第一次插入后，主键就回写了。再插入肯定重复！

**Comment by lslkk** [comment]
![default](https://user-images.githubusercontent.com/20640759/48296400-4ca54f00-e4d1-11e8-8698-4b040ddfb385.png)
不是同一个对象，同一个对象的话，肯定就没有问题了啊。我这边采用的是配置jpa自动建表配置mybatis使用。 想请问一下mybatis的自增策略是否和这个冲突呢？

**Comment by lslkk** [comment]
通过mapper判断两个对象是否相等的依据是什么呢？是必须要重写PO里的equals和hashCode方法吗
