### ISSUE TITLE
通用 Mapper 专用代码生成器生成疑问

### ISSUE THREAD

**Issue by grath10** [abel533/Mapper#449]
generatorConfig.xml配置文件中如下配置：

`<table tableName="%">`
 ` <generatedKey column="id" sqlStatement="JDBC"/>`
`</table>`

会将mysql数据库中所有表进行处理，而没有将指定数据库下所有表进行处理，该如何配置？
环境说明：
mysql8
tk.mybatis:mapper:4.0.4

**Comment by abel533** [comment]
可以指定 schema 试试
