### ISSUE TITLE
排序注解优化

### ISSUE THREAD

**Issue by qrqhuang** [abel533/Mapper#456]
有看到项目支持 `@OrderBy("desc")` 以实现单表字段排序，挺方便， 但有不足的地方。

- 该注解由`Java Persistence 1.0`提供， 适用于一对多子集合排序情况，会让人造成误解。- 
- 若需要多个字段排序，现目前无法指定先后顺序。

看是否可以自定义新注解， 并支持优先级如
```java
    @Order(value="asc", priority=2)
    private String countryName;

    @Order(value="desc", priority=1)
    private String countryCode;
```

**Comment by abel533** [comment]
感谢PR，已合并。

修改了PR， 兼容 OrderBy，但是 Order 优先级更高。
