### ISSUE TITLE
关于使用通用mapper和分页插件进行分页时，查询出来的数据重复的问题

### ISSUE THREAD

**Issue by 2500438167** [abel533/Mapper#46]
我使用PageHelper分页，发现调用selectByExampleAndRowBounds这个方法后，本应返回10条数据，但是实际返回了20条，数据是重复的。我调试代码，发现在pagehelper的SqlUtil类中，第499行的Object result = invocation.proceed();方法走了两遍，导致下面的page.addAll((List)result);方法加了两遍数据。不能确定是哪里引起的问题。pageHelper的版本是4.1.6，mapper的版本是3.3.8.

**Comment by abel533** [comment]
第499行的Object result = invocation.proceed();方法走了两遍，怎么走了两遍？？

导致下面的page.addAll((List)result);方法加了两遍数据？？

**Comment by 2500438167** [comment]
![image](https://cloud.githubusercontent.com/assets/9673709/18201935/b57b4dc0-713f-11e6-89eb-47709c2877c2.png)

**Comment by 2500438167** [comment]
这个是程序调用的信息，这个里面我就没法跟了，从这里跳出来就会又走一个page.addAll的方法。

**Comment by 2500438167** [comment]
我做了一个小的demo，给您发到abel533@gmail.com这个邮箱中，你帮我看一下行吗，这个问题能模拟出来。
