### ISSUE TITLE
通用mapper能查询聚合函数嘛？

### ISSUE THREAD

**Issue by SmNiuhe** [abel533/Mapper#460]
查看了一下通用mapper的相关文档，没找到操作聚合函数的介绍，不知道大家是如何操作的，都是生成 <SELECT> 嘛？

**Comment by abel533** [comment]
这里有测试的例子：https://github.com/abel533/Mapper/blob/master/extra/src/test/java/tk/mybatis/mapper/additional/aggregation/AggregationMapperTest.java
