### ISSUE TITLE
insertUseGeneratedKeys设置自增主键，主键名不为id，有没有更好的办法解决

### ISSUE THREAD

**Issue by CaoPengflying** [abel533/Mapper#461]
文档说明：
/**
     * ======如果主键不是id怎么用？==========
     * 假设主键的属性名是uid,那么新建一个Mapper接口如下
     * <pre>
        public interface InsertUidMapper<T> {
            @Options(useGeneratedKeys = true, keyProperty = "id")
            @InsertProvider(type = SpecialProvider.class, method = "dynamicSQL")
            int insertUseGeneratedKeys(T record);
        }
     * 只要修改keyProperty = "uid"就可以
     *
     * 然后让你自己的Mapper继承InsertUidListMapper<T>即可

我按照这种方式解决，但是有点麻烦，我需要专门创建一个接口去继承这个接口并且在新的接口不能调用原本的常用方法。然后需要在service中注入了两个mapper，很麻烦有没有简单的解决方案?

**Comment by sunhao-java** [comment]
有 但是现在作者还没有去做 我已经提出issue建议这么做了 目前我用着是很成功的 再不做 我就自己写 然后发起个pull request了
请看我的issue #445
