### ISSUE TITLE
blob

### ISSUE THREAD

**Issue by lihiayang0710** [abel533/Mapper#462]
我用通用的generator生成的model没有blob字段。mysql字段类型为text，这个字段没有包含的生成的model中。也不像MBG会生成xxxxxxWithBLOBs的model。

**Comment by abel533** [comment]
可以试试 `defaultModelType=flat` 生成单一对象。

**Comment by abel533** [comment]
配置看这里：https://blog.csdn.net/isea533/article/details/42102297
