### ISSUE TITLE
mysql的驱动版本导致的mapper-generator生成实体类的@Id问题

### ISSUE THREAD

**Issue by springpro** [abel533/Mapper#463]
mysql server: 5.7.20
5.x.x驱动正常有@Id，6.x，和8.x都没有@Id

**Comment by qrqhuang** [comment]
确实有这个问题
问题来源自`mybatis-generator-core`， 你可以在新版本中指定catalog临时解决
`<table catalog="test" tableName="demo_country"/>`

我再看下有没有更优雅的方式解决。

**Comment by RiverFlowsInYourHeart** [comment]
MySQL 8.0.6版本，使用`@Id`和`@GeneratedValue(strategy = GenerationType.IDENTITY)`后，还是存在不能自动生成ID的问题

**Comment by wenjuncao** [comment]
也可以在数据库配置url后面追加nullCatalogMeansCurrent=true

**Comment by ZHK1996** [comment]
连接oracle数据库为什么,老是报Error selecting key or setting result to parameter object. Cause: java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字,对了我主键是string类型的.
