### ISSUE TITLE
实体类和Table名字不一致

### ISSUE THREAD

**Issue by CaoPengflying** [abel533/Mapper#466]
生成了和数据库对应的实体类，
然后自己创建了扩展类，在扩展类中加入了一些特殊的方法，能不能使用扩展类向表中插入数据。
目前报了异常说table无法找到

**Comment by abel533** [comment]
贴代码看看。

类似` insert(T t)` 的方法可以使用扩展的子类进行插入。

**Comment by CaoPengflying** [comment]
可以使用子类插入的，我这边配置有点问题
