### ISSUE TITLE
调用 updateByPrimaryKey 居然where里是所有字段, 我确信实体里是有@Id的, 使用版本这2.0.4

### ISSUE THREAD

**Issue by miws** [abel533/Mapper#470]
调用 updateByPrimaryKey 居然where里是所有字段, 我确信实体里是有@Id的, 使用版本这2.0.4
`updateByPrimaryKey      : ==>  Preparing: UPDATE User SET id = ?,name = ?,age = ? WHERE id = ? AND name = ? AND age = ? `

**Comment by abel533** [comment]
看看 `@Id` 是不是 JPA 包里面的。
