### ISSUE TITLE
关于Mapper的底层原理是如何调用的

### ISSUE THREAD

**Issue by Yuxiao97** [abel533/Mapper#474]
如题，基于BaseMapper中都有CRUD的各种基础功能，但在BaseXXXProvider中，看到的是返回封装后的SQL语句，到底哪里执行了入库的操作呢？请教请教请教！

**Comment by abel533** [comment]
Mapper 底层返回的 SQL 替换了接口方法的默认定义，也就是初始化后，你调用的方法和直接写的 mybatis 方法是完全相同的。入库操作看 mybatis 执行过程。

**Comment by Yuxiao97** [comment]
> Mapper 底层返回的 SQL 替换了接口方法的默认定义，也就是初始化后，你调用的方法和直接写的 mybatis 方法是完全相同的。入库操作看 mybatis 执行过程。

也就是说在BaseXXXProvider中返回的SQL语句会交给MyBatis执行？

**Comment by abel533** [comment]
BaseXXXProvider中返回的是 XML 形式的 SQL，会在 Mapper 中解析为 SqlSource 替换 MS 中的值，此后执行和 Provider 没有任何关系。

**Comment by abel533** [comment]
原理看这儿：https://blog.csdn.net/isea533/article/details/78493852

**Comment by Yuxiao97** [comment]
> 原理看这儿：https://blog.csdn.net/isea533/article/details/78493852

感谢！
