### ISSUE TITLE
@LogicDelete 注解的问题

### ISSUE THREAD

**Issue by sxinle** [abel533/Mapper#475]
实体是这样的结构
![desktop](https://user-images.githubusercontent.com/5837285/49203892-e2ebd700-f3e4-11e8-88fe-1524e4028b6b.png)
启动就报这个异常
![image](https://user-images.githubusercontent.com/5837285/49203942-16c6fc80-f3e5-11e8-8dd2-652ffb99c9a1.png)
感觉这块代码有点问题

![image](https://user-images.githubusercontent.com/5837285/49204138-ce5c0e80-f3e5-11e8-8330-5bd80ba0c95d.png)

请大佬帮忙看下

**Comment by abel533** [comment]
@duwey 帮忙看看这个问题。

**Comment by duwey** [comment]
@abel533 已修复 #476

**Comment by abel533** [comment]
下周一发布 4.1.1 解决这个问题。
