### ISSUE TITLE
你有没有兴趣加入 Mapper?

### ISSUE THREAD

**Issue by abel533** [abel533/Mapper#479]
所有 PR 过的朋友有没有兴趣加入 Mapper?

@duwey 
@sunhao-java 
@qrqhuang 
@JiangYongKang
@zhiguangliu
@heshengbang 
@hittor
@wudy875498
@ztyzbb
@finira 
@wittyliu 
@tjpanda88
@littlefisher
@AngiWANG
@chinaerserver
@CarlJia
@liyongjun1 
@Ngone51 
@raistlinzx 
@DogFc 
@IamFive 
@NorthFacing 

经常在 ISSUE 回答问题，或者愿意完善文档的朋友有没有兴趣加入 Mapper?

如果大家愿意，是想在 https://github.com/abel533/Mapper 下面继续开发，还是将项目挪到组织下面进行开发？

可选组织：https://github.com/mybatis3

大家有愿意的或者有想法的都可以留言，谢谢大家参与！

**Comment by 844189873** [comment]
我也想参与到通用mapper的开发中来。
https://github.com/mybatis3这个看起更官方一点，会好一点

**Comment by duwey** [comment]
https://github.com/mybatis3也仅仅只是看起来官方一点、容易引起混淆的非官方组织，所以我倒是觉得没什么挪过去的必要。。。而且吧，这个组织下面也并没有什么实质性有用的东西~
当然最终还是看大家的决定啦。

**Comment by Ngone51** [comment]
抱歉，刘兄，我就不加入了。我现在也会偶尔看看Mapper的发展和更新。祝福通用Mapper越来越好！

**Comment by liyongjun1** [comment]
如果刘兄需要帮忙的话，我是非常愿意加入进来贡献自己的一份里的。开源本身就是一件很有意义的事情

**Comment by hwck** [comment]
希望加入组织

**Comment by zhiguangliu** [comment]
因为家里公司事情都挺多的，加入暂时没有时间。但是我会在公司推进使用，持续关注Mapper的发展，也会结合自己的使用，提出自己的意见和建议的。谢谢。

**Comment by CarlJia** [comment]
一直主张用开源的东西，也一直希望能为开源做一些贡献，感觉还是在原来的地址就好了。

**Comment by shisanli** [comment]
很高兴有机会参与到Mapper到开发。
如有需要，我可以用业余时间参与开源活动，这很有意义

**Comment by NorthFacing** [comment]
迁移没有必要吧，大版本更新的时候使用新地址就好了。

**Comment by hittor** [comment]
在公司内部推广后得到了研发团队的一致支持，因为Mapper好用易得，这里要特别感谢一下作者及团队。迁移的收益并不明显，所以个人认为可迁可不迁。目前默默关注这个项目半年了，如有机会，我很愿意在能力之内尽一份薄力，毕竟这是一个不错的项目，至少我认为是这样。握手！

**Comment by ranjinpeng** [comment]
我希望可以加入.  支持开源，自己也开源了一个 支持swagger-ui的  通用Mapper的逆向生成工具。希望可以加入

**Comment by abel533** [comment]
![mybatis](https://user-images.githubusercontent.com/1787798/49915611-6de2cc00-fed1-11e8-89c0-c14af63b327d.png)
MyBatis工具维护QQ群：542119179

大家可以加入这个群。

**Comment by wbb18129355955** [comment]
小白可以吗，做做文档也可以。

**Comment by wbb18129355955** [comment]
可以加入吗？小白一个，写写文档也可以

**Comment by DeeWooo** [comment]
申请加入，在上家公司推动使用了mapper一段时间，后来因为架构升级，架构师又下掉了，换成了jpa。
当时觉得是自己对mapper的了解不够深入，所以无法说服架构师。
现在希望加入Mapper，也是给自己一个学习的机会。

**Comment by AngiWANG** [comment]
非常感谢邀请，主要是最近有点忙，担心做不了什么，等忙完了联系你。

**Comment by sunhao-java** [comment]
愿意加入，虽然公司没有直接使用mapper，但还是借鉴了，并且也曾给社区提过意见

**Comment by JiangYongKang** [comment]
愿意加入，年底了，不怎么忙，可以贡献一些力量
