### ISSUE TITLE
3.3.9版本自动生成XML的注释标签从@mbggenerated 变成了@mbg.generated 导致会重复生成

### ISSUE THREAD

**Issue by sirs05** [abel533/Mapper#48]

**Comment by abel533** [comment]
这个问题注意到了，下个版本会解决。

**Comment by sirs05** [comment]
在3.3.8版本，多次重复运行会覆盖上一次生成的mapper xml
升级到3.3.9以后，第一次运行，覆盖掉了原来标记为@mbggenerated的生成xml，并替换为@mbg.generated。后面每运行一次自动生成就多添加一条。

**Comment by howenx** [comment]
这问题解决了吗？我现在用最新版本3.4.0还有这样的问题，mapper xml不会覆盖，还会继续添加

**Comment by abel533** [comment]
MBG原来就是这样，不知道新版本是不是不一样了。

**Comment by DKodak** [comment]
生成的注视为啥不会以mapper的方法尼？
