### ISSUE TITLE
@KeySql实现GenId时,如果我手动set了主键id的值，则手动set的id值被GenId所覆盖？

### ISSUE THREAD

**Issue by maolujun** [abel533/Mapper#482]

**Comment by maolujun** [comment]
@abel533 大神，有没有好的处理方式？

**Comment by abel533** [comment]
4.1.1 会解决这个问题。

**Comment by maolujun** [comment]
感谢。
现在我们项目处理方式是：自定义了一个update拦截器
![image](https://user-images.githubusercontent.com/17269489/49683489-dc561180-fb00-11e8-8f9e-83066617082e.png)
