### ISSUE TITLE
mysql数据库字段为text时使用该插件,不会生成WithBLOBs

### ISSUE THREAD

**Issue by bin-cn** [abel533/Mapper#486]
mysql 中字段类型为 text,

 		<plugin type="tk.mybatis.mapper.generator.MapperPlugin">
			<property name="mappers"  value="com.xxxx.BaseMapper" />
		</plugin> 
如果使用插件则不会生成对应的WithBLOBs类,提示找不到xxxxxWithBLOBs类,如果不使用插件则正常,插件版本3.4.6和4.1.1都有这种情况.

**Comment by abel533** [comment]
默认方法都去掉了。
