### ISSUE TITLE
insertList后批量回写ID报错

### ISSUE THREAD

**Issue by lbscut** [abel533/Mapper#492]
使用mybatis版本3.2.4，tkmybatis版本4.1.1
回写ID时会使用Jdbc3KeyGenerator（3.2.4版本），批量回写时会报错，升级mybatis版本为3.3.1后解决。
README.md中的【通用 Mapper 支持 Mybatis-3.2.4 及以上版本。】稍有误解。

**Comment by abel533** [comment]
具体方法的支持不同。
