### ISSUE TITLE
请问type-aliases-package如何配置多个model

### ISSUE THREAD

**Issue by guoliang3** [abel533/Mapper#493]
我的model 分别在不同的文件夹下 如何配置多个
目前配置如下
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.xxx.app.model

**Comment by lw5946** [comment]
使用mybatis自定义配置的功能，实现org.mybatis.spring.boot.autoconfigure.ConfigurationCustomizer接口

**Comment by abel533** [comment]
个人感觉，在配合IDEA free mybatis 类的插件使用时，也不需要省略包名去用，用完整的看着也直观。
