### ISSUE TITLE
使用 updateByExample+乐观锁 报Parameter 'version' not found. Available parameters are [record, param1, example, param2], excetion=MyBatisSystemException]

### ISSUE THREAD

**Issue by Kiuyam** [abel533/Mapper#496]
tk.mapper Version: 4.1.2
spring MVC Version: 4.3.0.RELEASE

代码重现
![image](https://user-images.githubusercontent.com/25220646/50467153-8debb280-09dc-11e9-858c-4c03c4d2a0f0.png)

代码简述
实体类，由子类+父类组成，version字段在父类上。(经测试 子类增加version字段也会报错)
example.getPropertyMap()方法中是可以查询到version这个字段的。
单表mapper，继承父接口CoreBaseMapper，未增加任何其它实现方法
CoreBaseMapper继承Mapper<T>, IdListMapper<T, String>, InsertListMapper<T>

updateByPrimaryKey 可以运行
但updateByExample 会抛出 Parameter 'version' not found. Available parameters are [record, param1, example, param2], excetion=MyBatisSystemException]
未执行到打印Sql

尝试过程
单步运行了一下，跟踪看的头疼，跟踪问题乏力，望谅解。

求正确解决问题的姿势，并不确定是不是源码问题，群里问了下无人回复。是否有解决过此问题的大佬？。

**Comment by Kiuyam** [comment]
https://gitee.com/free/Mapper/issues/IP37R  gitee上也有人提了类似的问题。

**Comment by Kiuyam** [comment]
实体去掉 Version运行正常，参考gitee issue上的源码解释，应该可以确认是代码bug。

**Comment by Kiuyam** [comment]
https://gitee.com/free/Mapper/issues/IP37R gitee 已定义为bug，此issue可以关闭了。

**Comment by fushun1990** [comment]
已解决，提交合并：https://github.com/abel533/Mapper/pull/506
