### ISSUE TITLE
selectByPrimaryKey和selectOneByExample的问题

### ISSUE THREAD

**Issue by apa7** [abel533/Mapper#500]
版本:
tk.mybatis.mapper-core.1.1.0
tk.mybatis.mapper-spring-boot-starter.2.0.4

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select substring(uuid(), 1, 8)")
	@Column(name = "id", unique = true, nullable = false)
	private String id;

错误信息:
org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 14

**Comment by apa7** [comment]
更换版本也没有效果, 前几次查询没有问题, 后面的selectOneByExample均出现这个报错
		<tk.mybatis.mapper.version>4.1.1</tk.mybatis.mapper.version>
		<mapper-spring-boot-starter.version>2.1.1</mapper-spring-boot-starter.version>

**Comment by Likenttt** [comment]
我发现我遇到这种问题往往是由于我的查询条件里面出现了空值
I found it occurred when certain query parameter is null.
