### ISSUE TITLE
Example如何打印sql日志

### ISSUE THREAD

**Issue by feixiangsmile** [abel533/Mapper#504]
你好，this.selectByExample(example) 这种查询，在后台怎么不打印sql语句的查询日志呀？？？  我通过mapper.xml 自己写的dao方法 执行的时候 在后台能打印sql执行日志的

**Comment by sj13824803000** [comment]
设置你dao所在bao的日志级别为debug就可以打印sql了

**Comment by riverfrank** [comment]
logging.level.tk.mybatis.springboot.mapper=debug

**Comment by jsyzthz** [comment]
我用logback就配置mapper的包日志级别都是Debug就可以了，例如：
<logger name="com.xxxx.mapper" level="DEBUG">
</logger>
