### ISSUE TITLE
WeekendSqls的第二个参数为String的问题

### ISSUE THREAD

**Issue by diansong** [abel533/Mapper#505]
请问WeekendSqls的orEqualTo(Fn<T, Object> fn, String value)，第二个参数是否应该调整为Object？
orNotEqualTo、orGreaterThan等都有此类问题。

**Comment by sj13824803000** [comment]
使用该方法:
Weekend weekend = Weekend.of(Entity.class);
weekend.weekendCriteria().orEqualTo(Entity::getId,id)
拿到weekendCriteria来拼接查询即可
