### ISSUE TITLE
lombok生成的Getter兼容性问题

### ISSUE THREAD

**Issue by diansong** [abel533/Mapper#507]
使用Weekend时遇到了一个lombok的Getter兼容性问题，暂时无法解决：
例如数据库表字段为E_NAME，实体的属性名为eName，lombok生成的Getter是getEName()。
Introspector.decapitalize(String name)将getter转换为属性名时，会转换为EName，从而导致报错。
这个问题lombok一直认为不必修复，可能会在2.x版本中才考虑。
Eclipse生成的Getter是geteName(),不存在这个问题。

只想到了两种侵入性很强的方式，暂时没找到好的解决方法。
1.要求字段名第二位不能是下划线
2.字段名第二位是下划线，则把前两位当作前缀去除。

可否在通用Mapper中的Reflections.fnToFieldName(fn)，加入一个可配参数或自定义扩展接口。

**Comment by abel533** [comment]
修改 e_name 更合适，最好能在 javabean 规范上统一，否则在各种工具库上都可能遇到坑。

**Comment by diansong** [comment]
统一规范，确实能让工作轻松不少。
工作中总是不自觉的在扩展性和兼容性想得多了一些。
