### ISSUE TITLE
为什么不直接在common-mapper.xml里面定义通用mapper操作

### ISSUE THREAD

**Issue by scofier** [abel533/Mapper#508]
SqlHelper，MapperTemplate 等用sqlscript，sqlnode，为什么不直接定义一个common-mapper.xml 在里面定义通用mapper操作？现在用sqlscript，sqlnode 通过代码的方式来组合sql实现， 感觉非常不直观。

借助mybatis的xml定义动态sql，然后加载到mapperTemplate中生成通用接口，这样不是更好一点？

**Comment by MissThee** [comment]
就我个人而言，我是特别不喜欢写xml。。。用通用mapper 的目的就是想要干净的java代码，所有东西都由java对象解决。

**Comment by abel533** [comment]
common-mapper.xml无法处理各种特殊逻辑。
