### ISSUE TITLE
spring boot2 环境下不支持simpleTypes 配置

### ISSUE THREAD

**Issue by Sochene** [abel533/Mapper#509]
spring boot2 环境下不支持simpleTypes 配置

**Comment by jack521** [comment]
mapper.useSimpleType=false 支持基本类型，true不支持。
不知道是故意这样定义的还是有意为之~

**Comment by jack521** [comment]
> spring boot2 环境下不支持simpleTypes 配置
在配置文件里：
mapper.useSimpleType=false 
false支持基本类型，true不支持。

不知道是故意这样定义的还是有意为之~

**Comment by abel533** [comment]
@jack521 simpleType不是指的原生类型。
