### ISSUE TITLE
使用InsertList方法批量插入时候，设置实体Id失效，实体必须是主键自增，这块能修改下吗

### ISSUE THREAD

**Issue by aaronuu** [abel533/Mapper#510]
如题 使用InsertList方法批量插入时候，设置实体Id失效，实体必须是主键自增，这块能修改下吗

**Comment by sj13824803000** [comment]
批量插入有两个接口,一个是支持自增长的,一个是支持自定义主键的,按需引用
自增长:tk.mybatis.mapper.common.special.InsertListMapper
自定义主键:tk.mybatis.mapper.additional.insert.InsertListMapper

**Comment by aaronuu** [comment]
> insert

你用的是哪个版本？我找不到你说的这个自定义主键的包

**Comment by aaronuu** [comment]
> 批量插入有两个接口,一个是支持自增长的,一个是支持自定义主键的,按需引用
> 自增长:tk.mybatis.mapper.common.special.InsertListMapper
> 自定义主键:tk.mybatis.mapper.additional.insert.InsertListMapper

你用的是哪个版本？我找不到你说的这个自定义主键的包

**Comment by aaronuu** [comment]
> 批量插入有两个接口,一个是支持自增长的,一个是支持自定义主键的,按需引用
> 自增长:tk.mybatis.mapper.common.special.InsertListMapper
> 自定义主键:tk.mybatis.mapper.additional.insert.InsertListMapper

Thanks
