### ISSUE TITLE
@Version在Timestamp使用上JDBC一直抛异常

### ISSUE THREAD

**Issue by zsw19870203** [abel533/Mapper#513]
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '07:30:10.736 WHERE  test_id = 10 AND updated = '2014-10-15 18:31:50'' at line 1
（这里证明了是个语法错误）

### The error may involve com.zsw.mapper.TestMapper.updateByPrimaryKeySelective-Inline
（这里明确了@Version注解确实生效了，错误发生在updateByPrimaryKeySelective方法中）

### SQL: UPDATE test  SET sal = ?,job_num = ?,updated = 2019-01-09 07:30:10.736 WHERE  test_id = ? AND updated = ?
（日志追踪：拼SQL出现updated = 2019-01-09 07:30:10.736也说明正确获取了当前时间，
updated = ?说明Pojo对象内确实有原时间对象Timestamp，且值不为空）

其实吧我就想问updated = 2019-01-09 07:30:10.736这里取值时是不是缺了一对（‘ ’）造成SQL语法的错误呢？
望作者大大解惑

**Comment by zsw19870203** [comment]
**UPDATE test SET sal=2,job_num=2,updated=2019-01-09 07:30:10.736 WHERE test_id=10 AND updated='2014-10-15 18:31:50'**
数据库里跑这条SQL报错也是因为缺了引号造成的，所以上面的报错应该是如出一辙的！希望各路大神解惑

**Comment by zsw19870203** [comment]
UPDATE test SET sal=2,job_num=2,updated=2019-01-09 07:30:10.736 WHERE test_id=10 AND updated='2014-10-15 18:31:50'
数据库里跑这条SQL报错也是因为缺了引号造成的，所以上面的报错应该是如出一辙的！希望各路大神解惑是否@Version在对TimeStamp支持上，取值时存在缺少引号的BUG？

**Comment by diansong** [comment]
乐观锁是接拼写在SQL语句中，而不是绑定变量的方式。
因此实际上只能拼接字符串，不能处理日期类型。
只增加引号无法解决的数据库兼容性问题。

我暂时使用的方案是返回【（数据库相关的）时间函数】字符串，样例如下：
public class MyNextVersion implements NextVersion<Object> {
    @Override
    public Object nextVersion(Object current) throws VersionException {
        return "SYSTIMESTAMP"; // 此处样例为Oracle生成timestamp的方法，建议使用配置文件管理。
    }
}

**Comment by abel533** [comment]
最新版本已经解决了，可以看看更新日志。。

建议关注微信公众号获取更新信息。

wiki 页最下面有二维码：https://github.com/abel533/Mapper/wiki

**Comment by zsw19870203** [comment]
试了  果然效率！NextVersion<T>增加泛型，方便自己拓展Date类型支持了！
