### ISSUE TITLE
Cannot resolve class 'Mapper2'

### ISSUE THREAD

**Issue by jemon9** [abel533/Mapper#518]
你好，本人小白鼠一枚，按照官网starter自动配置方式，报下面错误，烦请帮忙解决一下，谢谢！
pom.xml
     <dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper-spring-boot-starter</artifactId>
            <version>2.1.4</version>
        </dependency>
.yml
    mapper:
      mappers:
        - tk.mybatis.mapper.common.Mapper
        - tk.mybatis.mapper.common.Mapper2    //这行Mapper2标红，提示Cannot resolve class 'Mapper2'
      notEmpty: true
问题详情请看上面注释，谢谢！

**Comment by wds--moon** [comment]
去掉就是了,这个还可以自定义
mapper.mappers=com.example.core.TkMapper
public interface TkMapper<T> extends Mapper<T>, MySqlMapper<T>{

}

**Comment by jemon9** [comment]
了解了，感谢哈！
