### ISSUE TITLE
tk3.3.8之后，列名大小写问题

### ISSUE THREAD

**Issue by IDEA-Fang** [abel533/Mapper#519]
tkmybatis3.3.8
mybatis3.4.0
mybatis-spring1.3.2
查询selectAll()，查询的字段都是大写，实体是驼峰，

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'ID' in 'field list'
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'ID' in 'field list'
org.springframework.jdbc.BadSqlGrammarException: 

与这个问题相同
3.3.8之后, 列名的大小写出现问题. #22
https://github.com/abel533/Mapper/issues/22

**Comment by abel533** [comment]
试试最新版本。
