### ISSUE TITLE
批量插入，回写ID只有一个

### ISSUE THREAD

**Issue by youfeng** [abel533/Mapper#52]
通用接口方法，返回list中只回写了一个ID字段

public interface InsertListMapper<T> {
    /**
     \* 批量插入，支持数据库自增字段，支持回写
     *
     \* @param recordList
     \* @return
     */
    @Options(useGeneratedKeys = true, keyProperty = "id")
    @InsertProvider(type = SpecialProvider.class, method = "dynamicSQL")
    int insertList(List<T> recordList);
}

**Comment by abel533** [comment]
使用的数据库以及其他环境是什么？

**Comment by youfeng** [comment]
数据库：sql server
jdk1.8 + mybatis 3.3.1

2016-09-22 20:17 GMT+08:00 Liuzh <notifications@github.com>:

**Comment by abel533** [comment]
sqlserver有这个问题。
