### ISSUE TITLE
想在自动生成实体时，生成 swagger注释 ，请问怎么配置

### ISSUE THREAD

**Issue by kojz** [abel533/Mapper#522]
想在自动生成时，生成 swagger注释 ，

例如

  @ApiModelProperty("用户ID")
  private Integer id;

**Comment by Frodez** [comment]
可以使用mybatis-generator生成，我现在就使用的这种方案。
对于DTO和VO，我直接拿eclipse的jdt来分析生成了（

**Comment by abel533** [comment]
已经支持了。
