### ISSUE TITLE
generator设置了rootClass子类仍旧生成父类属性

### ISSUE THREAD

**Issue by hansfam** [abel533/Mapper#524]
generator配置如下

	<!DOCTYPE generatorConfiguration
	        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
	        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
	
	
	<generatorConfiguration>
	    
	    <properties resource="application-dev.properties" />
	    <context id="Mysql" targetRuntime="MyBatis3Simple" defaultModelType="flat">
	
	        <property name="javaFileEncoding" value="UTF-8"/>
	        <property name="useMapperCommentGenerator" value="true"/>
	
	        <plugin type="tk.mybatis.mapper.generator.MapperPlugin">
	            <property name="mappers" value="com.assunmotor.core.database.manager.BaseService"/>
	            <property name="caseSensitive" value="true"/>
	            <property name="forceAnnotation" value="true"/>
	            <property name="beginningDelimiter" value="`"/>
	            <property name="endingDelimiter" value="`"/>
	        </plugin>
	
	
	        <commentGenerator>
	            <property name="suppressDate" value="true"/>
	        </commentGenerator>
	
	        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
	                        connectionURL="${spring.datasource.url}"
	                        userId="${spring.datasource.username}"
	                        password="${spring.datasource.password}">
	        </jdbcConnection>
	
	        
	        <javaModelGenerator targetPackage="com.assunmotor.core.persistent.entity"
	                            targetProject="./src/main/java">
	            <property name="rootClass" value="com.assunmotor.core.persistent.BaseEntity"/>
	        </javaModelGenerator>
	        
	        <sqlMapGenerator targetPackage="resources.mapping"
	                         targetProject="./src/main"/>
	        
	        <javaClientGenerator type="XMLMAPPER"
	                             targetPackage="com.assunmotor.core.persistent.mapper"
	                             targetProject="./src/main/java">
	        </javaClientGenerator>
	
	        <table schema="test" tableName="core_user" >
	            <property name="rootClass" value="com.assunmotor.core.persistent.BaseEntity"/>
	            <generatedKey column="id" sqlStatement="Mysql"/>
	        </table>
	    </context>
	
	</generatorConfiguration>

生成实体类时, 虽继承了父类, 但仍有父类中所含的属性 (名称/属性/setter/getter都相同)

**Comment by jsyzthz** [comment]
添加classPathEntry，在maven里面就先install 父类所在的jar文件到本地仓库，classPathEntry中location指向改jar，这样属性g&s不会生成，但是数据库字段名常量还是会生成。
