### ISSUE TITLE
oracle 表名称小写时候需要双引号，如何处理

### ISSUE THREAD

**Issue by goodcto** [abel533/Mapper#528]
问题如题

**Comment by fushun1990** [comment]
@Table 注解，可以自定义表名称

**Comment by goodcto** [comment]
@fushun1990  oracle 小写的表名字，需要带上引号的，如果不带，就提示 没有此表，而@Table 注解不能再次加双引号的。

**Comment by abel533** [comment]
`@Table("\"name\"")` 有问题？

oracle 一般所有名都用大写。

**Comment by goodcto** [comment]
> `@Table("\"name\"")` 有问题？
> 
> oracle 一般所有名都用大写。

遇到了一个奇怪的甲方，目前用大写的形式暂时规避了这个问题，您这种方式，会报错的
