### ISSUE TITLE
批量插入失败

### ISSUE THREAD

**Issue by TaurusXi** [abel533/Mapper#54]
批量插入List<Model>，插入失败： nested exception is org.apache.ibatis.builder.BuilderException: Error invoking SqlProvider method (tk.mybatis.mapper.provider.SpecialProvider.dynamicSQL).  Cause: java.lang.InstantiationException: tk.mybatis.mapper.provider.SpecialProvider

For循环单独插入Model是没问题的。

数据源是 mysql

**Comment by abel533** [comment]
和 dynamicSQL 有关的错误基本都是配置的问题。

**Comment by TaurusXi** [comment]
那我检查一下配置。
然后还有个小问题。
目前Mapper的kit，原生支持
@Select("select * from pics where id in (#{picList})")
    fun selectPicListByIdList(@Param("picList") picList:List<String>):List<PicsPo>
转化为  select * from pics where id in ( value1,value2,value3,value4,...  )这类的查询么?
不支持的话，我就自己写一个了

**Comment by abel533** [comment]
不支持，用foreach

**Comment by ysysdzz** [comment]
同样的问题 求解解决
