### ISSUE TITLE
GeneratedValue自增主键问题

### ISSUE THREAD

**Issue by xiachao616345713** [abel533/Mapper#545]
按文档说的
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Integer id;
相当于
### <insert>
    <selectKey keyProperty="id" resultType="int" order="AFTER">
      SELECT LAST_INSERT_ID()
    </selectKey>
    insert into country (id, countryname, countrycode)
    values (#{id},#{countryname},#{countrycode})
</insert>
但是实际上测试相当于order="BEFORE"，插入第一次id为null对象可以成功，并且得不到可以，第二次会报主键冲突

**Comment by yang-mr** [comment]
QL: INSERT INTO hj_pic  ( created,updated,id,userid,url,name,status,style ) VALUES( ?,?,?,?,?,?,?,? )
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2023' for key 'PRIMARY'

**Comment by yang-mr** [comment]
这个问题很严重！ 出现的概率很大啊

**Comment by tangdu** [comment]
对的。我也看到这个bug了。准备回退新版本

**Comment by yang-mr** [comment]
MySQLIntegrityConstraintViolationException  这个新版本有修复吗？ 各位大佬

**Comment by yang-mr** [comment]
> 对的。我也看到这个bug了。准备回退新版本

最后你怎么解决的？ 兄弟

**Comment by abel533** [comment]
@yang-mr 你跟楼主问题一样吗？

@xiachao616345713 **插入第一次id为null对象可以成功，并且得不到可以，第二次会报主键冲突**，从这句话能看出来，同一个对象被反复插入数据库。。第一次插入数据库后，id 字段就有值了！！！再次插入时，就是指定主键插入，不是自增了！！！

**Comment by RyanPro** [comment]
同样遇到了这个问题，请问是怎么解决的

**Comment by xiachao616345713** [comment]
> 同样遇到了这个问题，请问是怎么解决的

没有@GeneratedValue(strategy = GenerationType.IDENTITY) 用的@GeneratedValue(generator = "JDBC")解决了
