### ISSUE TITLE
实体类中存在非表字段属性

### ISSUE THREAD

**Issue by brook-david** [abel533/Mapper#559]
实体类中存在非表字段属性，且为继承属性，@@Transient不适用，希望可以select *

**Comment by abel533** [comment]
`@Transient` 可以起到作用，继承关系中的非表字段也需要加该注解。

**Comment by brook-david** [comment]
继承字段有的表有该字段，有的表没有，@Transient无法适应性的解决问题。但是这是由项目设计问题引起的，目前打算新内容使用tk，旧内容沿用mybatis，在开发过程中有对旧表操作再针对进行相关处理，感谢您的关注与回复。
