### ISSUE TITLE
updateByExampleSelective更新条件不生效

### ISSUE THREAD

**Issue by scrollsyou** [abel533/Mapper#560]
https://github.com/abel533/Mapper/blob/45c3d716583cba3680e03f1f6790fab5e1f4f668/core/src/main/java/tk/mybatis/mapper/entity/Example.java#L336
当example.and().andEqualTo("username", bean.getUsername())中bean.getUsername()未做空判断时，做xxxMapper.updateByExampleSelective(bean, example);时会把where username=null过滤掉，直接进行全表更新。
虽然字段判空是必要的。

**Comment by abel533** [comment]
Example 构造方法能控制空值的处理，还有 safeUpdate 和 safeDelete 参数可以避免全表操作，看 wiki 参数介绍！

**Comment by scrollsyou** [comment]
好的，谢谢。
