### ISSUE TITLE
Example的excludeColumns 和 selectColumns方法建议废除掉，改用和其他orm框架相同的处理方式，读@Transient注解等

### ISSUE THREAD

**Issue by ThomasCui** [abel533/Mapper#567]
Example的excludeColumns 和 selectColumns方法建议废除掉，改用和其他orm框架相同的处理方式，读@Transient注解等。不然需要将字段名写在代码中，字段名变更或者框架切换时需要改写大量代码。

**Comment by cshijiel** [comment]
该框架本质是根据数据库模型定义生成仓库层。在Model上标记过多的注解，会影响Model代码的生成结果，或者加大MBG的逻辑

**Comment by ArthurZgx** [comment]
@transient和selectColumns方法的用途是不一样的，一个是不进行映射，一个是根据业务需求查询时只查询自己想要的字段

**Comment by abel533** [comment]
需求和含义不同，和 `@Transient` 无关。
