### ISSUE TITLE
关于插入时间和更新时间的问题

### ISSUE THREAD

**Issue by twistthous** [abel533/Mapper#583]
您好，首先感谢你的插件，有一个问题是我想在插入的时候设置更新时间和插入时间，修改的时候设置更新时间，在执行的时候动态插入，请问是否可以支持这个功能呢？

**Comment by cjsky666** [comment]
这个，你自己设置数据库字段根据当前时间插入和更新就好了呀

**Comment by abel533** [comment]
如果你用一个 BaseService 封装这种基础逻辑，就能在业务层实现。
