### ISSUE TITLE
调用存储过程，返回多个结果集问题

### ISSUE THREAD

**Issue by youfeng** [abel533/Mapper#59]
sqlserver2008
调用存储过程，返回多个结果集时，只返回了一个结果。
          
	<resultMap type="com.xxx.Result2" id="result2">
		<result column="field2" property="field2" />
	</resultMap>

	<resultMap type="com.xxx.Result3" id="result3">
		<result column="field3" property="field3" />
	</resultMap>

	<select id="getXXXByUserId" statementType="CALLABLE" parameterType="java.util.HashMap" resultMap="result2,result3">
		<![CDATA[
            {call GetXXXUserId (
              #{userId,mode=IN,jdbcType=INTEGER},
              #{deviceID,mode=IN,jdbcType=VARCHAR}
           )}
		]]>
	</select>

**Comment by abel533** [comment]
你可以试试纯JDBC能获取几个结果集。
