### ISSUE TITLE
Example 支持多级嵌套吗

### ISSUE THREAD

**Issue by LaineyC** [abel533/Mapper#590]
如 WHERE ( id > ? and id < ?  or       ( id > ? and id < ? ) or ( id < ? )       ) or ( id < ? )

**Comment by zhangtke** [comment]
不完全支持，比原生mybatis原生的Example.Criteria多了一个andOr属性，所以能支持两层嵌套

**Comment by LaineyC** [comment]
thank you------------------ 原始邮件 ------------------
发件人: "zhangtke"<notifications@github.com>
发送时间: 2019年6月16日(星期天) 晚上6:29
收件人: "abel533/Mapper"<Mapper@noreply.github.com>;
抄送: "噢乖蔡"<272874065@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [abel533/Mapper] Example 支持多级嵌套吗 (#590)



不完全支持，比原生mybatis原生的Example.Criteria多了一个andOr属性，所以能支持两层嵌套
 
&mdash;
