### ISSUE TITLE
m.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2103' for key 'PRIMARY' ; SQL []; Duplicate entry '2103' for key 'PRIMARY'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2103' for key 'PRIMARY'

### ISSUE THREAD

**Issue by yang-mr** [abel533/Mapper#601]
m.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2103' for key 'PRIMARY'
; SQL []; Duplicate entry '2103' for key 'PRIMARY'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2103' for key 'PRIMARY'

**Comment by qrqhuang** [comment]
我也是服了。 issue提的这么优秀

**Comment by abel533** [comment]
主键冲突。。

确认是否存在同一个对象反复插入数据库。
