### ISSUE TITLE
可否在生成Example以及.xml时给字段加上Table Name

### ISSUE THREAD

**Issue by TheHooper** [abel533/Mapper#61]
由于不支持多表，希望EntityXXExample里的查询参数形如TableName.ColumnName 
然后.xml里的字段也带上TableName，
如此一来，在进行简单的多表操作时就会很方便。在自动生成的selectByExample上稍作修改就能用了。即便完全写Sql也有很多能复用的东西，比较方便。

**Comment by abel533** [comment]
能不能举几个例子，如果不是很有必要，不会增加这个功能。不过下一步会考虑resultMap可以被 引用。
