### ISSUE TITLE
自定义配置后,数据库字段无法转实体字段

### ISSUE THREAD

**Issue by stt824726** [abel533/Mapper#617]
自定义配置后
![image](https://user-images.githubusercontent.com/52420035/60476956-1ca0fb00-9cb0-11e9-987b-8e5f3ee351c6.png)
查询出的数据库字段无法转实体字段
![image](https://user-images.githubusercontent.com/52420035/60476889-d5b30580-9caf-11e9-84a2-7ce64d5da7a5.png)

比如p.menu_name as menuName  能查出来menuName  ，
p.parent_id 就不能查出来

**Comment by stt824726** [comment]
数据库实体对象如下
![image](https://user-images.githubusercontent.com/52420035/60478894-91773380-9cb6-11e9-9ab8-b47130b0025c.png)

**Comment by stt824726** [comment]
@abel533  大佬，能麻烦有时间看下吗？

**Comment by abel533** [comment]
mapUnderscoreToCamelCase | 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
-- | --

**Comment by abel533** [comment]
http://www.mybatis.org/mybatis-3/zh/configuration.html#settings

**Comment by stt824726** [comment]
感谢大佬知道！

**Comment by stt824726** [comment]
> http://www.mybatis.org/mybatis-3/zh/configuration.html#settings

感谢大佬指导！
