### ISSUE TITLE
无法在多分表时动态表名插入数据，支持多子类方式

### ISSUE THREAD

**Issue by leimbag** [abel533/Mapper#62]
3.3.9版本之前，有时对于相同表结构的数据（做了分表处理），在做不同分表的录入时，通过多子类方式继承父类，@Table注释在子类中，调用父类对象的mapper不能正确获得子类的@Table的表信息，导致无法动态插入不同的表的数据，demo中有没有提供这种用法的文档，望楼主考虑下，能提供支持。

**Comment by abel533** [comment]
你看看更新日志，只需要继承一个接口就能支持分表功能，不需要那么多实体类。

**Comment by leimbag** [comment]
感谢楼主提示，你说的是3.3.0版本改动中说的IDynamicTableName这个接口是吧，let me try！

**Comment by leimbag** [comment]
亲试，确实好用，使用IDynamicTableName这个接口，赞
