### ISSUE TITLE
根据实体和排序字段进行查询

### ISSUE THREAD

**Issue by wangxiaoweishy** [abel533/Mapper#63]
你好，可否添加一个根据实体里面的属性值和排序字段进行查询呢？
比如select(T entity, String fieldName, String order)，其中order值为“asc”或“desc”

**Comment by pagehelper** [comment]
用Example查询

**Comment by wangxiaoweishy** [comment]
@pagehelper 好吧，example用起来还比较麻烦，它是直接跟实体关联的，很难写一个通用的service方法去实现排序过滤查询
