### ISSUE TITLE
使用mybatis plus 与通用mapper同时使用会报无法找到绑定的值

### ISSUE THREAD

**Issue by lazyliang** [abel533/Mapper#636]
如题，这个有好的解决方法嘛？

**Comment by qrqhuang** [comment]
不太建议两套框架同时集成。
你们的如此的初衷是为啥

**Comment by xcjm820** [comment]
因为原先的项目用的plus，觉得不好用，想加这个通用mapper，又不能影响之前的代码，所以。。。。不过我的问题是两个baseMapper注册bean的时候报了bean冲突，你们又遇到这个问题吗，改扫描路径？
