### ISSUE TITLE
最新版本默认配置,实体类包含基本数据类型(int为例),无法使用insert方法插入

### ISSUE THREAD

**Issue by wzming** [abel533/Mapper#637]
high!
     `tk.mybatis.mapper.mapperhelper.resolve.DefaultEntityResolve`这个类中第78行,有个if判断逻辑,会去遍历实体类中的所有字段,判断是否为简单类型(基本类型?),看源码注释的意思是如果启用了简单类型,就会去做简单类型校验,,我这边现在使用的是2.1.5 starter,默认是启用useSimpleType的,但是DEBUG到基本类型的时候,比如int,是不会走到processField方法的,不知道是否我的理解有误,按照abel533大神的意思,如果是int的话,应该是要走processField方法的?

**Comment by diguage** [comment]
我这里也发现了这个问题：
如果Domain值是基本类型（我这里是 `int` ），插入的时候如果使用的是 `int insertSelective(T record)` 则不会处理这个基本类型的数据，换句话说这个属性被忽略了。

版本号：

```xml
<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper-spring-boot-starter</artifactId>
    <version>2.1.5</version>
</dependency>
```

**Comment by diguage** [comment]
@abel533 
这个问题啥时候能解决掉啊？能否加快一下进度？都发出来半个月了，也不见回复…

**Comment by wzming** [comment]
@diguage 估计@abel533近期可能在忙,我已经提交了一个PR,希望尽快处理,或者你这边着急的话可以按照大神的建议,尽量不要使用基本类型,而是使用包装类型

**Comment by diguage** [comment]
@wzming 
谢谢啊。我目前就是把基本类型改成包装类型了。
一个开源项目，出了Bug，半个月都没有回应，我感觉很不好。

**Comment by abel533** [comment]
SimpleType不是指的基本类型，所以 int 会跳过。。`usePrimitiveType` 是配置开启基本类型的。

这里的if写的很乱，确实存在问题，改成更容易理解的下面方式：
```java
for (EntityField field : fields) {
    //如果启用了简单类型，就做简单类型校验，如果不是简单类型，直接跳过
    //3.5.0 如果启用了枚举作为简单类型，就不会自动忽略枚举类型
    //4.0 如果标记了 Column 或 ColumnType 注解，也不忽略
    if(!config.isUseSimpleType() //关闭简单类型限制时，所有字段都处理
            || (config.isUseSimpleType() && SimpleTypeUtil.isSimpleType(field.getJavaType())) //开启简单类型时只处理包含的简单类型
            || field.isAnnotationPresent(Column.class) //有注解的处理，不考虑类型
            || field.isAnnotationPresent(ColumnType.class) //有注解的处理，不考虑类型
            || (config.isEnumAsSimpleType() && Enum.class.isAssignableFrom(field.getJavaType()))) { //开启枚举作为简单类型时处理
        processField(entityTable, field, config, style);
    }
}
```
