### ISSUE TITLE
Example example = new Example(Account.class)出现无法获取实体类对应的表名!异常

### ISSUE THREAD

**Issue by paulfrom** [abel533/Mapper#64]
加了注解@Table(name = "t_account"),配置了TypeAliasesPackage，查看entityTableMap，里面也确实有Account这个类，估计是有什么冲突吧，异常如下：
`Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: 无法获取实体类com.yifan.guimin.business.entity.Account对应的表名!] with root cause

java.lang.RuntimeException: 无法获取实体类com.yifan.guimin.business.entity.Account对应的表名!
	at tk.mybatis.mapper.mapperhelper.EntityHelper.getEntityTable(EntityHelper.java:65) ~[mapper-3.3.9.jar:na]........`

目前能够定位到底问题是Account.class 获得的地址和EntityHelper.entityTableMap里面的不一样，其他相同

**Comment by abel533** [comment]
用于 Example 中的类，必须有对应的 Mapper 接口，否则没法初始化，就找不到相应的信息。

**Comment by paulfrom** [comment]
有对应的Mapper
`public interface AccountMapper extends MyMapper<Account> {}`

MyMapper是这样定义的
`public interface MyMapper<T> extends Mapper<T>, MySqlMapper<T> `

MapperScannerConfigurer的设置是这样的
`properties.setProperty("mappers", "com.xxx.xxx.base.util.MyMapper");`

**Comment by paulfrom** [comment]
最后明确问题了，是注解@AutoConfigureAfter(MyBatisConfig.class)没有起作用，MyBatisMapperScannerConfig先于MyBatisConfig配置。
mybatis 是3.3.1,mybatis.spring是1.2.4，目前还没解决

**Comment by paulfrom** [comment]
问题解决了，是和jar包spring-boot-devtools冲突了，去掉这个包世界就清净了。。。

**Comment by paulfrom** [comment]
问题解决了，是和jar包spring-boot-devtools冲突了，去掉这个包世界就清净了。。。去

**Comment by zw23534572** [comment]
问题解决了，是和jar包spring-boot-devtools冲突了，去掉这个包世界就清净了。。。去
我是也这个问题.去他大爷的热部署

**Comment by abel533** [comment]
@zw23534572 项目首页有解决办法。

**Comment by liboxing** [comment]
maven  里面这么去的吗？ <exclusion>  
            <artifactId>？</artifactId>  
            <groupId>？</groupId>  
        </exclusion>

**Comment by itliusir** [comment]
问一个问题啊 如果我在单元测试用的
```java
@MockBean 
private XxxMapper xxxMapper;
```
在下面的service层测试(有条件查询逻辑用到了Example对象)时候会出现无法获取实体类对应的表名，`@MockBean` 改为`@Autowired`就没问题 @abel533

**Comment by zhangbohun** [comment]
使用Example或Condition 需要初始化先初始化EntityNameMap，可以在测试类代码里如下方式初始化
@Before
    public void initEntityNameMap() {
        EntityHelper.initEntityNameMap(YourEntity1.class, new Config());
        EntityHelper.initEntityNameMap(YourEntity2.class, new Config());
    }
@itliusir @abel533

**Comment by SmNiuhe** [comment]
我这边和spring-boot-devtools没啥关系，由于我是测试，没有设置@MapperScan(basePackages = "xxx.mapper")，如作者说的：用于 Example 中的类，必须有对应的 Mapper 接口，否则没法初始化，就找不到相应的信息。

**Comment by YanYii** [comment]
我这边是这样解决的。启动类的 @MapperScan 导包信息，由

**Comment by YanYii** [comment]
我这边是这样解决的。启动类的 @MapperScan 导包信息，由
import org.mybatis.spring.annotation.MapperScan;
修改为（tk包下的MapperScan）：
import tk.mybatis.spring.annotation.MapperScan;

**Comment by JackrayWang** [comment]
@YanYii  但是写测试用例呢

**Comment by JackrayWang** [comment]
使用spock 写测试用例 执行到example的时候一直报错 找不到table

**Comment by wujinjian1988** [comment]
是因为热部署导致的，mybatis对热部署支持不好，因为mybatis对旧的mapper有缓存，热加载后 用新的mapper去查查不到类
