### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jsxiao** [abel533/Mapper#642]
1

**Comment by jsxiao** [comment]
而且在spring-boot中引入了mapper-spring-boot-starter 
完全按照文档中配置的，启动时提示 ` 只有 Spring Boot 环境中可以通过 Environment(配置文件,环境变量,运行参数等方式) 配置通用 Mapper，其他环境请通过 @MapperScan 注解中的 mapperHelperRef 或 properties 参数进行配置!如果你使用 tk.mybatis.mapper.session.Configuration 配置的通用 Mapper，你可以忽略该错误! `

真是无语了。

**Comment by jsxiao** [comment]
你这东西是玩具吧？ 有没有经过测试？ 还是仅仅是你自己本机好使?

**Comment by jsxiao** [comment]
> 1

**Comment by xiang87871** [comment]
人家又没逼你用

发自我的 iPhone
