### ISSUE TITLE
updateByPrimaryKeySelective 无法更新值为 "" 的字段

### ISSUE THREAD

**Issue by lzwill** [abel533/Mapper#645]
如下图，在使用 updateByPrimaryKeySelective 方法时无法更新空字符串(非null)字段。

![image](https://user-images.githubusercontent.com/22948246/63397956-acd10600-c3fe-11e9-9d64-896b7eadc230.png)

打印出来的语句是这样的：

![image](https://user-images.githubusercontent.com/22948246/63397993-c3775d00-c3fe-11e9-8734-d9c8b7140251.png)

可以看到 `remark` 字段没有被更新，这与方法注释中的描述 `根据主键更新属性不为null的值` 不符啊，请问大佬这是是注释错误还是实现有问题啊。

使用版本为
``` xml
<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper-spring-boot-starter</artifactId>
    <version>2.1.5</version>
</dependency>
```

希望大佬解答

**Comment by lzwill** [comment]
对了，我使用的版本号是 `mapper-spring-boot-starter:2.1.5`

**Comment by 1996yarbrough** [comment]
是呀，这个设计的有问题啊，而且和注释不符

**Comment by 1996yarbrough** [comment]
> 如下图，在使用 updateByPrimaryKeySelective 方法时无法更新空字符串(非null)字段。
> 
> ![image](https://user-images.githubusercontent.com/22948246/63397956-acd10600-c3fe-11e9-9d64-896b7eadc230.png)
> 
> 打印出来的语句是这样的：
> 
> ![image](https://user-images.githubusercontent.com/22948246/63397993-c3775d00-c3fe-11e9-8734-d9c8b7140251.png)
> 
> 可以看到 `remark` 字段没有被更新，这与方法注释中的描述 `根据主键更新属性不为null的值` 不符啊，请问大佬这是是注释错误还是实现有问题啊。
> 
> 使用版本为
> 
> ```
> <dependency>
>     <groupId>tk.mybatis</groupId>
>     <artifactId>mapper-spring-boot-starter</artifactId>
>     <version>2.1.5</version>
> </dependency>
> ```
> 
> 希望大佬解答

我也遇到这个问题了，后来debug了一遍代码，有个notEmpty这个属性设置，你看你是不是设置成true了，默认是false的，代码在tk.mybatis.mapper.provider.base.BaseUpdateProvider

**Comment by lzwill** [comment]
@1996yarbrough 确实是因为加了 `notEmpty: true` 这个配置，非常感谢！:)
