### ISSUE TITLE
实体中字段有java.sql.Time，但是查询的时候没有查询该字段

### ISSUE THREAD

**Issue by HuangDayu** [abel533/Mapper#648]
比如 我有个实体类
```java
Long id;
String name;
java.sql.Time time;
```

使用selectOneByExample（）方法，查询所有字段的时候，SQL语句如下：
```sql
SELECT id,name FROM t_aa WHERE ( ( id = ? ) ) 
```

可以看出，少了time字段。是什么原因呢？谢谢。

**Comment by wz2cool** [comment]
我在想是不是对 java.sql 包 支持的不好， 我自己的 java.sql.Date 也是拿不到， 兄弟在  time 上加上一个 @Column 注解看一下

**Comment by HuangDayu** [comment]
@wz2cool 这个没试过，大概率是无效的。我现在用String类型了

**Comment by wz2cool** [comment]
@HuangDayu 兄弟你可以试试看，我也是找了试了好久才发现要用 @Column 强制声明， 因为我自己写了一个基于tk.mapper 的扩展插件所以试了很多

**Comment by HuangDayu** [comment]
@wz2cool 好的，謝謝

**Comment by HuangDayu** [comment]
> @HuangDayu 兄弟你可以试试看，我也是找了试了好久才发现要用 @Column 强制声明， 因为我自己写了一个基于tk.mapper 的扩展插件所以试了很多， 我的bug 在这里 #654 

这个需求我又遇到了😁，mysql类型是time，JAVA对应类型是string就可以了😊

**Comment by wz2cool** [comment]
> > @HuangDayu 兄弟你可以试试看，我也是找了试了好久才发现要用 @column 强制声明， 因为我自己写了一个基于tk.mapper 的扩展插件所以试了很多， 我的bug 在这里 #654
> 
> 这个需求我又遇到了，mysql类型是time，JAVA对应类型是string就可以了

老哥 你用 string 是弱类型啊，真的不考虑用 @Column 么

**Comment by HuangDayu** [comment]
> > > @HuangDayu 兄弟你可以试试看，我也是找了试了好久才发现要用 @column 强制声明， 因为我自己写了一个基于tk.mapper 的扩展插件所以试了很多， 我的bug 在这里 #654
> > 
> > 这个需求我又遇到了，mysql类型是time，JAVA对应类型是string就可以了
> 
> 老哥 你用 string 是弱类型啊，真的不考虑用 @Column 么

http请求提交也是字符串，判断一下格式，目前一直用着，还未发现问题。
