### ISSUE TITLE
insertUseGeneratedKeys 在主键名不为id的情况下，使用getter取到的主键值为空

### ISSUE THREAD

**Issue by sirs05** [abel533/Mapper#67]
配置如下：

>         <table tableName="video_session">
>             <generatedKey column="sessionid" sqlStatement="Mysql" identity="true"/>
>         </table>

代码如下：
        videoSessionMapper.insertUseGeneratedKeys(vs);
        logger.info("vs id:{}", vs.getSessionid());

取到的主键为null

**Comment by sirs05** [comment]
产生的model似乎也没什么问题。。

@Table(name = "video_session")
public class VideoSession {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long sessionid;

**Comment by abel533** [comment]
`insertUseGeneratedKeys` 这个方法注释有说明，由于注解限制为 id，其他情况不适用，除非有统一主键名称的情况下，否则不推荐类似方式。

**Comment by sirs05** [comment]
谢谢
