### ISSUE TITLE
Controller里面调用泛型Service报java.lang.ClassCastException错误

### ISSUE THREAD

**Issue by liaow** [abel533/Mapper#68]
java.lang.ClassCastException: com.xxx.domain.business.FileInfo cannot be cast to 
com.xxx.domain.business.FileInfo

===Service泛型注入写法
@Service
public abstract class BaseService<T>{

    @Autowired
    protected com.xxx.utils.BaseMapper<T> mapper; 
   ...
}
===FileInfoService代码
@Service
public class FileInfoService extends BaseService<FileInfo>{
    ...
}
===Controller报错处
FileInfo info = fileInfoService.selectByPrimaryKey(fileId);
===Mapper代码
public interface FileInfoMapper extends BaseMapper<FileInfo> {
}

**Comment by abel533** [comment]
不支持热部署，排除 domain 目录即可。

**Comment by liaow** [comment]
顺便请教一下：mybatis-spring-boot-starter 是不是也可以不依赖呢？

**Comment by abel533** [comment]
如果你依赖了 mapper-spring-boot-starter，这个会依赖 mybatis 的 starter，不用手动指定这个。

**Comment by liaow** [comment]
谢谢，确实是热部署的问题
