### ISSUE TITLE
希望增加example可以构建自定义的查询条件

### ISSUE THREAD

**Issue by bushuang** [abel533/Mapper#7]
oracle下，假如CREATE_DATE字段是DATE类型，用example构建查询条件，当传入的参数为java.util.Date时，oracle会自动使用to_timestamp函数，这样就不会走CREATE_DATE这个字段的索引，而且使用druid打印出的可执行的sql是有问题的，
所以希望增加一个方法，可以传入一个自定义的子句，方便使用oracle的函数之类的

**Comment by abel533** [comment]
可以增加类似方法，等考虑好对Example的各种修改后会尝试增加。

**Comment by abel533** [comment]
已经添加，请关注最新的3.3.0版本(未发布).

3.3.0变化：http://git.oschina.net/free/Mapper/issues/64
