### ISSUE TITLE
代码生成器  使用自定义 templatePath 无法生成

### ISSUE THREAD

**Issue by anylys** [abel533/Mapper#701]
<plugin type="tk.mybatis.mapper.generator.TemplateFilePlugin">
            <property name="targetProject" value="src/main/resources"/>
            <property name="targetPackage" value="mapper.cdr"/>
            <property name="mapperPackage" value="com.yzx.cdr.mapper"/>
            <property name="templatePath" value="mygenerator/mapperXml.ftl"/>
            <property name="mapperSuffix" value="Mapper"/>
            <property name="fileName" value="${tableClass.shortClassName}${mapperSuffix}.xml"/>
        </plugin>

提示
java.net.MalformedURLException: no protocol: generator/mymapper.ftl
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at tk.mybatis.mapper.generator.TemplateFil

**Comment by anylys** [comment]
我配置mapps  <plugin type="tk.mybatis.mapper.generator.MapperPlugin">
            <property name="mappers"
                      value="tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.special.InsertListMapper"/>
            <property name="lombok" value="Getter,Setter,ToString"/>
            
            <property name="caseSensitive" value="false"/>
            
            <property name="forceAnnotation" value="true"/>
            
            <property name="generateColumnConsts" value="true"/>
            <property name="beginningDelimiter" value="`"/>
            <property name="endingDelimiter" value="`"/>
        </plugin> 

但是生成的mapper接口缺没有.

我是项目集成了mapper的包.

**Comment by abel533** [comment]
通常是类加载器的问题，ftl所在jar包至少install到本地。。

另外用idea的情况下，可以debug加断点看看为什么找不到文件。

**Comment by anylys** [comment]
这不是bug,配置问题.
