### ISSUE TITLE
selectByPrimaryKey问题

### ISSUE THREAD

**Issue by sufeng** [abel533/Mapper#71]
只要引用 springboot 1.4.3  dev-tools 

调userMapper.selectByPrimaryKey(id)方法 出错

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: demo.mybatis.mapper.entity.User cannot be cast to demo.mybatis.mapper.entity.User] with root cause

java.lang.ClassCastException: demo.mybatis.mapper.entity.User cannot be cast to demo.mybatis.mapper.entity.User

/**
     * 获取单个用户
     *
     * @param id uid
     * @return 1
     */
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public User Get(@PathVariable Long id) {
        return userMapper.selectByPrimaryKey(id);
    }

**Comment by sufeng** [comment]
去掉 devtools 就可以 不知道什么原因

**Comment by abel533** [comment]
通用Mapper不支持热加载。。配置devtools 排除实体类即可。

**Comment by fanxl12** [comment]
我也遇到了，devtools怎么排除实体类@abel533

**Comment by abel533** [comment]
http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload

**Comment by fanxl12** [comment]
@abel533 看的不怎么明白，是直接排除包名？
`devtools:
    restart:
      exclude: com.agitation.hisport.entity
`

**Comment by abel533** [comment]
排除 jar 包。不是包名。

**Comment by fanxl12** [comment]
@abel553 我自己创建的实体类，哪里有jar包？

**Comment by abel533** [comment]
如果只有 classes，就把 devtool 去掉吧，反正不好使，不如 jrebel 一类的。
