### ISSUE TITLE
关于默认使用乐观锁的场景

### ISSUE THREAD

**Issue by DawnSouther** [abel533/Mapper#717]
**是否不根据主键进行的update或delete不需要添加乐观锁？**

wiki上写着这些方法在启用乐观锁时自动添加版本号更新。
- delete
- deleteByPrimaryKey
- updateByPrimaryKey
- updateByPrimaryKeySelective
- updateByExample
- updateByExampleSelective
在一个普通的头行结构的业务中，经常会出现根据头id去更新行上的某些字段或删除某些行，这种时候不适用与乐观锁，想用乐观锁就必须要把版本号查出来？
我的理解是，主键和乐观锁是配套使用的，如果不根据主键进行更新，乐观锁就没有使用的必要。

另外，是否有办法屏蔽掉以上某些方法中的乐观锁？

**Comment by abel533** [comment]
建议不直接使用mapper提供的乐观锁，自己在业务层封装。
