### ISSUE TITLE
如何结合select和selectByExample进行查询

### ISSUE THREAD

**Issue by 565444118** [abel533/Mapper#72]
List<T> select(T record);
List<T> selectByExample(T example);
我的需求大概是这样的，大部分的查询条件都是等号比较，所以想用select，但是因为排序是动态的，所以又觉得该用selectByExample，不知道有没有办法结合一下？求赐教

**Comment by abel533** [comment]
Example 有个方法可以传入 Entity，并且都是用等号比较。

**Comment by WangJincheng4869** [comment]
> Example 有个方法可以传入 Entity，并且都是用等号比较。

大佬，这个方法是哪个啊？木有找到啊。
