### ISSUE TITLE
当Example.Criteria未设置where条件直接查询时，带有逻辑删除注解的表会报错

### ISSUE THREAD

**Issue by cqsongjin** [abel533/Mapper#722]
`Example example = new Example(LogicDeleteTable.class);`
`Example.Criteria criteria = example.createCriteria();`
`logicDeleteTableService.selectByExample(example);`
如上代码所示，criteria 未设置任何查询条件，当LogicDeleteTable存在逻辑删除注解时，会报错。
生成的SQL语法有误：select count(0) from (SELECT `id`,`code`,`pid`,`name`,`level`,`create_time`,`update_time`,`del_flag` FROM `logic_delete_table` WHERE `del_flag` = 0 and) tmp_count
报错信息如下：
Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') tmp_count' at line 1

**Comment by dinghongfei** [comment]
因为项目中依赖的是 mapper-spring-boot-starter ，版本2.1.5，在这个版本上还未解决，能否发一版新的starter 到中央仓库 @abel533
