### ISSUE TITLE
4.1.5 版本 NoSuchMethodException异常

### ISSUE THREAD

**Issue by Imagoodboy** [abel533/Mapper#726]
前提
1.mapper版本4.1.5
2.mapperScan 使用mybatis

`interface IMapper<T> extends Mapper<T>, OracleMapper<T>`
形如如上接口，不包含自定义扩展，无异常。
```
public interface IMapper<T> extends Mapper<T>, OracleMapper<T> {
    @SelectProvider(type = ISelectProvider.class, method = "dynamicSQL")
    String selectMaxByPrimaryKey();
}
```
形如如上自定义扩展，抛NoSuchMethodException异常（所有方法）

解决办法：mapperScan 使用tk 
（但是看wiki, 4.x 版本已经修复此类常见异常?

**Comment by abel533** [comment]
给这个接口增加 `@RegisterMapper` 注解，这时会因为是父类接口，会避免实例化该接口。
