### ISSUE TITLE
有没有Mapper各个方法的使用demo啊

### ISSUE THREAD

**Issue by fanxl12** [abel533/Mapper#73]
看了文档上面关于Mapper的一些使用，但是不全，没有说明的不知道该如何使用，比如我想更新实体类里面的部分字段，看到应该是使用updateByExample方法，但是不知道Example，尝试了几次都不成功。
`
Example example = new Example(Region.class);
        example.selectProperties("updateDate", "name").createCriteria()
                .andCondition("id="+region.getId());
`

**Comment by abel533** [comment]
selectProperties 这个是设置查询属性的，和更新无关。
更新部分字段用带 Selective 的方法就行，看全部方法介绍。
https://github.com/abel533/Mapper/blob/master/wiki/mapper3/5.Mappers.md

**Comment by fanxl12** [comment]
好的，感谢，我看看使用
