### ISSUE TITLE
Mapper泛型不适用实体类，使用HashMap 是否支持？

### ISSUE THREAD

**Issue by lhqiang** [abel533/Mapper#76]
Mapper泛型不使用实体类，使用HashMap 是否支持？

**Comment by IrvingZhao** [comment]
弱弱的问一句，你说的不适用是指哪方面，我用这个工具做过基于spring4的泛型注入mapper

**Comment by lhqiang** [comment]
不适用实体类，想使用HashMap作为泛型。第一次错别字不是不适用

**Comment by IrvingZhao** [comment]
你都不用实体类了，肯定就不会用映射了，既然这样，直接在xml中，添加一个select不就行了，然后映射到Mapper中的方法，直接返回HashMap，或者是List<HashMap> 之类的内容。
你这是自动档习惯了，手动挡就忘了啊

**Comment by abel533** [comment]
可以是继承 Map 的实体，可以通过set,get 方法指定字段。

**Comment by IrvingZhao** [comment]
能问一下你这么做的应用场景是什么啊

**Comment by lhqiang** [comment]
好的， 之前项目都取消了实体类。我就想试一下查件能否可以。。。
