### ISSUE TITLE
JDK9+之后，MyBatis3.4版本有一个警告

### ISSUE THREAD

**Issue by long-jie** [abel533/Mapper#771]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/D:/mavenRepository/org/mybatis/mybatis/3.4.6/mybatis-3.4.6.jar) to method java.lang.Class.checkPackageAccess(java.lang.SecurityManager,java.lang.ClassLoader,boolean)
WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by uniquejava** [comment]
这个要怎么解决

**Comment by abel533** [comment]
看文档：
https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B

找到下面这部分内容

## Understanding Runtime Access Warnings
Some tools and libraries use reflection to access parts of the JDK that are meant for internal use only. This illegal reflective access will be disabled in a future release of the JDK. In JDK 9, it is permitted by default and a warning is issued.

For example, here is the warning issued when starting Jython:
```bash
>java -jar jython-standalone-2.7.0.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/Jython/jython2.7.0/jython-standalone-2.7.0.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
```

**Comment by uniquejava** [comment]
> 看文档：
> https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B
> 
> 找到下面这部分内容
> 
> ## Understanding Runtime Access Warnings
> Some tools and libraries use reflection to access parts of the JDK that are meant for internal use only. This illegal reflective access will be disabled in a future release of the JDK. In JDK 9, it is permitted by default and a warning is issued.
> 
> For example, here is the warning issued when starting Jython:
> 
> ```shell
> >java -jar jython-standalone-2.7.0.jar
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/C:/Jython/jython2.7.0/jython-standalone-2.7.0.jar) to method sun.nio.ch.SelChImpl.getFD()
> WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
> ```

可以升级mapper-spring-boot对应的mybatis依赖吗。 这个mapper-spring-boot 2.1.5对应mybatis3.4.6, 而mybatis在3.5.0版本中修复了这个警告。see https://blog.mybatis.org/2019/01/mybatis-350-released.html

**Comment by uniquejava** [comment]
@abel533 解决了， 加了如下配置到pom里。 启动时就没有警告了。

```xml
        <!-- https://mvnrepository.com/artifact/org.mybatis/mybatis -->
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>3.5.7</version>
        </dependency>
```
