### ISSUE TITLE
使用Postgresql新增操作，返回错误last_insert_id() does not exist

### ISSUE THREAD

**Issue by malinghan** [abel533/Mapper#79]
org.postgresql.util.PSQLException: ERROR: function last_insert_id() does not exist

**Comment by abel533** [comment]
LAST_INSERT_ID 是 mysql 方法，postgresql 只能支持自增，并且名字是 id 的主键。

**Comment by malinghan** [comment]
Postgresql获取主键策略
`<selectKey resultType="java.lang.Long"  order="AFTER" keyProperty="id" >
            SELECT currval('seq_user_id') AS id  
        </selectKey>`
插入策略
`INSERT INTO tb_user( id, name) VALUES (nextval('seq_user_id'), #{name})`
感觉支持不太好
