### ISSUE TITLE
表字段已经用驼峰式命名时的一个问题~~

### ISSUE THREAD

**Issue by blacklong** [abel533/Mapper#8]
表字段，本身已经是驼峰式命名，如orderId，
在generator.xml中，我这样写
生成...table tableName="order_settlement_daily" domainObjectName="OrderSettlementDaily" ... 》
			《property value="true" name="useActualColumnNames"/》
即使用真实字段名，生成的bean属性即为orderId
-------------------------------------------

问题：
因为bean属性与真实字段名一致，所以没有生成@Column注释，
所以，拼接sql时，会拼成order_id，导致失败。
我现在是修改了MapperCommentGenerator.java，
        //if (!column.equals(introspectedColumn.getJavaProperty())) {
            //@Column
            field.addAnnotation("@Column(name = \"" + column + "\")");
        //}
把判断注释掉了，始终生成@Column注解，就没问题了。

**Comment by abel533** [comment]
新版有一个NameStyle注解可以配置转换规则，你可以看看更新日志。
