### ISSUE TITLE
对于有参数的TypeHandler()的处理

### ISSUE THREAD

**Issue by loveinliuy** [abel533/Mapper#81]
对于`Mybatis`的`EnumTypeHandler`和`EnumOrdinalTypeHandler`的构造函数是有参数的，不像其他`BooleanTypeHandler`的构造函数是无参数的。
在代码 `EntityTable#202`行处采用
```
builder.typeHandler(entityColumn.getTypeHandler().newInstance());
```
这种方式是无法构造出相应对象的。

**Comment by abel533** [comment]
建议配置全局的

2017-03-01 14:20 GMT+08:00 Zhang Shibo <notifications@github.com>:

**Comment by loveinliuy** [comment]
但是当自定义的枚举类型增多的时候，配置全局的方式看起来就不是那么完美了。

**Comment by abel533** [comment]
你可以试试 `@ColumnType` 注解。

**Comment by loveinliuy** [comment]
你的这个注解在 对列是枚举类型的时候，就没有作用的，因为反射出来的内容是没有泛型的
