### ISSUE TITLE
乐观锁不生效

### ISSUE THREAD

**Issue by dinghongfei** [abel533/Mapper#818]
使用的依赖是
<dependency>
    <groupId>tk.mybatis</groupId>
    <artifactId>mapper-spring-boot-starter</artifactId>
    <version>2.1.5</version>
</dependency>

实体继承的基类
![image](https://user-images.githubusercontent.com/24501314/112628215-8b9f8980-8e6d-11eb-8932-6d956093dc08.png)

更新代码
![image](https://user-images.githubusercontent.com/24501314/112628277-a2de7700-8e6d-11eb-9608-48a877f80ec7.png)

更新后 version 字段没有 +1

debug代码到这里
![image](https://user-images.githubusercontent.com/24501314/112628564-07013b00-8e6e-11eb-8170-12d1353b14b7.png)

发现是没有拿到@Version注解

一直找不到原因，请求帮助一下。

**Comment by AlfredNing** [comment]
你是如何解决的乐观锁
