### ISSUE TITLE
4.1.5版本，代码生成器指定mappers无效

### ISSUE THREAD

**Issue by chentianming11** [abel533/Mapper#829]
![image](https://user-images.githubusercontent.com/30620547/125441864-4210e35d-66b0-4d77-817f-302bc8bfcaed.png)
mappers指定为自定义Mapper，但是生成的代码还是tk.mybatis.mapper.common.Mapper
![image](https://user-images.githubusercontent.com/30620547/125442160-6945ef0d-48bd-4862-8921-bebc7ff57285.png)

**Comment by micy0706** [comment]
目前最新版还有这个问题
