### ISSUE TITLE
2021了大哥

### ISSUE THREAD

**Issue by wajncn** [abel533/Mapper#831]
![image](https://user-images.githubusercontent.com/37337912/125769581-9e84e5a1-46e4-4bba-b28c-5a60b9f2a401.png)

**Comment by abel533** [comment]
可以先关注一下：https://github.com/mybatis-mapper/mapper

会尽快发布正式版。

**Comment by wajncn** [comment]
建议
1.逻辑删除可以兼容唯一索引。
2.尽可能的不要过度封装。 能用javax的注解就用。
3.关于泛型的描述不要太过简单。 比如 <T,ID> 就不要写成<T,I>


Liuzh ***@***.***> 于2021年7月29日周四 下午4:26写道：

**Comment by ghxiaoym** [comment]
在哪里可以查到兼容性，目前我们用的是springboot 2.4.5,tk >mapper-spring-boot-starter用的2.1.5，这2个版本兼容吗

**Comment by wajncn** [comment]
我看源码里面删除是1 没删除是0      这样会和唯一索引起冲突的.
ghxiaoym ***@***.***> 于2021年8月9日周一 下午5:18写道：

**Comment by abel533** [comment]
1.0.0正式版已经发布，等准备好官网再发通知。

**Comment by wajncn** [comment]
挂到我的网上不.  免费的.     https://javanet123.com

Liuzh ***@***.***> 于2021年8月10日周二 下午1:35写道：

**Comment by wajncn** [comment]
https://mapper.mybatis.io/
这种网站我看很多相似的.  这个是开源的改的 还是自己开发的?

>

**Comment by abel533** [comment]
@wajncn 用的 vuepress

**Comment by wajncn** [comment]
这个项目能和tkmapper 一起使用吗?
  我司项目中已经使用了tkmapper 了.   我想把这个mapper项目给集成进来. 会有影响吗 ?

**Comment by abel533** [comment]
@wajncn 能一起使用，没有冲突

**Comment by uniquejava** [comment]
> @wajncn 能一起使用，没有冲突
JDK11 启动报警告怎么破 An illegal reflective access operation has occurred

**Comment by abel533** [comment]
@uniquejava jdk11有很多安全方面的设计，需要自己通过参数控制。
