### ISSUE TITLE
与springboot集成,mapper.mappers 配置项异常

### ISSUE THREAD

**Issue by Linfini** [abel533/Mapper#836]
mapper-spring-boot-starter 版本:2.1.5

yml配置:
```yaml
mapper:
  mappers: com.xxx.MyMapper # MyMapper继承 tk.mybatis.mapper.common.Mapper.Mapper
  not-empty: false  
  identity: MYSQL
```
启动时抛错:
```
Description:
Failed to bind properties under 'mapper.mappers' to java.util.List<java.lang.Class<?>>:
    Reason: No converter found capable of converting from type [java.lang.String] to type [java.util.List<java.lang.Class<?>>]
```

**Comment by abel533** [comment]
集合写法：
```yaml
mapper:
  mappers: 
    - com.xxx.MyMapper
  not-empty: false  
  identity: MYSQL
```

**Comment by Linfini** [comment]
> 集合写法：
> 
> ```yaml
> mapper:
>   mappers: 
>     - com.xxx.MyMapper
>   not-empty: false  
>   identity: MYSQL
> ```
改成数组写法了 
Failed to bind properties under 'mapper.mappers[0]' to java.lang.Class<?>:

    Property: mapper.mappers[0]
    Value: com.xxx.MyMapper
    Origin: class path resource [application.yml]:30:7
    Reason: No converter found capable of converting from type [java.lang.String] to type [java.lang.Class<?>]

**Comment by Linfini** [comment]
找到原因了,maven 依赖的问题.原来是 SpringBoot App启动类所在的模块,没有引用到tk mapper的包,多用maven编译几次就好了.
