### ISSUE TITLE
updateByPrimaryKeySelective方法执行时筛选的包括不为null同时不为""的情况

### ISSUE THREAD

**Issue by JohnHello** [abel533/Mapper#84]
updateByPrimaryKeySelective方法执行时筛选的包括不为null同时不为""，但是大部分情况下只筛选出不为NULL就可以了，为""的情况下不需要筛选。我用的时候定制了一个新的mapper，加入到拦截器中。最好您的mapper里面再放开一个这个接口。

**Comment by JohnHello** [comment]
在Config类中配置 config.setNotEmpty(false);

**Comment by william-abel** [comment]
> 在Config类中配置 config.setNotEmpty(false);

 config.setNotEmpty(false); 在哪里??
