### ISSUE TITLE
@Column定义字段取值问题

### ISSUE THREAD

**Issue by liaow** [abel533/Mapper#85]
因业务需要有以下代码：
`
    @Column(name = "user_name")
    private String nickName;//姓名
    private String username;//用户账号
`
使用selectByPrimaryKey、selectOne这些通用的方法可以正确映射数据字段，但是使用自己写的Mapper（SqlProvide）就会把user_name字段的值映射到username上去。
请问这是哪里出现了问题？

**Comment by abel533** [comment]
自己写还得处理映射。

**Comment by liaow** [comment]
框架是什么做到？想找到源码学习下

**Comment by abel533** [comment]
框架生成的sql是 select user_name nickname, ... 用的别名。
