### ISSUE TITLE
框架版本支持问题迷惑

### ISSUE THREAD

**Issue by liuyandeng** [abel533/Mapper#866]
我们系统的mybatis是3.2.2,我看到wiki上说的是通用 Mapper 支持 MyBatis 3.2.4+,所以我就私自升级了公司框架两个小的版本号到3.2.5,解决了一些版本问题后,可以进行CRUD,我又把mybatis版本还原到3.2.2,发现CRUD依然好使!
我对此感到迷惑,3.2.2低于要求的3.2.4,依然可以运行,如果不升级到高于规定的版本可以吗,会有什么潜在的问题,如果不升级也能使用,还是倾向于不动公司框架的版本号!
版本
![image](https://user-images.githubusercontent.com/19473507/189787473-15793f88-57c2-40b5-ac24-991cf2a9256b.png)
功能
![image](https://user-images.githubusercontent.com/19473507/189787495-c7325389-4758-4244-bfb7-2a7284a947fc.png)
wiki
![image](https://user-images.githubusercontent.com/19473507/189787553-0a3f2672-9e5a-46f8-8e8a-65807028cf22.png)

**Comment by abel533** [comment]
gitee回复。

**Comment by liuyandeng** [comment]
https://gitee.com/free/Mapper/issues/I5QP9W

**Comment by liuyandeng** [comment]
https://gitee.com/free/Mapper/issues/I5QTHW
