### ISSUE TITLE
mapper-spring-boot-starter:1.1.0依赖的mapper版本不是3.4.0

### ISSUE THREAD

**Issue by bohrqiu** [abel533/Mapper#87]

**Comment by abel533** [comment]
https://github.com/abel533/mapper-boot-starter/blob/master/pom.xml

是 3.4.0.

**Comment by bohrqiu** [comment]
mapper-spring-boot-starter 1.1.0继承了

<parent>
        <groupId>tk.mybatis</groupId>
        <artifactId>mapper-spring-boot</artifactId>
        <version>1.0.0</version>
    </parent>

**Comment by abel533** [comment]
确实是错了。。

**Comment by bohrqiu** [comment]
谢谢你开源这个项目
