### ISSUE TITLE
insertList有插入条数限制吗？版本：mapper-extra:4.2.1

### ISSUE THREAD

**Issue by kyle-gta** [abel533/Mapper#870]
如题, 请问版本：tk.mybatis: mapper-extra:4.2.1这个版本insertList批量插入是否有插入限制？

**Comment by abel533** [comment]
数据库有限制，业务上可以分批操作。

**Comment by kyle-gta** [comment]
> 

请问是否是限制1000条？

**Comment by kyle-gta** [comment]
> 数据库有限制，业务上可以分批操作。

好的谢谢👍
