### ISSUE TITLE
Invalid property 'mapperHelper' of bean class [org.mybatis.spring.mapper.MapperFactoryBean]: Bean property 'mapperHelper' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?  

### ISSUE THREAD

**Issue by UltramanNoa** [abel533/Mapper#885]
新增子模块后  MybatisConfiguration里的配置：
@MapperScans({@MapperScan("net.axx.bxx.*.mapper"),@MapperScan("net.axx.bxx.xxx.*.mapper")})
MapperScannerConfigurer里的配置：
mapperScannerConfigurer.setBasePackage("net.axx.bxx.*.mapper,net.axx.bxx.xxx.*.mapper");  配置这些之后启动就报这个错  项目里没有用到热部署插件

**Comment by abel533** [comment]
用错注解了，注意包名。
https://github.com/abel533/Mapper/blob/master/spring/src/main/java/tk/mybatis/spring/annotation/MapperScan.java
