### ISSUE TITLE
不支持devtools热加载的原因是？

### ISSUE THREAD

**Issue by baihe** [abel533/Mapper#90]
表面来看是因为在定位class的地方（如MapperTemplate的 getMapperClass）直接调用了 Class.forName() 而不是使用了上下文的classloader， 导致一连串的类型判断因为classloader不同而失败。替换了这些加载方法后就可以使用了。
所以想问一下，没有使用上下文的classloader是因为考虑到了什么隐患或者其他什么问题吗？

**Comment by emf1002** [comment]
spring-devtools.properties如下配置后可以热加载
restart.include.mapper=/mapper-[\\w-\\.]+jar
restart.include.pagehelper=/pagehelper-[\\w-\\.]+jar

**Comment by abel533** [comment]
@emf1002 非常感谢，项目文档首页已添加相关配置介绍。

**Comment by baihe** [comment]
但还是没有解释为什么不用上下文 classloader 的原因，是因为要避免什么潜在的问题么？

**Comment by abel533** [comment]
@baihe 看这里：http://blog.csdn.net/isea533/article/details/70495714
