### ISSUE TITLE
咨询下Mapper最新版本4.2.3是否支持JDK17？还是待4.3.0版本发布后才会支持？

### ISSUE THREAD

**Issue by Mrliu1102** [abel533/Mapper#907]

**Comment by ccfish86** [comment]
头疼，
明明开发环境好好的，发服务器上就起不来，提示：
![image](https://github.com/abel533/Mapper/assets/15622514/1d951eb4-f026-4212-a743-7251add60070)

```
dependency 'tk.mybatis:mapper-spring-boot-starter:4.2.3'
dependency 'tk.mybatis:mapper:4.2.3'
```

**Comment by xiaobaogeit** [comment]
经过测试可以正常使用，只是会导致javax、jakarta共存，如果需要去掉则需要自行修改了，或者等新版本。

**Comment by abel533** [comment]
如果同时支持JDK8和JDK17就需要维护两个版本，后续考虑先把JDK最低版本升级到8，等PR和issues处理差不多后再考虑JDK17，如果大家有兴趣参与，也可以考虑提前创建jdk17分支同时进行。

**Comment by xiaobaogeit** [comment]
> 如果同时支持JDK8和JDK17就需要维护两个版本，后续考虑先把JDK最低版本升级到8，等PR和issues处理差不多后再考虑JDK17，如果大家有兴趣参与，也可以考虑提前创建jdk17分支同时进行。

建议开启一个`jdk17`分支，这个从目前`Sping Boot 2.7.x`支持周期来看还是尽早为好。

**Comment by abel533** [comment]
5.0.0-rc2 可以试用。
