### ISSUE TITLE
use   PasswordEncoder passwordEncoder  An error occurred

### ISSUE THREAD

**Issue by itl-coder** [abel533/Mapper#921]
@Autowired
private PasswordEncoder passwordEncoder;

public void InitUserInfo() {
        log.info("init auth userInfo.............................");

        SysUser sysUser = new SysUser();
      
        String encode = passwordEncoder.encode("1234");
        sysUser.setId(1);
        sysUser.setUsername("user");
          // TODO:  java.lang.IllegalArgumentException: Illegal group reference
        sysUser.setPassword(encode);
        sysUserMapper.updateById(sysUser);
    }

**Comment by abel533** [comment]
执行的时机过早导致的，可以试试lazy能不能行，如果不行，就把这部分方法单独提供，不用通用方法。
