### ISSUE TITLE
版本升级到5.0.0 构建失败

### ISSUE THREAD

**Issue by SouperGeng** [abel533/Mapper#923]
项目引用 version 为RELEASE，使用最新5.0.0 报错，使用4.3.0不报错，目前已降级

错误日志

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project ***: Compilation failure
[ERROR] /home/***.java:[5,32] cannot access tk.mybatis.mapper.common.Mapper
[ERROR]   bad class file: /root/.m2/repository/tk/mybatis/mapper-base/5.0.0/mapper-base-5.0.0.jar(tk/mybatis/mapper/common/Mapper.class)
[ERROR]     class file has wrong version 61.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by galaxy-sea** [comment]
请使用jdk 17 编译
