### ISSUE TITLE
5.0.0 自定义Mapper继承通用Mapper扩展方法如果没实现会报错

### ISSUE THREAD

**Issue by kalvan2019** [abel533/Mapper#924]
**代码示例** ：
```
@RegisterMapper
public interface IBaseMapper<T> extends ShardingMapper<T>, MySqlMapper<T> {
 /**
     * 汇总查询
     *
     * @param params 查询参数
     * @return Map
     */
    Map<String, String> querySumMap(@Param("params") Map<String, Object> params);
}
@Repository
public interface TestMapper extends IBaseMapper<Test> {

}
```

 **问题** ：原来版本4.2.2有判断处理，没有的方法就不去注册，兼容支持，现在5.0.0不支持

![image](https://github.com/user-attachments/assets/5cf6f4a2-c8e1-4a94-bd33-1461e7120e96)

 **临时解决方案** ：
本地项目中重写MapperHelper 临时解决
 
![image](https://github.com/user-attachments/assets/b14f6cab-3197-4f05-a9c0-4635fa9a34a3)

**Comment by kalvan2019** [comment]
移除IBaseMapper 类上的 @RegisterMapper

**Comment by kalvan2019** [comment]
IBaseMapper去掉 @RegisterMapper

**Comment by kalvan2019** [comment]
自定义 的IBaseMapper去掉@RegisterMapper

**Comment by abel533** [comment]
![FRH2MRYQQ$K3H3{80Z$J PG](https://github.com/user-attachments/assets/9fe40c54-19e2-4007-96fd-e15f4d73421f)
试试这种方式，如果可行可以PR
