### ISSUE TITLE
插件生成的实体属性带“`”符号后，查询返回的相应属性值变为null

### ISSUE THREAD

**Issue by youtao531** [abel533/Mapper#94]
通过mybatis插件生成的实体，属性带“`”符号后，查询时返回的字段会变为null，若去掉该符号则能正常返回数据库中的值。

**Comment by abel533** [comment]
贴代码看看，查询sql也发出来。

**Comment by youtao531** [comment]
![2](https://cloud.githubusercontent.com/assets/8513513/25661142/e0969412-3041-11e7-857e-6d5919183b47.png)
![1](https://cloud.githubusercontent.com/assets/8513513/25661168/006a385c-3042-11e7-9671-d36a90430edf.png)

**Comment by abel533** [comment]
https://github.com/abel533/Mapper

**Comment by abel533** [comment]
@youtao531 前几天回复时回复错了。。你问题解决了吗？什么原因？

**Comment by youtao531** [comment]
具体原因还不知道，我现在是重写 plugin，默认不添加“`”。
