### ISSUE TITLE
通用mapper在@PostConstruct情况下 触发查询报错!!

### ISSUE THREAD

**Issue by cuipengcx** [abel533/Mapper#96]
![image](https://cloud.githubusercontent.com/assets/21178565/25837352/02b98aea-34c0-11e7-90b2-37897efd4630.png)

**Comment by abel533** [comment]
这是由于Mapper还没有处理通用方法就被调用引起的。

**Comment by cuipengcx** [comment]
好像是这样的  怎么解决那？

**Comment by longzhiwuing** [comment]
我也遇到这个问题了，在@Configuration的配置文件中，如果注入mapper相关的service，查询数据库就会报错。有解决思路吗？或者可以调整执行先后顺序吗？等mapper初始化完，再autowire？

**Comment by cuipengcx** [comment]
我是自己写sql了

**Comment by zhuwenjie11** [comment]
我也遇到这个问题，请问有办法解决吗？ @abel533

**Comment by tastypinenut** [comment]
@abel533 请问这个问题什么时候可以解决，或者有什么方法可以避免？
