### ISSUE TITLE
对象里面有其他对象这种支持吗

### ISSUE THREAD

**Issue by jimmy384** [abel533/Mapper#97]
实体类是不是必须是基本类型的，像Order对象里面有一个Customer对象这种可以吗？还是说只能是customerId

**Comment by abel533** [comment]
可以是复杂类型，但是需要通过`@Transient`忽略非表字段。

**Comment by jimmy384** [comment]
@abel533 我想要的效果是查询出Order的时候，Order里面的Customer也查出来了，原生的mybatis是通过<association class="Customer" select="根据customer_id查Customer的语句"，我是想要这种效果，你说那个不明白你说@transient跟这种有什么关系，我知道@transient的作用

**Comment by abel533** [comment]
不支持复杂查询，只是单表。
